### ISSUE TITLE
scalatags data-

### ISSUE THREAD

**Issue by codingismy11to7** [japgolly/scalajs-react#101]
Is there a way in the customized scalatags for this project to do `data-` attributes? I eventually figured out that I could do `Attr("data-target") := "#something"`, so maybe that's the best way...just wondering if there was something better.

**Comment by japgolly** [comment]
You can do as you've done above. The recommended way is like this:
```scala
val stuff = "data-stuff".reactAttr

stuff := "blah"
```

**Comment by codingismy11to7** [comment]
Thanks, sorry about opening the issue (I see this in the docs, now) - got confused since scalatags proper has docs specifically about data-, but couldn't find anything related in this modified scalatags.

**Comment by japgolly** [comment]
No worries at all :) Happy coding!​
