### ISSUE TITLE
Release new version for React 19

### ISSUE THREAD

**Issue by nghuuphuoc** [japgolly/scalajs-react#1097]
React 19 was [released](https://react.dev/blog/2024/12/05/react-19) a couple of days ago. Do we need to release a new tag to support that version?
I'm using `3.0.0-beta6` and React/ReactDOM 19.0.0 without any issues.

**Comment by rpiaggio** [comment]
Hi @nghuuphuoc! React 19 seems to be backwards compatible with 18, so what you are doing is fine and is the way to proceed if you want to use the 19 release, no new releases of scalajs-react are necessary.

Eventually, the idea is to implement the new functionality of React 19 (PRs welcome!), at least the UI features. When that happens, compatibility will break and we will update the required version of React.

**Comment by nghuuphuoc** [comment]
Thanks you, @rpiaggio. So it's good to go now!
