### ISSUE TITLE
Why not use scala's inline XML feature?

### ISSUE THREAD

**Issue by nornagon** [japgolly/scalajs-react#112]
```scala
scala> <div>{Seq(1,2).map { (x:Int) => <span>{x}</span> }}</div>
res5: scala.xml.Elem = <div><span>1</span><span>2</span></div>
```

**Comment by japgolly** [comment]
1. Inline XML is on its way out of Scala. It will be removed entirely from 2.12.
2. Scalatags is concise where XML is verbose.

That being said, I would accept a PR + an answer on what to do in 2.12 onwards.

**Comment by nornagon** [comment]
Ah, I wasn't aware that inline XML was destined for the trash. Scalatags also seems to offer a little more in the way of type-safety.

**Comment by japgolly** [comment]
Ah yeah, it does. I forgot that it also prevents typos and invalid tags &
attributes.​

**Comment by japgolly** [comment]
I made a mistake. They're getting rid of XML literals in Scala 3 (dotty), not Scala 2.12.
