### ISSUE TITLE
Issues with overloaded methods (render)

### ISSUE THREAD

**Issue by elacin** [japgolly/scalajs-react#116]
I'm having a lot of fun hacking on scalajs-react, and wanted to raise one issue that keeps bothering me.
In most examples the following style is used:

```scala
    ReactComponentB[List[String]]("app")
      .initialState(State(0))
      .backend(new Backend(_))
      .render((P, S, B) ⇒ {
        val a = S.index
        div(s"State: $a")
      }
      ).build

```

Personally, i always have the urge to rewrite that into the following to get better pattern matching capabilities, and to avoid double set of parentheses if there is more than one statement within the function
```scala
  ReactComponentB[List[String]]("app")
    .initialState(State(0))
    .backend(new Backend(_))
    .render {
      case (_, state, _) ⇒
        val a = state.index
        div(s"State: $a")
    }.build

```

This, however, doesn't work, because of the multiple overloads of `render()`, and scalac spits out 
```
Error:(56, 13) missing parameter type for expanded function
The argument types of an anonymous function must be fully known. (SLS 8.5)
Expected type was: ?
    .render {
            ^
```

So this is, as far as i can see, an unfortunate limitation of the compiler that makes the library a bit confusing to use. Would you consider a PR where I either change the method names or (I'm sure preferably) introduce new wrapper functions so it's easy to disambiguate?

If yes, any naming preference?
- `render`, `renderWithChildren`, `renderComponentScope` 
- or shorter versions like for example `render`, `renderC`, `renderCS`

**Comment by japgolly** [comment]
Hi. Awesome to hear you're having fun. Adding `case` doesn't  make much sense though. You use it to match patterns, or extract data (unapply), and in this case you'd be doing neither (arity ≠ patterns in Scala). You can avoid the double set of parens a different way. Like this:

```scala
    ReactComponentB[List[String]]("app")
      .initialState(State(0))
      .backend(new Backend(_))
      .render { (P, S, B) ⇒
        val a = S.index
        div(s"State: $a")
      }.build
```

How's that?

**Comment by elacin** [comment]
Well yes, that solves it.

the `case` would quickly be needed though, if you for example made a ReactComponentB[(Int, Int)] and wanted to directly unpack the props in the function. I am not sure how many people code like me - I frequently add those `case`s to avoid thinking about when they are needed.

I understand it if APIs are frozen or better kept in line with javascript, but this would have been my proposal anyhow:
```scala
  // ===================================================================================================================
  final class PS[Props, State] private[ReactComponentB](name: String, initF: Props => State) {

    def backend[Backend](f: BackendScope[Props, State] => Backend) = new PSB(name, initF, f)
    def noBackend                                                  = backend(_ => ())

    def render(f: (Props, State) => ReactElement): PSBN[Props, State, Unit] =
      noBackend.render((p, s, _) => f(p, s))

    def renderWithChildren(f: (Props, PropsChildren, State) => ReactElement): PSBN[Props, State, Unit] =
      noBackend.renderWithChildren((p, c, s, _) => f(p, c, s))

    def renderComponent(f: ComponentScopeU[Props, State, Unit] => ReactElement): PSBN[Props, State, Unit] =
      noBackend.renderComponent(f)
  }
```

**Comment by japgolly** [comment]
Ah right, I prefer to create case classes for those. Um, let me think on it a bit. In the meantine you can also do this:

```scala
    ReactComponentB[(Int,Int)]("app")
      .initialState(State(0))
      .backend(new Backend(_))
      .render { (P, S, B) ⇒
        val (first, second) = P // ← you can do this for now
        div(s"State: $a")
      }.build

```

**Comment by elacin** [comment]
Sure. And just to be clear, its the general horribleness of overloaded methods (type inference, following/reading code, error messages) that irks me more than lack of pattern matching in particular, and this was a very visible place in the API, lets say :)

**Comment by japgolly** [comment]
I generally agree with you but you've got to look at context.

*following/reading code, error messages* - only sometimes, depends on context
*type inference* - agree, big problem!
function coercion - biggest problem imo. eg. `as map f` needs `as.map(f(_))` when `f` is overloaded.

This instance (i.e. the render methods and more importantly, the way they're used) don't suffer from the above faults.

**Comment by japgolly** [comment]
For reasons above, I think we should close this. Our limited usage doesn't hit the problems you normally get with overloading.
