### ISSUE TITLE
React Render Visualizer

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#117]
https://github.com/redsunsoft/react-render-visualizer

Just in time for the performance release (0.9).

JS mixins that rely on props & state wont work with Scala stuff but ones like this should be fine.

Also if I want to enable this, I don't want to add it to all components manually. I'd prefer to set it once, have it apply to everything, then turn it off when done. Meaning either global mutability or implicits. :|

**Comment by japgolly** [comment]
Ability to use pure-JS mixins added in 77007776885896fcd170bb9c25de2f3000177634.

Unfortunately the React Render Visualizer mixin doesn't work. Is doesn't give a shit what a component's `shouldComponentUpdate` fn does, it makes its own incorrect decision. Similarly the info it tries to convey about what's changed doesn't work cause it can't unwrap the Scala data.

**Comment by japgolly** [comment]
We now have a Scala version in `Reusability.shouldComponentUpdateWithOverlay`.

Live demo: http://japgolly.github.io/scalajs-react/#examples/reusability

**Comment by slorber** [comment]
that's cool  :)
