### ISSUE TITLE
modState / setState : Future[Unit]

### ISSUE THREAD

**Issue by longshorej** [japgolly/scalajs-react#118]
Hi,

I've had a fair amount of code that uses the callback parameters on `modState` and `setState`. I've created these implicit classes in my codebase to chain various `Future` operations instead of using a callback style API.

I'm wondering if anyone thinks it's a good idea to add these to the library, ideally in a more appropriate place. Not sure exactly what class they should belong in but I find myself using it on `BackendScope` so I placed them there. Downside is that its effectful - I don't think there's anyway around using `Promise` when integrating `Future` with a callback API. Upside is it fits much better with typical Future API usage in Scala.

```scala
class RichBackendScope[P, S](val scope: BackendScope[P, S]) extends AnyVal {
  def modifyState(f: S => S): Future[Unit] = {
    val promise = Promise[Unit]()

    scope.modState(f, () => promise.success {}: Unit)

    promise.future
  }

  def modifyStateM(f: S => Future[S])
                  (implicit ec: ExecutionContext): Future[Unit] = {
    for {
      newState <- f(scope.state)
      _        <- assignState(newState)
    } yield { }
  }

  def assignState(s: S): Future[Unit] = modifyState (_ => s)
}

@inline implicit def iRichBackendScope[P, S](s: BackendScope[P, S]): RichBackendScope[P, S] = new RichBackendScope(s)

// some sample usage

for {
  data   <- someRpcCall()
  data2  <- someRpcCall2()
  _      <- $.modifyState(_.copy( ... data ) )
} yield ...
  
```

**Comment by japgolly** [comment]
Interesting. Seems good.

I'd like to clarify though: this isn't "modState/setState *composition*", it's more just lifting them into futures. The reason that it's not composition is that React's setState (and thus modState) is async and doesn't compose - repeated calls will override each other until the component is re-rendered.
I think you'll find that your `modifyState` fn above if called more than once when in a single future composition, won't work as expected. Eg `modState(+2)` and `modState(+3)` will not result in `modState(+5)`.

**Comment by japgolly** [comment]
(Btw, state monads *do* compose so if ever I need multiple `modState`s in the same pass, I use `runState` in the Scalaz ext instead of `modState`.)

**Comment by longshorej** [comment]
Sorry - wrong terminology :)

I do want to clarify that modifyState in a future composition does compose. Each "step" results in a full rendering of the component after the previous "step" has completed. Suppose you have a `Int` as the state:

```scala
      for {
        _ <- scope.modifyState(_ + 1)
        _ <- scope.modifyState(_ + 1)
        _ <- scope.modifyState(_ + 1)
        _ <- scope.modifyState(_ + 1)
        _ <- scope.modifyState(_ + 1)
      } yield {}
```

This will result in the component being rendered 5 times. With a start state of 0, you'll see 5 at the end of it. However, if you were just calling scope.modifyState() inline - instead of in flatmaps - indeed each invocation would overwrite the previous, leaving you with 1 at the end.

Anyways, I find this API to be very powerful for consuming asynchronous data via e.g. Autowire, so just wanted to share.

**Comment by japgolly** [comment]
Oh because the `promise.success` is in the `modState` callback? Is that a good thing? Ideally wouldn't you want all of those transformations bundled into a single pass. Causing render passes only to throw the work away re-render them immediately times isn't gonna be good for performance.

(Btw aside from this composition issue I'd like to hash out, this seems like a nice addition to the library :+1: )

**Comment by longshorej** [comment]
Yeah, it's in the callback. I think I am not communicating the typical use-case clearly. For just chaining together everything in one pass, I just use basic scala currying to build a single modify function, or as you suggested the scalaz Ext code could be used.

With this API, the intent isn't to chain `modifyState` calls as much as it is to integrate component rendering into chaining `Future`s. My prior example was just to demonstrate when the promise is completed - I agree that shouldn't really be done in practice because of rendering inefficiencies.

Maybe a more clear usage in my code is something like:

```scala
// lets say this takes 10ms before it is completed
val fastData = getSomeDataViaSomeAjaxCall()

// lets say this takes 1 minute before it is completed
val slowData = getSomeVerySlowLoadingDataViaSomeOtherAjaxCall()

for {
  fast <- fastData
  _    <- $.modifyState(_.copy(fastData = fast))
  _    <- dispatchSomeNotification("partially loaded .. feel free to use the component")
  slow <- slowData
  _    <- $.modifyState(_.copy(slowData = slow))
  _    <- dispatchSomeNotification("fully loaded .. look at all that extra data")
} yield {}

// dispatchSomeNotification() could be anything that returns a future, e.g. an
// observer system that renders another react component and returns a future
// when it has rendered.
```

Does that make sense?

**Comment by japgolly** [comment]
That makes perfect sense, and thank you. We can just make a mention of the composition semantics as a method comment to be kind.

We'll get this in 0.9.0. If you could submit a unit test that would be :+1:  :+1: :smile: .

**Comment by japgolly** [comment]
Names don't really matter so much when the types tell the whole story but I would like consistency.
We currently have:

* `setState` - Plain 'ole do-it-now.
* `setStateIO` - IO monad (for callbacks).
* `setStateL` - Lenses.

How about we use `F` for these `Future` supporting methods. (Or `A` for async? Nah `F` probably better hey?)

So
* `setStateF: S => Future[Unit]`
* `modStateF: S => S => Future[Unit]`
* `modStateF?: S => Future[S] => Future[Unit]` <- not sure.. `FB` with second `B` for (monadic) bind?

**Comment by longshorej** [comment]
Great! Name suggestions sound good to me. I was using modStateM for monadic but b for bind works too. I'll submit a PR with a test sometime in the next week.

**Comment by japgolly** [comment]
Btw, when you submit a PR, could you please submit it against the 0.9 branch instead of master? 0.9.0 is the next release, due in 9 days. Cheers.

**Comment by longshorej** [comment]
I'll have to be upfront here: Work is pretty nuts right now and I don't see having time to look at this until next month. Maybe we should target the next release? Sorry about this!

**Comment by japgolly** [comment]
No worries! I can emphatically relate. There'll be other releases, we'll get it in one of those when you're ready. Thanks for letting me know :+1:

**Comment by japgolly** [comment]
Added via 41ed6f7074436c311a661639fa0b4b38f071be20.
Usage example in unit test at bottom of patch.
