### ISSUE TITLE
Have mixins apply to more than ReactComponentB

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalajs-react#130]
Currently scalajs-react serves its main purpose as reactjs wrapper (everything related to DOM /browser) .  how about making its flexible so that native / somex implementation of reactJS can  reuse the core !

Example :  

```scala
 def install[P, S, B <: OnUnmount, N <: TopNode] =
    (_: ReactComponentB[P, S, B, N]).componentWillUnmount(_.backend.runUnmount())
```

install is constrained to ReactComponentB(which is coupled with browser React!) .How about having a some  base trait so that we can inject different implementation we need ? or is there any better way to handle these scenarios ?

**Comment by japgolly** [comment]
You want to apply a Scala mixin to a JS component?

**Comment by chandu0101** [comment]
ReactComponentB - reactjs-browser impl 
ReactNativeComponentB - react-native impl

currently if i want to use OnUnmount out of box ,it doesn't allow me because its expecting ReactComponentB

**Comment by japgolly** [comment]
Ah I see. `ReactComponentB` was never meant to be more than a build for React.JS. It would probably require significant thought and effort to generalise the library to directly support more than React.JS. I'm not saying no, but I don't have the capacity to focus on something like that now.

**Comment by japgolly** [comment]
If you want, you could suggest small changes to the library, one at a time, that we could consider implementing.

Or maybe better would be if you created your own branch, customised is it little as possible but just the necessary things, get React Native working however you want, then after using it for a while come back to me with the changes and we can consider incorporating them.

**Comment by chandu0101** [comment]
it just came to my mind ,once we upgrade to 0.14 we no longer need ReactComponentB right ?

**Comment by japgolly** [comment]
When we upgrade to 0.14 I think we'll support components as traits. `ReactComponentB` will still exist but be optional.

(Warning: This is the plan - when 0.14 comes out there's still a possibility that I could try and fail, find out we're unable to do so.)

**Comment by chandu0101** [comment]
> we'll support components as traits 

implies current mixins should be redesigned isn't it?

**Comment by japgolly** [comment]
Yeah, it certainly does imply that. It's going to be work when it comes.

**Comment by chandu0101** [comment]
pretty cool , we'll discuss about this when time comes! , till then i'll copy paste stuff :)

**Comment by japgolly** [comment]
Sounds good mate

**Comment by japgolly** [comment]
I believe this is no longer on the radar.
