### ISSUE TITLE
Implement ReactJS context

### ISSUE THREAD

**Issue by slorber** [japgolly/scalajs-react#132]
Contexts can be used to pass data to a whole hierarchy of components.
https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html
(this may be outdated but gives you the idea)

This is undocumented by React on purpose as the feature may evolve  (it changed a bit in 0.13 I think) but it won't disappear and is already used by a lot of frameworks (like Flux frameworks, React-Intl etc...)

I use this to put data that barely never change like current user id, or app language.

Typically I think things like your broadcast/listenable feature should be injected in an app by a context as it removes the need for a singleton eventbus. One should be able to broadcast messages from outside of React components, as well a one should be able to listen from outside (I do this for example to handle communication with iframes or websockets: don't want to put this in a component)

**Comment by chandu0101** [comment]
looks like its a must feature we should implement! .

from https://github.com/wav/material-ui-scalajs-react : 
>scalajs-react currently doesn't have a way to define a react context. A fork is used as a hack.

here is the hack he is using 

https://github.com/wav/scalajs-react/commit/0510e35ada18f2bd8f5065572c261086bad30266

i wonder why he didn't sent a PR!

**Comment by wav** [comment]
@chandu0101. I was planning to tonight or tomorrow sometime time when I've fleshed it out a little more. Currently it was a hack to see if it works. Ideally, you would pass in a trait that had the two context properties and the builder would add it to the spec. I haven't had any issues with it thus far.

**Comment by chandu0101** [comment]
@wav cool  ok , waiting for PR  . I think it also useful to have a unsafespec method, in future if new feature comes we can atleast get it working in un safe manner instead of waiting for new release!

offtopic : any specific reason for disabling issues in your material-ui wrapper project ?

**Comment by japgolly** [comment]
Just briefly for now: could you please include a small test case in the PR.
I want to confirm it works now on React 0.12, but will also need to confirm
it doesn't break when we upgrade to 0.14. Thanks!

**Comment by wav** [comment]
Ok will do tonight. At work atm.

**Comment by japgolly** [comment]
Take your time, there's no rush :)
Next release is probably about 2-3 weeks away.

**Comment by slorber** [comment]
Notice in 0.14 there's the official switch from owner-context to parent-context.

If you use "portals" for exemple for modals/tooltips you have to use a new method `renderSubtreeIntoContainer`

See 
https://github.com/facebook/react/issues/4081
https://github.com/rackt/react-modal/issues/37


As far as I'm concerned there's no api change about context in 0.14, only the way to use the api changes so it should be safe for scalajs-react to implement it and point to the related ReactJS documentation

**Comment by wav** [comment]
#144 

Ive had a go at this today. I don't know of a nice way of accessing the context. I'm using `.asInstanceOf`. My preference is something like a `Ref` object, alternatively you can thread a `C` parameter through the builders and scopes, but that's too invasive at this stage. The tests are inspired by the react tests.

**Comment by japgolly** [comment]
Closed via #143.
