### ISSUE TITLE
Example integration in a real-life JS project

### ISSUE THREAD

**Issue by slorber** [japgolly/scalajs-react#133]
Is there any example setup available that is usable for a real-life application?

I guess this is related to https://github.com/japgolly/scalajs-react/issues/8 about Interop as we must be able to use pure JS React components (like Router, React-Intl, React-Date-Picker etc...)

We tend to use tools like Browserify or Webpack to be able to use any kind of NPM published libs.
We can't rewrite everything in Scala.
We also use custom build setups with Grunt or Gulp. 

We have to control bundling behavior and not rely on single JS files imported separately with a script tag. 

One thing that we often do is split our app into 2 parts: `libs.js` (does not change often so can be cached agressively) and `app.js` (see https://github.com/sogko/gulp-recipes/tree/master/browserify-separating-app-and-vendor-bundles)

Many people developping production ReactJS apps are also using Flux frameworks. It would be nice to know how this can be integrated with scalajs-react. Should we write a Flux implementation on top of your lib, or should we try to integrate existing ones?

For these reasons it would be great to have an example setup that uses let's say Browserify + Gulp + Flux. I'd like to try your lib on a real project but without these things it will be vey hard for me :s

A bonus would be to have a setup that supports hot reloading of scalajs-react components :)

**Comment by japgolly** [comment]
A lot of the packaging aspects wrt Scala.JS aren't addressed yet. In my case I use Scala.JS to create a JS file and have grunt & bower take care of the rest of the JS deps. It's quite a custom setup. A while back I extracted just my SBT built: https://github.com/japgolly/sbt/tree/skeleton. It's grown organically more than thoughtfully and it a bit messy.

As for Flux, I don't support it in scalajs-react. I don't want to touch it. Just as it's a separate JS  library I'd prefer someone create a separate Scala.JS version of it that works with scalajs-react just like the original does with React itself. Provided it is useful in Scala-land. AFAIK certain people that use scalajs-react are still trying out different ideas and alternatives around that. Our gitter chatroom would be a good place to talk about it in more detail. Just reading through the recent history you'll see a number of libraries ppl are considering. :)

There is a great example project here:
https://github.com/ochrons/scalajs-spa-tutorial

Hot reloading:
https://github.com/lihaoyi/workbench

**Comment by slorber** [comment]
Thanks will take a look at your links.

Another thing that is concerning me is the ScalaJs compilation time, the output bundle size, and the ability to split my app into multiple modules (and maybe publish them on NPM)

**Comment by japgolly** [comment]
> Another thing that is concerning me is the ScalaJs compilation time, the output bundle size, and the ability to split my app into multiple modules (and maybe publish them on NPM)

Yeah publishing into multiple modules will probably be via SBT with the target being Maven Central or bintray or something. You'll likely need to wait at least a year *(my guess only)* before the Scala.JS ecosystem starts producing to NPM et al.

Regardless those are Scala.JS community issues so let's close this. As for an example project, some community members are doing great work in #54 on this so let's track it there.
