### ISSUE TITLE
Warn when Route `string` DSL value captures a group

### ISSUE THREAD

**Issue by Daxten** [japgolly/scalajs-react#142]
Example Router:
https://gist.github.com/Daxten/2c4d9dbc7a169adebf2f

will print 2 times the first argument.
As a minor addition, IntelliJ Code Completion is broken. In Line 15 "e" will be of Type Pages, and not of Type ProjectPage as expected.

**Comment by japgolly** [comment]
Change
```scala
  val regExRoute = "([^/]+)"
```
to
```scala
  val regExRoute = "[^/]+"
```
and it should be fine.

Also note that such a pattern can collect chars like `?` `#`, I think it's best to use a whitelist approach like `[a-zA-Z0-9_]+` or something instead of a blacklist approach.

**Comment by Daxten** [comment]
Hm that really fixed it thanks! Thought I checked that already..

any comment on the Intellij Code Completion? Most likely something which can only be fixed by Intellij?

**Comment by japgolly** [comment]
@Daxten Hey, nah that's just IntelliJ being IntelliJ. 10% of my codebase is red according to IntelliJ. Hopefully one day they'll fix their stuff.

**Comment by japgolly** [comment]
Closing with 12a95e008f781d69c4901cabbf625d05f0e3bcf7.

Was going to put a check in but I don't think JS regex allows us to check. (https://github.com/scala-js/scala-js/issues/1727)
