### ISSUE TITLE
Unify --> ==> ~~>, remove IO, add Callback

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#145]
The attempt to satisfy everyone by supporting unsafe callbacks (? => Unit) and using Scalaz's `IO` has created a division and incompatibility between code. Very bad for community. Already seeing small spots of pain with shared libraries & components.

We need to just have one, single, common way.

The solution:
* A simple, lightweight built-in `Callback` type. All callbacks are wrapped in it - simple.
* We have 1 operator instead of 3.

Will probably do this earlier rather than later. The longer we wait the worse the change is going to be.
Migration is doing to be a day of pain for everyone, but a worthy one-time price to pay for a lifetime of happiness when everyone's libraries & shared components are compatible.

I'm even considering a quick 0.10.0 to get this over and done with before React 0.14 comes out.

**Comment by ngbinh** [comment]
:100: had to come back and replace all of our `unsafePerformIO` with `IO` version.

**Comment by japgolly** [comment]
At the same time, should probably also remove variance from React type ctors. It's causing such a frustrating headache having to pepper every new addition to extra with special helper methods to deal with type inference problems.

**Comment by japgolly** [comment]
Done and on https://github.com/japgolly/scalajs-react/tree/topic/v0.10
