### ISSUE TITLE
React 0.13.03 - Animation using addon ReactCssTransitionGroup causes  --> Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined

### ISSUE THREAD

**Issue by bkkoo** [japgolly/scalajs-react#150]
On React library version 0.12.2, your animation example work fine but when using 0.13.03 , it causes this error --> Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined. I have looking in the source code the "object Addons" in "Addons.scala" file  line 28 and 29  

line 28 -->    val f = React.addons.CSSTransitionGroup
line 29 -->    f(toJs, children.toJsArray).asInstanceOf[ReactComponentU_]

the f variable that hold the CSSTransitionGroup (js.native) component on line 28 and is apply on line 29 might cause this error. Calling it directly as following does not cause such error but the transition does not work and there are no "h1" html dom node and it's children in html document. 
   
    val items = Seq(^.p( ^.key:=0, "item0") , ^.p(^.key:=1, "item1"))
    val ts = ReactCssTransitionGroup("example", component="h1")
    React.addons.CssTransitionGroup(ts.toJs, items.toJsArray).asInstanceOf[ReactComponentU_]

I've google about this error, it might be 0.13 breaking core change as following statement...
  
  - Deprecated patterns that warned in 0.12 no longer work: most prominently, calling component classes    without using JSX or React.createElement and using non-component functions with JSX or createElement

Do you have any plan supporting 0.13.03?

**Comment by chandu0101** [comment]
if you wrap with React.createFactory everything works fine 
https://github.com/chandu0101/scalajs-react-components/issues/9

>Do you have any plan supporting 0.13.03?

https://github.com/japgolly/scalajs-react/issues/95

**Comment by bkkoo** [comment]
According to your solution, I've to code it using js.Dynamic like below:  
val f =  React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.global.ReactTagsInput)

**Comment by chandu0101** [comment]
yeah just  add a createFactory guard ,if you want this change in upstream , just send a PR for transition group :)

**Comment by bkkoo** [comment]
Thank you.

**Comment by japgolly** [comment]
Fixed in 9558c11144e2b871a3180a433e3b312906f4f302
