### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalajs-react#156]
http://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html
http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

**Comment by chandu0101** [comment]
if any one want to play .. , i added to webjars npm 

```scala
  val reactJSVersion = "0.14.0-beta1"

      jsDependencies += "org.webjars.npm" % "react" % reactJSVersion % scope / "dist/react-with-addons.js" commonJSName "React",

```

**Comment by japgolly** [comment]
That's awesome. All those vdom alternatives and vdom benchmarks all over the internet that mostly miss the point. Now that React plan to make the vdom backend swappable we can have best of both worlds!

**Comment by chandu0101** [comment]
@japgolly  yeah future is bright .. , whats the plan now , new module(reactdom)! (or you still prefer core for both react and dom)

how about ES6 component  style .. ,  looks like its  not possible with current scala.js 

>You currently cannot emit a ECMAScript 6 style class with Scala.js. You can chain prototypes as you would in ECMAScript 5. However, this will probably be very verbose. Consider using React's createClass function. –  gzm0

http://stackoverflow.com/questions/31116258/how-to-provide-and-consume-require-js-modules-in-scala-js-and-extending-classes

this question is un answered both in SO and gitter ...

**Comment by japgolly** [comment]
>  whats the plan now , new module(reactdom)! (or you still prefer core for both react and dom)

I plan to mirror whatever React does. So if they split into react & react-dom then this project will have a module for each such that someone who only wanted to use react core (without react-dom) in Scala.JS could do so.

In the next major release I'll probably lump all the big changing things together (components as classes, React 14, unify `-->`/`==>`/`~~>`). Even if I only focus on React 14 it's going to be significantly  backward-incompatible by the look of it so we as well do all the breaking things at once. Less pain for us all to change our projects.

Re; the es6 stuff - no idea.

**Comment by chandu0101** [comment]
cool ok ,

>components as classes , Re; the es6 stuff - no idea.

are you going to use original React.Component in component as classes design or same old React.createClass ...

**Comment by japgolly** [comment]
I haven't looked into it so I don't know yet.

If you have reasons about how you think things should be done, possible
benefits and/or penalties of solutions, etc, just drop them all here into
this issue. When time comes for me to start working on this I'll read them
all and factor them into the decision making.

**Comment by chandu0101** [comment]
Definitely , i'll drop here when i have something ..

**Comment by chandu0101** [comment]
yay https://github.com/scala-js/scala-js/issues/1795

**Comment by japgolly** [comment]
RC1 is out. http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

**Comment by japgolly** [comment]
Re functions as components:

> spicyj 1 hour ago
>
> They are components in that they render later, but they don't support any lifecycle methods. We'll probably add some sort of "pure" flag via static properties on the function later.

https://news.ycombinator.com/item?id=10199162

**Comment by ngbinh** [comment]
Relased http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by japgolly** [comment]
Thanks!​

**Comment by japgolly** [comment]
Can't get `ReactDOMServer` working with Scala.JS:
https://github.com/scala-js/scala-js/issues/1945

**Comment by japgolly** [comment]
Temporarily disabled `ReactDOMServer` in 570a85ff8dbbafa9ef2c3a71d07ad59ab8c73490.

**Comment by japgolly** [comment]
Will include the `inlineElements` optimisation later after 0.10 is released. Track in #192

**Comment by japgolly** [comment]
Done in 00209551d4ef3f42d5ce8825d9df239868f2a326 and 39caf50efd913f4723a6878ed8171d45a5583d3d.

**Comment by japgolly** [comment]
Oh crap: pending resolution of the `ReactDOMServer` issue (link above).

**Comment by japgolly** [comment]
Beh, `ReactDOMServer` doesn't matter for now. We'll see how scala-js/scala-js#1945 goes.
