### ISSUE TITLE
Add onLoad and onError support for img

### ISSUE THREAD

**Issue by Alefas** [japgolly/scalajs-react#159]

**Comment by japgolly** [comment]
`onLoad` is already there.
Added `onError` in 56e54ce.

**Comment by Alefas** [comment]
I tried to use custom onError attribute, but it didn't work, so I think this "onError" attribute will have similar result. As I understood, react.js requires some special code to enable it (there are few libraries for that), but would be great support it natively in Scala.js.

**Comment by japgolly** [comment]
I searched their repo and saw that both attributes were added in React 0.9 ([src](https://github.com/facebook/react/blob/38acadf6f493926383aec0362617b8507ddee0d8/docs/_posts/2014-02-20-react-v0.9.md)). I'd imagine it should just work. If not I'll need more info to go on, PR with test  case would be even better.
