### ISSUE TITLE
Unable to create a React element on server side

### ISSUE THREAD

**Issue by Synapski** [japgolly/scalajs-react#160]
I'm trying to render a Rect element on the server server (I'm using Play) :

```scala
def index = Action {

    val elem =
      <.div(
        <.h1("test")
      )

    Ok(React.renderToString(elem))
}
```

but I'm getting the following error :
```
java.lang.ClassCastException: java.lang.String cannot be cast to japgolly.scalajs.react.ReactNode
```

Is it possible to render my React element on the server side ? (it is working fine on the client side)

**Comment by japgolly** [comment]
I don't use Play nor have I tried to use React on the server but I can't see how it would work. React requires JS which as I understand it, means you'd have to compile scala to JS, supply React JS and run both (as JS) on the server, maybe in something like Nashhorn. So no I can't imagine you getting code like above working in Play without doing much plumbing yourself to enable it.

**Comment by Synapski** [comment]
I understand. I'll see if I can come up with a solution using Nashhorn on the server side. Thank you.

**Comment by nafg** [comment]
@japgolly To render on the server, why do you need React? React is great at updating the dom based on changes to the vdom etc., but for the initial version of the page you don't need any of that. Can't you just call the scala render functions and pass them something and get something back that can be stringified and pushed out as text/html?

**Comment by japgolly** [comment]
First, I'm pretty sure that if you trying to do what you're suggesting and duplicate React's vdom→html logic, there'd be a number of minor differences in the output. React makes more minor and subtle changes than I know.

Second, I wonder how it handles callbacks? eg. `<button onclick="???">...`

Third, if you're will to volunteer something, it should probably be in a separate module, at least until it matures. If there's anything about this library that blocks the ability to do that then we can get that fixed first.

**Comment by nafg** [comment]
Good point about callbacks. Maybe we need to find out what they do in the js community. I can't think how "run react on the server" would solve the callback issue either.

**Comment by easel** [comment]
I imagine you have to generate an html document with all the appropriate react-id's and such and then start react on the client, telling it to take over the existing id's. That should allow it to wire in the event handlers and start rewriting things pretty seamlessly.

**Comment by nafg** [comment]
What you could do is skip the event handlers etc., and then immediately on
page load call React.render. So a quick "cheat" so the page isn't blank,
but it isn't really "live" until React runs on the client.

**Comment by nafg** [comment]
Some relevant info: http://redux.js.org/docs/recipes/ServerRendering.html

Also you can see what the generated markup looks like here: http://react-serverside-rendering.herokuapp.com

I think it's basically doing what I wrote in https://github.com/japgolly/scalajs-react/issues/160#issuecomment-222198220, but it has to generate a data-react-id for each component.

http://stackoverflow.com/a/33967810 explains that pretty well.

**Comment by MasseGuillaume** [comment]
Also since react itself is in javascript you need a runtime. Spinning a v8 server, a proccess or using Project Nashorn would tackle the runtime issue.

**Comment by nafg** [comment]
@MasseGuillaume my objective is to do the server side part without react

**Comment by nafg** [comment]
I put some of the markup generated by that app in a gist: https://gist.github.com/nafg/e2be058a2fc85689243247acb3c00a81

The javascript is in a transpiled bundle so not as obvious what to send there

**Comment by japgolly** [comment]
@nafg I'm pretty hesitant about the reliability of something that duplicates React and then needs to interoperate with it later. Even if you find all the edge cases where the generated code differs (between yours and what React does and expects), every time a new React comes out you'll have to update and retest everything.

What's your worry/aversion to using React proper on the server-side? Is it performance (time)? If so, you might want to run some benchmarks cos I think Java 8's JS engine is supposed to be pretty fast and may get faster if you keep a bunch of ThreadLocal ones around. Then again you'd also want to know what the space (memory) impact is too.

**Comment by nafg** [comment]
@japgolly for one, I think @sjrd mentioned that Nashorn has a bug that prevents it from running scalajs. That's why sbt plugin uses rhino which is slow.

Also, if a pure-Scala implementation could rely only on public APIs it's not that concerning. But that might be a big if, of course. 😂

But yeah, if we could just run it on Nashorn that would be great and simple.

**Comment by nafg** [comment]
Also I figured the links might be interesting to people who Google takes to this ticket.

**Comment by japgolly** [comment]
Oh my. I think SBT uses Rhino because they want to support Java 6+. I didn't know that Nashorn can't run SJS! That's shocking.

(And re links, yeah sure, more info is good.)

**Comment by matthewpflueger** [comment]
It has been awhile but following [this post](http://winterbe.com/posts/2015/02/16/isomorphic-react-webapps-on-the-jvm/) worked for me.  I have a [small template repo here](https://github.com/matthewpflueger/isomorphic). Look at [HelloWorld](https://github.com/matthewpflueger/isomorphic/blob/master/jvm/src/main/scala/com/github/matthewpflueger/isomorphic/server/HelloWorld.scala) to see what worked for me with Nashorn...

**Comment by MasseGuillaume** [comment]
>  I think @sjrd mentioned that Nashorn has a bug that prevents it from running scalajs

Do you have quote for that ?

**Comment by sjrd** [comment]
> Do you have quote for that ?

Here's your quote: ;)

Nashorn has a bug that prevents it from running Scala.js.

**Comment by sjrd** [comment]
To be fair, Rhino has the same bug. However Rhino has more hooks, which allow us to work around the bug.

The bug is that both try to create JVM methods of more 64k something (bytes of bytecode, IIRC), and their back-end crashes.

**Comment by MasseGuillaume** [comment]
```scala
val engine = new javax.script.ScriptEngineManager().getEngineByName("nashorn")
engine.eval(new java.io.FileReader("/home/gui/fluffy-broccoli/test.js"))
// function test(a){
//  return a + 1;
// }: Object
engine.eval("test(1)")
// 2: Object
engine.eval(new java.io.FileReader("/home/gui/fluffy-broccoli/webapp/js/target/scala-2.11/webapp-fastopt.js"))
// null
engine.eval("ch.epfl.scala.index.client.Client.test(1)")
// nope
```

**Comment by MasseGuillaume** [comment]
@sjrd It look like it works for me (tm) !

**Comment by sjrd** [comment]
Your app might be small enough that it does not trigger the bug. It's really a size issue. Can it parse the Scala.js test suite? (produced by `sbt testSuite/test:fastOptJS` in the scala-js/scala-js repo)

**Comment by MasseGuillaume** [comment]
cloned scala-js/scala-js
added
```scala
import scala.scalajs.js
import js.annotation.JSExport

class Foo(val x: Int) {
  @JSExport
  def square(): Int = x*x // note the (), omitting them has a different behavior
  @JSExport("foobar")
  def add(y: Int): Int = x+y
}
```
in the test suite

```
scala>  val engine = new javax.script.ScriptEngineManager().getEngineByName("nashorn")
engine: javax.script.ScriptEngine = jdk.nashorn.api.scripting.NashornScriptEngine@4187c91b

scala> engine.eval(new java.io.FileReader("/home/gui/scala-js/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js"))
javax.script.ScriptException: TypeError: Cannot read property "prototype" from undefined in <eval> at line number 465
  at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
  at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
  ... 42 elided
```

same error if I try to load it in v8
```bash
$ node
> var a = require('/home/gui/scala-js/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js'); 
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/gui/scala-js/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:262609:143)
    at Object.<anonymous> (/home/gui/scala-js/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:324985:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
```

**Comment by japgolly** [comment]
Shit. I never thought I would but now I need this too.

I have a feeling this will prioritise the redesign which very clearly exposes all the underlying raw JS components. No idea how yet but it seems you might need to take our Scala components back out of Scala-land for this...

**Comment by matthewpflueger** [comment]
This is an interesting read about the data-reactids that are generated.  A bit old but gives some insight.  Seems the ids are random...

https://github.com/facebook/react/issues/1666

**Comment by japgolly** [comment]
Personally, I'm going to workaround this. I strongly dislike the idea of running server-side JS in response to a user request due to negative impact to response time, and server-side resources.

Instead, and because I only need this sparingly and for "Loading" pages until the SJS kicks-in, I'm going to embed results of `ReactDOM.renderToStaticString` into my server, and just transform a few values like username and such. If anyone's interested I can share my strategy of doing the above and ensuring validity so that transforms or content doesn't go stale or break.

**Comment by matthewpflueger** [comment]
I am definitely interested. Perhaps the strategy can be put into the docs?

**Comment by ricsirigu** [comment]
@japgolly @matthewpflueger I'm interested too
