### ISSUE TITLE
ES6 classes

### ISSUE THREAD

**Issue by nlhkh** [japgolly/scalajs-react#165]
This is just a suggestion. Since the way most people write React code is with ES6 class, would it be intuitive if we leverage Scala class to create React component instead of using `<`?

**Comment by japgolly** [comment]
It's on the roadmap in #87; closing as duplicate.

> the way most people write React code is with ES6 class

FYI I only use React as a Scala user, I've never used JS classes or know much about them. Thus my perspectives will be different to someone who has. Feel free to offer suggestions but I'll probably need more info to help understand pure JS-world stuff (like anything to do with ES6).
