### ISSUE TITLE
Fix up confusing overloaded ReactComponentB.render methods

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#168]
v0.10 is a big refactoring release. As we're all going to be combing through our codebases now is the best time to redo the ambiguous overloaded `render` methods in `ReactComponentB`.

**Comment by guersam** [comment]
:+1:

**Comment by elacin** [comment]
wonderful! :)

**Comment by japgolly** [comment]
@elacin I remember you suggested this a while ago. The time is now ripe!

**Comment by japgolly** [comment]
This is going to very annoying for us all to manually update in our codebases (especially my massive work one). :weary: It's for the best. That's what v0.10 is all about.

Done in 04f11a6a8cc5830e9ae315a1da3085ea3660da5d

New render methods:
https://github.com/japgolly/scalajs-react/blob/04f11a6a8cc5830e9ae315a1da3085ea3660da5d/core/src/main/scala/japgolly/scalajs/react/ReactComponentB.scala#L69-L100

**Comment by japgolly** [comment]
FYI, similarly updated `initialState` methods for consistency in 5346cfe05b5e50aeeeddc0e250645844df42d58a

**Comment by elacin** [comment]
I hadn't noticed until now, but among all those render() alternatives you somehow left out the only two I will use, hehehe. Can we add these (I'll leave the naming system to you)?

```scala
def renderR(f: (P, S, B) => ReactElement): PSBR[P, S, B] =
  new PSBR(name, initF, backF, ($: DuringCallbackU[P, S, B]) ⇒ f($.props, $.state, $.backend))

def renderRC(f: (P, S, B, PropsChildren) => ReactElement): PSBR[P, S, B] =
  new PSBR(name, initF, backF, ($: DuringCallbackU[P, S, B]) ⇒ f($.props, $.state, $.backend, $.propsChildren))
```

**Comment by japgolly** [comment]
There are a few reasons.
​There's every combination of P S and C; if I include B the number of
render methods becomes huge.
Second if you're using a backend, it's better organisation and readability
to just add a render method to the backend and then when building the
component have .render(_.backend.render).
Third, it adds a bit more uniformity when building non-trivial components
as it seems, the future of React JS is going to be an abstract class or
similar, and I'd like to start softly shaping scalajs-react in that
direction too.
