### ISSUE TITLE
React 0.13

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#173]
[React v0.13](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)
[React v0.13.1](https://facebook.github.io/react/blog/2015/03/16/react-v0.13.1.html)
[React v0.13.2](https://facebook.github.io/react/blog/2015/04/18/react-v0.13.2.html)
[React v0.13.3](https://facebook.github.io/react/blog/2015/05/08/react-v0.13.3.html)

Relevant stuff:
- [x] Added a new top-level API `React.cloneElement(el, props)` for making copies of React elements. When migrating your code, you may want to use new `React.cloneElement` API (which is similar to `React.addons.cloneWithProps` but preserves key and ref and does not merge style or className automatically)
- [x] Deprecated patterns that warned in 0.12 no longer work
- [x] Added new top-level API `React.findDOMNode(component)`, which should be used in place of `component.getDOMNode()`.
- [x] New ref style, allowing a callback to be used in place of a name: `<Photo ref={(c) => this._photo = c} />` allows you to reference the component with `this._photo` (as opposed to `ref="photo"` which gives `this.refs.photo`).
- [x] `this.setState()` can now take a function as the first argument for transactional state updates, such as `this.setState((state, props) => ({count: state.count + 1}))`.
- [x] New vdom. See 0.13.2 & 0.13.3. Also send over to Scalatags.
- [x] Ignore shit docs, scan `ReactTestUtils` source for API changes.

**Comment by japgolly** [comment]
They also break `ReactTestUtils` without mentioning it in the changelogs.

**Comment by ngbinh** [comment]
:+1:

**Comment by japgolly** [comment]
- `React.addons.createFragment was added`. *[info](https://facebook.github.io/react/docs/create-fragment.html)*

This ↑ moved out of core and into addons in 0.14. Leaving out for now.

**Comment by japgolly** [comment]
Closed via 993d284bae300d5f2464d14f77b44e2529705306

Note: React 0.13 has a fatal issue where in event callbacks, event properties are cleared before `modState` calls are executed. This means that `modState(_.copy(title = e.title))` doesn't work (!). This seems to be fixed in React 0.14.

Regardless, I will publish v0.10.0-M3 with these changes.
