### ISSUE TITLE
Define equality for ClassNameAttr

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalajs-react#177]
```
object ClassNameAttr {
  def :=[T](t: T)(implicit av: AttrValue[T]): TagMod = new TagMod {
    override def applyTo(b: Builder): Unit =
      av.apply(t, b.addClassName)
  }
}
```  

On many of my `Props`, I expose a `style: TagMod` attribute to allow parents to style the outer component.  This gets converted to a ClassNameAttr which does not define any equality breaking my ability to use shouldComponentUpdate simply for case classes.

Would you be up for a PR addressing this?

**Comment by japgolly** [comment]
Sorry, I don't quite follow. When you say *"This gets converted to a ClassNameAttr"*, how can you convert a `TagMod` into a `ClassNameAttr`? `ClassNameAttr` is an object. Unless you mean you call `^.className := tagMod` which makes no sense either. Erm, more info?

Also, have you thought about using `Reusability.byRef` for `TagMod`s? That would work if upstream components create a `TagMod` statically, or memoise their `TagMod` generation logic, or have a `Px[TagMod]`. You could also use a `ReusableVal[TagMod]` in your Props, which would allow (well, require) upstream components to provide their own reusability logic when they provide the `TagMod`.

**Comment by matthughes** [comment]
Right, so I have a `Style` from scalacss and when I try to use it as a `TagMod`, I believe, this implicit gets invoked:

```
trait ScalaCssReactImplicits {
  import ScalaCssReactFns._

  implicit final def styleaToTagMod(s: StyleA): TagMod =
    ^.className := s.htmlClass
```
which invokes the code I originally pasted.  The end result is an anonymous `TagMod` with no equals defined.  I am proposing something like this:

```
case class ClassNameAttr[T](t: T, av: AttrValue[T]) extends TagMod {
  override def applyTo(b: Builder): Unit =
    av.apply(t, b.addClassName)
}
object ClassNameAttr {
  def :=[T](t: T)(implicit av: AttrValue[T]): ClassNameAttr[T] = ClassNameAttr(t, av)
}
```

Calling semantics are the same; it's just now `ClassNameAttr` has defined equality.  I can look into `Reusability` as a workaround, but for simple `Props` where everything has defined equality already, I find:

```
    .shouldComponentUpdate((scope, p, s) => scope.props != p)
```
to be just as effective.

**Comment by japgolly** [comment]
Oh right, I get you. Yeah I'm cool with that change on its own, but it's the larger picture I have a concern about. If you're going to rely on `equals` working for `TagMod`, here you create a situation where only `className = xxx` passes, and any other `TagMod` combination or value will always fail. Or from a different angle, if we do this, anyone using your component will have it always update any time they use anything apart from exactly 1 classname (and maybe `EmptyTag`) as the `TagMod`.

That situation worries me a little. Ideally we would have reliable equality for all `TagMod` values, and failing that I lean towards none rather than a small subset (because I believe none would encourage reliable workarounds).

What do you think?

**Comment by matthughes** [comment]
One option is for me to use `StyleA` instead of `TagMod`.  That better implies intent, but 1) forces ScalaCSS on the parent and 2) doesn't let me use the pattern of `style: TagMod = EmptyTag`.  That is, I have to use Option or js.undefOr which obviously is not the end of the world.

From what I can see `ClassNameAttr` is the exception, not the rule in not defining equality.  I do understand your concerns about reliable equality though.  What I don't like about saying: use Reusability.byRef, is there is no way to communicate a contract with the caller at compile-time.  I have to communicate and enforce that pattern with teammates.

**Comment by japgolly** [comment]
ACK on all of that. Re:

> What I don't like about saying: use Reusability.byRef, is there is no way to communicate a contract with the caller at compile-time. I have to communicate and enforce that pattern with teammates.

Very true. Not sure if you're aware but `ReusableVal` alleviates that. If pushes the responsibility to decide and provide reusability onto the caller (with compile-time verification). Although in your specific scenario (a css style), callers might that more annoying than beneficial. It's all about choosing trade-offs :)

If you'd still like to add univ-equality for `ClassNameAttr` and are ok with the deficiency we discussed,  I'm cool to merge it. (I just won't advertise or recommend it.)

**Comment by japgolly** [comment]
Hey @matthughes, I'm gonna close this, it'll create a new ticket if you submit a PR.
