### ISSUE TITLE
Rendering scalatags in scalajs-react render method?

### ISSUE THREAD

**Issue by zv3** [japgolly/scalajs-react#182]
Not sure if this is possible, but if so.. is there an example on how you could render an HTML dom that was constructed using scalatags as a reactjs render output? Or vice versa? 

I'm asking this because I'm thinking it'd be great to share HTML that gets constructed with scalatags, call it like "templates" so that I don't have to write the same thing on my Play Framework HTML template for rendering on the server side (for SEO purposes).

**Comment by japgolly** [comment]
You can use `React.renderToString` to generate HTML that you could use on the server-side.  I think Nashorn is not slow and some simple caching could ensure it's performant regardless.

I'm not aware of any conversion tool you could use at runtime. From memory, two people in Gitter chat made static conversion tools that you might find useful.

But yeah, I'd probably see how they do this in plain JS and do it with the same React support using React on the server-side. Good luck!
