### ISSUE TITLE
unable to do runState on componentWillUpdate

### ISSUE THREAD

**Issue by n3ziniuka5** [japgolly/scalajs-react#189]
```scala
.componentWillUpdateIO { (scope, props, state) =>
  scope.runState { //runState not found
    ST.mod(_.copy(...))
  }
}
.componentDidUpdateIO { (scope, props, state) =>
  scope.runState { //works
    ST.mod(_.copy(...))
  }
}
```

Is this a bug or was this intentional? Should I only do state updates on `componentDidUpdate`?

**Comment by japgolly** [comment]
That's a genuine feature :)

According to the React doco you're not allowed to call `setState` within `componentWillUpdate` and scalajs-react's types encode that constraint.
