### ISSUE TITLE
Input Range Min/Max Not Available

### ISSUE THREAD

**Issue by jclyons** [japgolly/scalajs-react#191]
I'm probably just not seeing how to do this in the source or documentation, but it seems I can't use 'min' and 'max' attributes for ^.input of type "range."

Defining it this way:
```
<.input(
    ^.tpe := "range",
    ^.min := S.sourceData.map(i => i.date).min.getTime,
    ^.max :=  S.sourceData.map(i => i.date).max.getTime,
    ^.onChange ==> B.onChangeRange
)
```

I get this:

`Compilation error[value min is not a member of object japgolly.scalajs.react.vdom.Attrs]`

Are these attributes available? If not, can you make them available in the next version?

**Comment by japgolly** [comment]
It seems they're missing. If you'd like to send a PR, attributes are defined in `HtmlAttrs.scala`.

**Comment by japgolly** [comment]
Ah, it seems I've already added these as part of #173, it just isn't released yet. This will be in the next version of  scalajs-react.
