### ISSUE TITLE
Remove string-based DOM refs?

### ISSUE THREAD

**Issue by oyvindberg** [japgolly/scalajs-react#194]
Hey again! :)

I see you're gearing up for release of 0.10 - really great work so far, looks great!

Just one question though, wouldn't it be better to kill the string references altogether? Now that we're first in API breaking mode?

in the doc it says:

> React also supports using a string (instead of a callback) as a ref prop on any component, although this approach is mostly legacy at this point.

So i would propose we _remove_ the `ref` attribute and replace it with an `withRef` method that takes a callback, both on `ReactTag` and `ReactComponentC`, to have a single consistent interface to references, and leave it at that. 

I played with that idea here: (the diff also contains some semi-related changes, my apologies).
https://github.com/elacin/scalajs-react/commit/fb6d0323b655ae80c3f005e161b3d164ff90544f

WDYT?

**Comment by japgolly** [comment]
Oh I didn't realise the *"this approach is mostly legacy at this point"* part. I wonder if that means they'll remove it in the future...?

Problem is, I like string-based references :smile: Using `Ref` (well, `RefSimple`) in Scala it becomes a nice type-safe solution, where as using the callback method we have to create a variable per component and write side-effects directly into our dom. No problem for JS, but in Scala I think the other way is safer and nicer.

Both ways are usable in v0.10 but personally, I don't plan to use the new callback style myself.

**Comment by elacin** [comment]
Right, different styles there, i personally find the string matching brittle, and would be happy to see it go. 
I haven't read anything about them going to remove it, just saw that quote in the doc for 0.14 (perhaps 0.13 too).

Hey sorry for using the issue tracker as a chatbox again, but since you're here anyway... That same commit also shows an experiment with typing `ReactTag`s (so i can haz some type-safety for my `HTMLInputElement => Unit` ref updates), would that be something you're interested in?

**Comment by japgolly** [comment]
Oh absolutely, string matching is brittle, I agree with that, but using `Ref(Simple)` it puts type-safely on top of that so it's not brittle anymore. The only string-like problem I can think of that would leak though would be duplicate names being used. Or is there something else I haven't realised?

Btw to be clear, this is what I mean and think is ok and safe:
https://github.com/japgolly/scalajs-react/blob/topic/v0.10/test/src/test/scala/japgolly/scalajs/react/RefTest.scala#L21-L26

> Hey sorry for using the issue tracker as a chatbox again

Hehe no problem dude. Actually I would need to go through the commit again but in more detail before I can answer that Q. I only breezed through it - I need to get to work atm :open_mouth:

**Comment by elacin** [comment]
It might come down to confusion on my part that i have used it wrong. There are some moving parts, and some scoping i don't really understand. It has happened quite a bit that i look up references in the wrong context (say you're passing it to a child component) and nothing comes out. 
The callback variant is pretty much fail-safe, even though it necessarily introduces mutability. 

Another thing is the pedagogical side: A type like this: `ref: js.UndefOr[MuiDatePickerM => Unit] = js.undefined,` communicates quite a lot better than `ref: js.UndefOr[String] = js.undefined,` what it is and what you can do with it.

--


About typed `ReactTag`s, I can probably save you the trouble. it comes down to this:
```scala
//covariant, to let a ReactTagOf[html.Paragraph] also be a ReactTagOf[TopNode]
abstract class ReactTagOf[+N <: TopNode] extends DomFrag 
//regain invariance to make compiler happy
private [vdom] final case class ReactTagImpl[N <: TopNode] 
//make sure existing code should be allright
final type ReactTag = japgolly.scalajs.react.vdom.ReactTagOf[TopNode]

// make all tags in HtmlTags.scala gain more specified types
implicit class STStringExt(private val s: String) extends AnyVal {
  def tag[N <: TopNode](implicit namespaceConfig: Namespace): ReactTagOf[N] = ...
  ...
}
```

**Comment by japgolly** [comment]
I didn't think of stuff like that (passing refs to children). I'm rather simple with my sparse ref usage.

Re your pedagogical/type argument: good point! That's quite convincing. That being said, let's leave things as they are for v0.10 and reconsider for v0.11.

**Comment by elacin** [comment]
Thats fine, there is already a lot of new goodied in 0.10

**Comment by japgolly** [comment]
Revisit as part of #259.

**Comment by japgolly** [comment]
Fixed on `topic/neo` branch.
