### ISSUE TITLE
CSSTransitionGroup timeout props

### ISSUE THREAD

**Issue by zv3** [japgolly/scalajs-react#198]
Was checking the React docs (https://facebook.github.io/react/docs/animation.html) on CSSTransitionGroup and wanted to play with the transitionEnterTimeout and transitionLeaveTimeout because somehow removed elements (from a collection in the state) are not removed from the DOM after re-rendering. This is on v0.10 and React 0.14

Thought that playing with the timeout values would fix this but seems we can only set transitionAppear/transitionLeave boolean props

**Comment by japgolly** [comment]
Ah right, sounds like we just need to add `transitionEnterTimeout` and `transitionLeaveTimeout` params and we should be sweet.

**Comment by zv3** [comment]
Excellent, I can open a PR if you like, I think I can do that :smiley:

**Comment by japgolly** [comment]
Sure! That would be helpful :smile:

**Comment by zv3** [comment]
Submitted PR #205 and tested the added props, all working :+1:

**Comment by japgolly** [comment]
Closed via #205
