### ISSUE TITLE
Support nested view?

### ISSUE THREAD

**Issue by nghuuphuoc** [japgolly/scalajs-react#200]
For now, we can use the same layout for all pages using the [renderWith()](https://github.com/japgolly/scalajs-react/blob/master/extra/ROUTER2.md#rendering-with-a-layout) method.
The same layout consists of common parts such as navbar, footer, etc.

In our app, there are a lot of pages which have the same view/set of components in addition to the same main layout. So, is it possible for us to use the nested views with ScalaJS react?

**Comment by japgolly** [comment]
I don't quite understand what you're proposing. The router is just a component and so is composable in the same way that any component is. The router doesn't need to be at the component tree root, and the routing rules needn't be globally static. It sounds like you could solve your problem by lowing the router in the hierarchy and/or passing in shared components when creating the routing rules. Do you think that would work?

**Comment by japgolly** [comment]
Please re-open if you have more info.
