### ISSUE TITLE
React warning due to implicit conversion from Seq[ReactNode] to ReactNode

### ISSUE THREAD

**Issue by ochrons** [japgolly/scalajs-react#206]
It's quite easy to make a mistake like 
```
def apply(props: Props, children: ReactNode*) = component(props, children)
```
when you really want
```
def apply(props: Props, children: ReactNode*) = component(props, children: _*)
```
The `children` (array) parameter is implicitly converted to a valid `ReactNode` but then React will complain about missing `key` props at runtime because the children are passed as an Array.

Similarly when building DOM from fragments, you can return a `Seq[ReactNode]` from a function whose return type is `ReactNode` and it will implicitly do the conversion, which will result in the `key` prop warning.

```
  private def buildTodoMenu(props: Props): ReactElement = {
    val todoCount = props.todos().count(!_.completed)
    Seq(
      <.span("Todo "),
      if (todoCount > 0) <.span(bss.labelOpt(CommonStyle.danger), bss.labelAsBadge, todoCount) else <.span()
    )
  }
```

Of course it's quite convenient to have this automatic conversion in normal DOM, but with React it might make sense to make the implicit conversion something that has to be explicitly imported.

**Comment by japgolly** [comment]
Will fix this on the neo (1.0) branch where all the vdom stuff is getting an overhaul.

**Comment by japgolly** [comment]
I'm thinking about making The New World work like this

* No more automatic/implicit conversion from `Array` or even `js.Array`.
* No more automatic/implicit conversion from `Seq`/`List`/`Traversable{,Once}` etc.
* Allow automatic/implicit conversion from `Option`.
* Add an extension method called `.toReactArray`, to `Array`, `Seq`, `TraverseOnce`, etc that allows a collection to be used as a React array (and thus require keys).

So from the example:
```scala
def apply(p: Props, c: ReactNode*) = {
  component(p, c) // Wont work anymore
  component(p, c: _*) // Works
  component(p, c.toReactArray) // Works
}
```

@ochrons What do you think of this solution? Any feedback, suggestions, changes I should make?

Also, any better name for `.toReactArray`?

**Comment by japgolly** [comment]
Fixed on `topic/neo` branch.
