### ISSUE TITLE
PERF.md still uses old callback/IO

### ISSUE THREAD

**Issue by ochrons** [japgolly/scalajs-react#207]
In https://github.com/japgolly/scalajs-react/blob/master/extra/PERF.md#example-1 the examples are still using old style Scalaz `IO` and `~~>` etc. instead of `Callback`

**Comment by ochrons** [comment]
Same in https://github.com/japgolly/scalajs-react/blob/master/extra/ROUTER.md#routerctl

**Comment by ochrons** [comment]
This new 0.14 feature might also be handy, "Added React.Children.toArray which takes a nested children object and returns a flat array with keys assigned to each child."

**Comment by japgolly** [comment]
Oh crap, I forgot to update all the doc in `extra/` for 0.10.0. Thanks.

**Comment by japgolly** [comment]
Painful. Closed via e5b46a130224d93baaa57e281a26196fff3d272f and f988eb52b05c1dfc0c46da3ec7e1cc99d5403596.
