### ISSUE TITLE
Online ScalaDoc To Browse APIs

### ISSUE THREAD

**Issue by jclyons** [japgolly/scalajs-react#209]
It would be great if all types and methods were documented with ScalaDoc and uploaded to a public location for easy browsing of documented APIs. It's sometimes hard to know what methods are available on a type without looking into the source code.

**Comment by elacin** [comment]
more documentation is always great, but scaladoc is pretty terrible to navigate and read. what kind of IDE doesn't show you that information inline in the editor these days?

**Comment by jclyons** [comment]
Most IDEs do, but not all programmers use an IDE. I use Sublime Text for most of my coding, and my terminal for running / testing. I find online documentation such as this http://www.scala-js.org/api/scalajs-dom/0.8/#package very useful. Whether it's accomplished through ScalaDoc or some other utility, it's nice to be able to read it in the browser.

**Comment by japgolly** [comment]
Cool, will do when there's time.

**Comment by japgolly** [comment]
I'm not gonna be able to triage this into my own schedule. A PR would be greatly appreciated though - I'll add a help_wanted tag.

**Comment by japgolly** [comment]
Seems we get this for free!
https://www.javadoc.io/doc/com.github.japgolly.scalajs-react/core_sjs0.6_2.11/0.11.1

**Comment by japgolly** [comment]
Fixed on master
