### ISSUE TITLE
Passing callbacks to JS components in 0.10

### ISSUE THREAD

**Issue by jclyons** [japgolly/scalajs-react#210]
Using 0.9.2, I was wrapping a JavaScript component called 'Button' and I was passing an 'onClick' handler as a partially applied function like so:

```
Button(onClick = $.backend.onToolSelect("dynamicFieldTool") _)
```
The callback looks like this:
```
    def onToolSelect(tool: String)(e: ReactEventH) : CallbackTo[Unit] = 
        $.modState(_.copy(activeTool = Some(tool)))
```

The case class wrapper for the component was like this:
```
case class Button(
    ref: js.UndefOr[String] = js.undefined,
    key: js.UndefOr[String] = js.undefined,
   onClick: js.UndefOr[(ReactEventH) => Callback] = js.undefined
) { [...]
```
This was working under 0.9.2  - modState was being called - but I upgraded to 0.10 and it broke.

How do you pass callbacks to JS components in 0.10?

**Comment by elacin** [comment]
Don't think it has been properly addressed yet. You need to transform the event handlers, something like this:  `onClick _ andThen (_.runNow())`

I wrote a macro to do it for `scalajs-react-components`:
https://github.com/elacin/scalajs-react-components/blob/scalajs-react-0.10/macros/src/main/scala/chandu0101/macros/tojs/JSMacro.scala#L52-L61

**Comment by jclyons** [comment]
Great - that did it. I'll check out that macro. Thanks!

**Comment by japgolly** [comment]
I don't use any of the pure-JS-component-wrapping stuff, it's all been kindly contributed. As I don't use it  myself, I wasn't too keen on spreading the `Callback` love to it off the bat. As `Callback` get comfortable I'd like to hear from users of this JS stuff as to whether or not to update it similarly. Please feel free to open an issue or PR in future to discuss this once opinions solidify.
