### ISSUE TITLE
Functions as Components

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalajs-react#214]
Hey,
          I added this feature to sri  recently https://github.com/chandu0101/sri/blob/master/docs/StatelessFunctionComponents.md ,so far i am really loving it . any specific reason for not adding in scalajs-react ? if there is no strong reason i can send a PR ;)

**Comment by japgolly** [comment]
It's already in; it was part of v0.10. See the CHANGELOG for details. Thanks for the PR offer though!

**Comment by chandu0101** [comment]
ah my bad sorry :(
