### ISSUE TITLE
Callback/Future integration

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#216]
Add conversions like:
```
    CallbackTo[Future[A]]

     ↓                 ↓

CallbackTo[A]  ← →  Future[A]

     ↑                 ↑

    Future[CallbackTo[A]]
```

**Comment by japgolly** [comment]
Would make #118 obsolete.

**Comment by elacin** [comment]
This seems to be in pretty high demand on gitter, at least an easy way to make results of ajax calls perform state updates. I'm not sure how to express the transformations above, but at least something like this would go a long way:
```scala
  implicit def toCallback(fcb: Future[Callback]): Callback =
    Callback(fcb.foreach(_.runNow()))
```
(not sure if it actually makes sense to make it implicit... perhaps)

**Comment by japgolly** [comment]
Ok thanks @elacin for letting me know! If the demand is high I can publish 0.10.1 very soon with just this in it.

This seemed easy and straight-forward and finished a draft (https://gist.github.com/japgolly/e511e05023474674c9a8).

Then I realised a serious problem...
I think `Future` → `Callback` should be illegal!

A `Future` means code has already begun execution and the result is pending. A `Callback` is code that *may* be run later in response to something. If a user reshapes and passes a `Future` to a DOM callback, it will run during `render` and do nothing when (if) the DOM event fires.

Even the `implicit def` you wrote above, although it seems fine, is wrong. It's similar to writing this:
```scala
implicit def toCallback(fcb: Future[Callback]): Callback = {
  fcb.foreach(_.runNow())
  Callback.empty
}
```
The request to server starts immediately. Only the use of that value (presumably a `setState`) is delayed until the callback is invoked.

I think the helpers should only apply to reduce a `CallbackTo[Future[?]]` down to a `Callback`. `Future` creation should happen inside a `Callback`.

I was thinking adding `def future(f: => Future[Callback]): Callback` to `Callback` but then it leads to confusion like:
```scala
def updateServer: Future[Unit] = ...

// Callback.future arg is by-name so no prob
val ok = Callback.future(updateServer)

// FAIL: updateServer begins immediately + callback is not repeatable.
val f = updateServer
val notOk = Callback.future(f)
```

Thoughts?

**Comment by japgolly** [comment]
Done. See changelog for details.
