### ISSUE TITLE
React.js 0.14.2 - no love for IE

### ISSUE THREAD

**Issue by ngbinh** [japgolly/scalajs-react#221]
http://facebook.github.io/react/blog/2015/11/02/react-v0.14.2.html

Seriously! But again, should be an easy update.

**Comment by japgolly** [comment]
Lol already? They waited for me to hit release on this project I think. Bet they're all in their little office laughing it up. Probably got this exact issue up on the office monitors auto-refreshing. :laughing: 

I'm a bit busy lately but scalajs-react can be used with React 0.14.2 as is without a problem. Only missing one new attribute.

**Comment by ngbinh** [comment]
> I'm a bit busy lately but scalajs-react can be used with React 0.14.2 as is without a problem. Only missing one new attribute.

Yes. No rush!

**Comment by japgolly** [comment]
Closed via 4e8bea2

**Comment by ngbinh** [comment]
Thanks! `0.10.2` soon?

**Comment by japgolly** [comment]
Very soon. I'll be using the SNAPSHOT in my main work today and through the weekend - if I don't discover anything I need missing, I'll publish 0.10.2 then.

**Comment by japgolly** [comment]
Which means FB is likely waiting to release React 0.14.4 as soon as I hit publish hehe
