### ISSUE TITLE
Each child in an array should have a unique key prop warning with custom component

### ISSUE THREAD

**Issue by nghuuphuoc** [japgolly/scalajs-react#222]
I have a custom component that allows to pass the children such as 

```scala
object MyComponent {
  private val COMPONENT_NAME = this.getClass.getSimpleName

  case class Props(...)

  private val component = ReactComponentB[Props](COMPONENT_NAME)
    .stateless
    .noBackend
    .render((P, C, _, _) => {
      <.div(C)
    })
    .build

  def apply(...)(children: ReactNode*): ReactComponentU[_, _, _, TopNode] = {
    component(Props(...), children)
  }
}
```

And it's used inside other component's `render` as following:

```scala
object Login {
  private val component = ReactComponentB[Props](COMPONENT_NAME)
    .initialState(...)
    .backend(...)
    .render((P, S, B) => {
      // Call my custom component
      MyComponent(props)(
          <.div(...)   // Here are the children
      )
    })
    .build

  def apply(...): ReactComponentU[_, _, _, TopNode] = {
    component(Props(...))
  }
}
```

Everything works fine, except the `Each child in an array should have a unique "key" prop` warning.

Adding a `^.key` attribute before passing the children will fix the warning

```scala
// Login component
MyComponent(props)(
    <.div(^.key := 0,
        <.div(...)   // Here are the children
    )
)
```

but I don't want to modify all of components in that way.
Is there better way to fix that, maybe just adjust `MyComponent`? I know that the library provides `component.set(key, ref)` and `component.withKey()` methods, but don't know how to use it.

**Comment by japgolly** [comment]
You could change `component(Props(...), children)` to `component(Props(...), children: _*)` - that way you won't need keys.

> I know that the library provides component.set(key, ref) and component.withKey() methods, but don't know how to use it.

Like this:
```scala
component.withKey("eg1")
// or
component.set(key = "eg1")
```

**Comment by nghuuphuoc** [comment]
> You could change component(Props(...), children) to component(Props(...), children: _*) - that way you won't need keys

That works. Thank you so much!
