### ISSUE TITLE
Integration to React-Redux

### ISSUE THREAD

**Issue by naksu** [japgolly/scalajs-react#223]
I've been trying to integrate with React-Redux (https://github.com/rackt/react-redux), so far with little luck.
I wrote a wrapper for the `Provider`, so that part should be fine.
```
case class Provider(store: js.Dynamic) {
  def toJs: js.Dynamic = {
    js.Dynamic.literal(store = store)
  }

  def apply(children : ReactNode*): ReactComponentU_ = {
    val factory = React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.global.ReactRedux.Provider)
    factory(toJs, children(0)).asInstanceOf[ReactComponentU_]
  }
}
```
Application's topmost component needs to be wrapped in a `Provider`, and connected to the store via `Redux.connect` function. `Redux.connect` expects a `Component`, as in the example from from http://rackt.org/redux/docs/basics/ExampleTodoList.html.
```
class App extends Component ...
var component = connect(select)(App)
```
`PSBR.build` method returns a factory function, instead of a `Component` class, so I cannot give it to `connect`. I tried creating a dummy react element from my scala component, and using its `type` property as a component. Unsurprisingly, it did not work. 

*What would be a correct way to get a Component from Scala-based component?*

My attempt below:

``` 
val store = ...
def select(state: js.Dynamic): js.Dynamic = {
  state
}
val connector = js.Dynamic.global.ReactRedux.connect(select: js.Dynamic => js.Dynamic)
val node = dom.document.getElementById("content")
val connected = connector(Hello.Component(null).asInstanceOf[js.Dynamic].`type`)
ReactDOM.render(Provider(store)(js.Dynamic.global.React.createElement(connected).asInstanceOf[ReactNode]), node)
```

**Comment by naksu** [comment]
With the above code, the `Hello` does appear. So perhaps the way of calling `connect` is sort of ok.

If I log `props` to console in the `Hello`'s `render` method, `props` are undefined. However, logging `this.asInstanceOf[js.Dynamic].selectDynamic("example$Hello$Backend$$scope$f").props` does print valid-looking props. 

So it seems that React-Redux does provide the `props` to the child object (`Hello`), but they don't quite make their way to the `render` method. Could it be that there is some plumbing needed in ScalaJS-React?

**Comment by japgolly** [comment]
Hello!

> What would be a correct way to get a Component from Scala-based component?

Sounds like you want one of these: https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/ReactComponentC.scala#L16-L24

> So it seems that React-Redux does provide the props to the child object (Hello), but they don't quite make their way to the render method. 

React JS requires all props and state to be `js.Objects` where as in Scala-land we want to be able to use any type. Therefore under-the-hood, all props and state are wrapped in `WrapObj` which changes a Scala `T` to a JS `{v: T}` to keep React happy. If you're expecting props to be fed you from a JS lib you'll likely have to factor that into your interop.

**Comment by naksu** [comment]
Thanks for your help!

With the reactClass, the construction is now more sane:
```
val connector = js.Dynamic.global.ReactRedux.connect(select)
val connectorComponent = connector(componentBuilder.reactClass)
js.Dynamic.global.React.createElement(connectorComponent).asInstanceOf[ReactNode]
```
I wrapped the top-level state inside a `{ v: state }`, and thus now the props are visible in the `render` method. (For anyone trying to do the same, I modified `mapStateToProps` to wrap its return value in a `{ v: ... }`. https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).

Am I correct in that this wrapping must be done whenever a standard React component has a child that is a ScalaJS-React component? For example `render = <StandardComponent v=${childProps}>...`. 

Is there a way to avoid the wrapping? This hack might not always be feasible.

**Comment by japgolly** [comment]
Glad to hear you've got things​ working.

Yes the hack is necessary for any React component for which the props/state
is a Scala type. React crashes if it encounters a props/state value that
isn't a js.Object so all Scala values need to be wrapped to keep the JS
happy.

**Comment by naksu** [comment]
It required some more hacking, since the connect method merges the `store.dispatch` method with the state before assigning the result to props. The code below merges the `v`'s.

```
val mapDispatchToProps = (dispatch: js.Object) => js.Dynamic.literal(dispatch = dispatch)
val connector =
  js.Dynamic.global.ReactRedux.connect(
    mapStateToProps andThen react.WrapObj,
    mapDispatchToProps andThen react.WrapObj,
    (stateProps: react.WrapObj[js.Object], dispatchProps: react.WrapObj[js.Object], ownProps: js.Object) => {
      react.WrapObj(js.Dynamic.global.Object.assign(js.Dynamic.literal(), stateProps.v, dispatchProps.v))
    })
```
