### ISSUE TITLE
Polymorphic Props and State confusing the macro 

### ISSUE THREAD

**Issue by zv3** [japgolly/scalajs-react#224]
Atm, if you have code like the following:

```
case class Props[A](...)

class Backend[A]($: BackendScope[Props[A], _]) {
  def render(P: Props[A]) = ...
}

def apply[A]() =
   ReactComponentB[Props[A]]("MyComponent")
    .renderBackend[Backend[A]]
    .build
```

You get the following error on compile

>  Don't know what to feed (P: z.x.y.Props[A]) in z.x.y.Backend[A].render.
>  .renderBackend[Backend[A]]

The workaround suggested by @japgolly on gitter chat:

> That might be a bug due to `Props[A]`'s polymorphism confusing the macro. You can avoid it even now by changing `render(P: Props[A])` to `render(p: Props[A])` or `render(props: Props[A])`.

The same also happens with `State[A]` and having a `def render(S: State[A])`

On a side note, I noticed that when i don't go with the usual `val component = ReactComponentB...build{U}` to build the component and instead have the apply() method return the `ReactComponentB` build like in the code above, whenever the parent component changes this component's props, the component is unmounted and remounted as opposed to just updating the props with a `WillReceiveProps` like it happens if you go with: 

```
val component = ReactComponentB[{Unit,Props}]..build{U}

def apply() = component()

```

**Comment by japgolly** [comment]
@zv3 I missed your side-note comment and just saw it.

Yes, if you use `def apply = ReactComponentB...` it's going to create new component every time - even if it looks the same, React has some internal mechanism that will realise they're different and so at runtime it will unmount and remove one, then mount and add the other.

I plan to facilitate this behaviour in #180

**Comment by torstenrudolf** [comment]
just leaving this here for completeness.
I hadn't seen this issue before.
http://stackoverflow.com/questions/43559344/how-to-use-type-parameterized-components-with-scalajs-react

**Comment by ngbinh** [comment]
is this still an issue?

**Comment by japgolly** [comment]
@torstenrudolf Very good idea! Thanks

@ngbinh Yeah you're right. This no longer makes sense. Closing!
