### ISSUE TITLE
Open up japgolly.scalajs.react.vdom.Builder

### ISSUE THREAD

**Issue by codingismy11to7** [japgolly/scalajs-react#240]
the `Builder` class is marked private[vdom]. I have a class that I'd like to give an implicit `StyleValue` in its companion object, but I can't due to `Builder`'s visibility

**Comment by elacin** [comment]
+1, I've hit this too

**Comment by codingismy11to7** [comment]
haha, yeah, it was for react sjs components, MuiColor, I wanted to provide a typeclass to just `.asInstanceOf[String]` on it to let me send it in. @japgolly i really like all the stuff you do, even though my coworkers and boss hate me for all the FPness of it, and all the privatizing and finalizing is great, but here's one spot where it'd be nice to let us define our own typeclasses

**Comment by japgolly** [comment]
> even though my coworkers and boss hate me for all the FPness of it
Hahaha! :laughing: 

Erm, opening it up worries me a little because it's a hack and then I have to consider backwards-compatibility for it. I want to open things up so you have control and freedom but I believe allowing subclassing of `Builder` isn't the way to do so.

What would you think about adding a feature for what you need (even if it's just a typeclass), that gives you full freedom but without needing to subclass an implementation class?

**Comment by elacin** [comment]
Things i have wanted to do:
* provide instances of `StyleValue` for new types, which we cannot do because `Builder` is hidden
* render `StylePair`s to `js.Object` so that we can use scalatags style attributes with js libraries that expect styles encoded as a js object.

**Comment by zlangbert** [comment]
+1

**Comment by japgolly** [comment]
@codingismy11to7 @oyvindberg FYI guys, I plan to get 0.11 released pretty soon. The change for this issue would be a breaking change so if you want to get a PR in, this week is your best chance because after 0.11 it'll be a few months until 0.12.

**Comment by japgolly** [comment]
Scratch that - I'm refactoring all of the scalatags stuff, making it cleaner and simpler. As such, it's now not going to be such red flags to extend the attr/style stuff have `Builder` exposed.

**Comment by japgolly** [comment]
Done.

**Comment by codingismy11to7** [comment]
ok cool, my notifications for this issue apparently have been lost since december, so glad to read. thanks
