### ISSUE TITLE
Support combining inline style with attribute-set styles

### ISSUE THREAD

**Issue by rpiaggio** [japgolly/scalajs-react#242]
When setting a tag's attributes, either of these work fine:

`^.style := js.Dictionary("background-color" -> "black").asInstanceOf[js.Object]`

or

`^.color := "red"`

However, when combined:

`^.color := "red", ^.style := js.Dictionary("background-color" -> "black").asInstanceOf[js.Object]`

the inline `style` doesn't get rendered in the presence of directly-set style attributes.

It would be nice if this worked. Maybe it is a Scalatags thing? Also, in case this worked, we should establish a precedence in case of conflict.

Thank you.

**Comment by japgolly** [comment]
Hi. Yes, I believe this is an implementation detail from when I forked Scalatags long ago. I'm open to having it fixed but:

1. It will need to be fixed by the community.
2. Maybe one day (far away) be replaced by direct ScalaCss support.

**Comment by japgolly** [comment]
Fixed on `topic/neo` branch.
Tests added in 0b9338753a48bb6538a6de28cb4c29d6b23c5fbe.
