### ISSUE TITLE
Make ReactComponentB generate ES6 classes?

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#246]
Supposedly, ES6 classes yield better performance.

1. Will it work in *all* browsers? ONCE AGAIN I've forgotten how ES6 works.
2. Can it be done at all, considering mixins and things like `Reusability.shouldComponentUpdate`?

**Comment by japgolly** [comment]
One day when someone shows me **proof** that this yields improvement, it can be reopened and reconsidered. At this point the disadvantages / limitations are well known but the advantages are anecdotal and rumours.

**Comment by simerplaha** [comment]
Hi @japgolly , I thought this change was needed if we wanted to use scalajs-react with react native ? I know react-native is not what scalajs-react is focused on but it will be great if we could use your awesome scalajs-react for react native apps as well. Or am I missing something here ?

**Comment by japgolly** [comment]
Hey @simerplaha. Ohhhhhh react native slipped my mind completely - I forgot about that. I don't know much about it to be honest - is ES6 required? I'm not sure. It would be good to have nice integration with react native from scalajs-react, I don't want to prevent that. The community or those who'll actually use it will need to build that bridge though.

This issue's a little different. This issue was to have `ReactComponentB` generate ES6 classes under the hood (so all you're existing code would be unchanged). There are still some open questions (see first post in this thread) that make me think it might not be possible.

Anyhoo, if it's needed for react native I'm cool to have this issue open but if it's just for anecdotal performance, I'd like to verify the claim before re-opening.

**Comment by simerplaha** [comment]
@japgolly My bad! ... Apparently ES6 classes are not required for react-native. I'm trying to see if somehow I can write react-native apps with scalajs-react with SRI and was under the impression that ES6 classes were required. Thanks for replying back David. Cheers!

**Comment by japgolly** [comment]
@simerplaha No worries. This isn't really the right issue for SRI integration but I can tell you that @xsistens was interested in working towards that and his first step was #217 which is stalled because, well, we all have more pressing responsibilities and little time unfortunately. But if you're interested in helping build that bridge I'd say have a look at that issue and maybe chat to @xsistens.

Otherwise, cool cool, I'll leave this particular ticket closed for now.
