### ISSUE TITLE
router blows up with UBE on "some" ie versions

### ISSUE THREAD

**Issue by easel** [japgolly/scalajs-react#249]
Root cause is referencing window.location.origin, which isn't well supported on IE.

I'm working on getting this fixed upstream, so this should get fixed automatically with an update to scala.js or scala-js.dom, but for now you can also work around it with the polyfill from  https://github.com/scala-js/scala-js-dom/issues/201

**Comment by easel** [comment]
I'll PR the fix above once the scala-js-dom change is merged, although we probably won't want to merge anything here until the updated scala-js-dom code is stable.

**Comment by easel** [comment]
I split out a couple of the commits from the branch below. Assuming the scala-js-dom pr is accepted as is, the last bit will be simply to bump the scala-js-dom dependency and replace the implementation of fromWindowOrigin with the .getOrElse implementation you can see in 
https://github.com/7thsense/scalajs-react/commit/b24205656e84aec367d1f64fc28635147cac4c73

**Comment by japgolly** [comment]
> the last bit will be simply to bump the scala-js-dom dependency and replace the implementation of fromWindowOrigin with the .getOrElse implementation

I don't think we should bother with `getOrElse`. If the compiled JS has to include the code to build it ourselves then we may as well just do it all the time. That'll shave a few bytes off output size :smiley:

**Comment by easel** [comment]
That's fine too, it's hard to imagine the original implementation doing something interesting or different.
