### ISSUE TITLE
Redo ALL the damn types

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#259]
The types in this have become a giant mess. They've evolved as much as they can without a major rewrite. So it's time for a major redesign of the types.
#### Problems
- Many types describe JS directly with ops added via implicits. Certain typically-simple functionality like mapping P, mapping S, CB vs direct, etc require so much annoying machinery (`CompState`) or just can't be done (`BackendScopeMP`).
- Similarly, React rules are encoded in types by conjunction. `A with B with C` which makes general abstraction and mapping in pain when possible and impossible other times.
- Organisation is terrible as it's either dump heaps in `package.scala` or add boilerplate everywhere like `MonocleReact` and `ScalazReact`. Yuk.
- `[P, S, B, N <: TopNode]` = pain in the ass.
- Too hard now to use types to prevent/allow `.props.children`.
#### Solution Ideas
- Just wrap all the bloody JS crap in Scala. One extra object instance per component (hopefully) isn't going to make a noticeable dent in performance.
- Would be great to have a single class for components' `this` and then have capabilities encoded as implicit permissions, phantom types, etc. The class could have _all_ possible ops all the time (like in JS) but the permissions could be required to _invoke_ them.
- Use existential types for backend and node type (and props children probably) with a few ∀ `Aux` helpers. Library provides in full. Gen code will mostly only specify `[P, S]`.

**Comment by ramnivas** [comment]
Wonderful! I was just thinking about this the other day. Indeed there are too many types (more so in 0.10.x with `ComponentDidUpdate` and its parents and siblings). Just so that I understand the direction you are thinking, is it going to be along the following lines?
```scala
def componentDidMount(implicit ev: Mounted[???)
def refs(...)(implicit ev: Mounted[???] )
```

**Comment by japgolly** [comment]
@ramnivas Yeah! That's one of the ideas I have. I don't know if it's the best solution yet or even how feasible it is but it would definitely be cleaner and clearer that what we have now :)

**Comment by japgolly** [comment]
For anyone interested, this is now online: https://github.com/japgolly/scalajs-react/tree/topic/neo

**Comment by japgolly** [comment]
Still a WIP. Only about 50% of the way through.

**Comment by PerWiklander** [comment]
Would "Just wrap all the bloody JS crap in Scala" make it easier to write a JVM side static renderer later?

**Comment by japgolly** [comment]
@PerWiklander I'm not sure how you'd go about doing that but, because Scala components now expose their underlying JS components and no longer use any hidden magic, rendering a Scala-based component on the JVM side, should be the same difficulty as rendering a pure JS component on the JVM side. It takes the Scala bit out of the equation but I'm still not sure how you'd do it (given the Scala.JS issues with Rhino & Nashhorn, and the sandboxing of PhantomJS & NodeJS) so my answer is a hesitant, ....yes?

**Comment by PerWiklander** [comment]
I was more thinking of if we will have an abstraction layer on top of the JS things it should be possible to have JVM side implementations and render using Scalatags. Any event handler or state callback would basically be a no-op. It's just an idea I'm toying with. Sure it breaks as soon as you start playing with js.Dynamic or mix it with plain JS react components. 

 /Per

**Comment by japgolly** [comment]
Ah, yeah that would be possible, but it would also be some decent work to implement. Probably not a huge amount though. I would imagine creating a new component type that performed differently on JS/JVM and maybe had some additional constraints. Much easier with the new redesign because there's an abstract component interface that lets you create as many different implementations of React components as you like, where as on the v0.x.y branch you'd be forced to start hacking around in `ReactComponentB` and it would be a big pain & mess.

**Comment by PerWiklander** [comment]
That sounds like a great opening at least :-)

 /Per

**Comment by mariussoutier** [comment]
Do you have a usage example?

**Comment by japgolly** [comment]
@mariussoutier Of the new (WIP) design? There are some links in the README here: https://github.com/japgolly/scalajs-react/tree/topic/neo

**Comment by mariussoutier** [comment]
Yes of the new design. The JS component one-liner looks good. Did the ReactComponentB change? I was wondering if it made sense to make building React components in Scala.js very similiar to ES6, along the lines of:

~~~scala
class MyComponent[Props, State] extends React.Component {
  override def initialState() = State(...)
  override def render() = <.div(...)
}
~~~

**Comment by japgolly** [comment]
`ReactComponentB` will be backwards-compatible with what we have now but it's still WIP.

You're free to experiment with a class-based approach. It comes with limitations which even Facebook haven't worked out yet (which is why they still recommend using `React.createClass`). What's nice about the new branch is that it allows different representations of components so if you got a class-based style working and you liked it, you'd be free to use it without removing support for anything else (like `ReactComponentB`).

**Comment by japgolly** [comment]
Oh and regarding extending `React.Component`, a consideration that will need to be made is that React requires props & state to be `js.Object | Null`. To make components accept any Scala value a little conversion is required around all props/state reading/writing. It's not so clear on master with its magic, but it's super-clear on the neo branch, ([example1](https://github.com/japgolly/scalajs-react/blob/4c3de21c3b3af4ebf9b5ecca6886d8ab2d212409/neo/src/main/scala/japgolly/scalajs/react/ScalaComponent.scala#L12-L13), [example2](https://github.com/japgolly/scalajs-react/blob/4c3de21c3b3af4ebf9b5ecca6886d8ab2d212409/neo/src/main/scala/japgolly/scalajs/react/ScalaComponent.scala#L54-L61)).

A feature allowing Scala components to extend `React.Component` would need to have similar conversions in place. It's an unavoidable consequence of mixing Scala.JS and React, not specific to this library.

**Comment by chandu0101** [comment]
> It comes with limitations which even Facebook haven't worked out yet (which is why they still recommend using React.createClass)

:o hmm nah ,  react team actually against React.createClass  

>createClass() API feels outdated,

>Eventually we should deprecate createClass, possibly move it into a separate package.

ES 6 Componenet problems are in JS land (binding , prop inits etc) , i don't think they exist in scala land.

that being said they still experimenting with other techniques.. , they may deprecate ES6  classes too but they don't go back to `React.createClass`

Ref : https://github.com/reactjs/core-notes/blob/master/2016-05/may-19.md#createclass-vs-es2015-classes

**Comment by japgolly** [comment]
I literally read a week ago that they are still recommending `React.createClass` publicly while trying out ES6 internally and hitting lots of problems. Frustratingly I can't find the link now which is extremely inconvenient.

Anyway, going off the information in the link that you posted, they have heaps of problems. All their notes are full of currently unresolved ES6 problems. At one point they say "eventually we should deprecate `createClass`" and in another (on the same page) they say "**If** we decided to deprecate `createClass` in the future".  They're loving playing around with ES6 but we aren't in danger here. If they eventually deprecate `createClass`, ok that's cool, by then they should have fixed most of the problems and should be more comfortable with it. In which case, we make an internal change here and users of `ReactComponentB` will be unaffected. Happy to do so if the benefit is demonstrable, or we just get forced to for API reasons.

But remember, we're not obligated to model things the same way in Scala-land.

It doesn't take a genius to look at theory and/or look at the history of the industry, even just to look at case studies and see that *functions compose better than classes*. Functions are simpler than classes. I don't know if `ReactComponentB` is the best way of doing things, it works well so far, but because it just mostly composes functions together it's superior to extending a class and that's provable because it can do everything a class can do, but not the other way around. You can't abstract over methods (in JS, not that reflection is a good idea). Practical example: if you extend a class and you want to add a feature to it that affects behaviour of multiple lifecycle callbacks, then if you extend if class you have to wire up all those calls manually and override methods yourself and if you forget something, well bad luck, you've got a bug. With `ReactComponentB` or something similar, it's just a single call and it's safe.

Facebook's reasons for jumping from JS objects to JS classes do not at all necessitate Scala devs jumping from functions to classes. In fact that's ridiculous. I'm saying this so that we all remember to view our Scala-land development from a Scala perspective and do what's best for our Scala code and runtimes (which includes performance and JS component interop). We shouldn't try to mimic JS-land decisions where the environment (lack of a type-system) is entirely different. For them they have understandable reasons to move away from objects. If we want to use Scala classes, that's cool, let's make it possible in the redesign, but remember that we're not moving *up* from JS objects, we're moving *down* from better representations.

**Comment by chandu0101** [comment]
>It doesn't take a genius to look at theory and/or look at the history of the industry, even just to look at case studies and see that functions compose better than classes

to clarify i am not debating on classes vs functions ;) , i am just saying that React.createClass is going to deprecated!

more food for thought : 

<img width="620" alt="screen shot 2016-06-23 at 11 23 58 am" src="https://cloud.githubusercontent.com/assets/2179670/16293183/5bb637d8-3935-11e6-881e-edc41254652b.png">
<img width="631" alt="screen shot 2016-06-23 at 11 25 53 am" src="https://cloud.githubusercontent.com/assets/2179670/16293184/609ba6fc-3935-11e6-9af0-537052e3c060.png">
<img width="629" alt="screen shot 2016-06-23 at 11 25 30 am" src="https://cloud.githubusercontent.com/assets/2179670/16293187/67ed87b8-3935-11e6-9d51-b956d8ee818f.png">

If i were you i wouldn't spend my time on redesign now(assuming future is going to be similar to React.createClass ) unless i want to give job security to library users  :)

**Comment by mariussoutier** [comment]
Ok got it. Let stay functional then (nice discussion btw).

The only other concern I have right now is compile time, on a mid-sized project compile speed really suffered. It's hard to debug, but my guess is there's too many implicits? On a smaller project everything is faster, but making changes in Scala.js code becomes a pain after a while.

**Comment by PerWiklander** [comment]
Yeah, I've been feeling this. My smallish libs are fast and nice to work on,
but a typical client app that has many interconnected parts gets really slow
to compile after a
while.![](https://link.nylas.com/open/c7xqaaso1fkmfktxnomi9veih/local-
f938436a-
fb7b?r=cmVwbHkrMDAwNWZiMzU0YmU0MWIyMzdjNmFjMDk3MjgzNWM3MmQwZmIyYmQ4MDAwYWQ2NGY5OTJjZjAwMDAwMDAxMTM4MzUzYmY5MmExNjljZTA4MmMzNmVjQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 23 2016, at 2:37 pm, Marius Soutier &lt;notifications@github.com&gt;
wrote:  

> Ok got it. Let stay functional then (nice discussion btw).

>

> The only other concern I have right now is compile time, on a mid-sized
project compile speed really suffered. It's hard to debug, but my guess is
there's too many implicits? On a smaller project everything is faster, but
making changes in Scala.js code becomes a pain after a while.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/japgolly/scalajs-
react/issues/259#issuecomment-227973124&r=cmVwbHkrMDAwNWZiMzU0YmU0MWIyMzdjNmFjMDk3MjgzNWM3MmQwZmIyYmQ4MDAwYWQ2NGY5OTJjZjAwMDAwMDAxMTM4MzUzYmY5MmExNjljZTA4MmMzNmVjQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAX7NWxUuEZuG90JhZxjuAvZlo622RBdks5qOje_gaJpZM4Hk_xV&r=cmVwbHkrMDAwNWZiMzU0YmU0MWIyMzdjNmFjMDk3MjgzNWM3MmQwZmIyYmQ4MDAwYWQ2NGY5OTJjZjAwMDAwMDAxMTM4MzUzYmY5MmExNjljZTA4MmMzNmVjQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AAX7NW84Y1jtcod79bOoXAiHN5n6kEZ9ks5qOje_gaJpZM4Hk_xV.gif)

**Comment by japgolly** [comment]
Sorry for the delay; it's been a busy few days.

> to clarify i am not debating on classes vs functions ;) , i am just saying that React.createClass is going to be deprecated!

@chandu0101 No worries, I hear you. I know there's been a lot of talk about it happening but even in their own meeting notes you can see that there's uncertainty. Whatever they decide to do, we can handle here in the library. What I like about `ReactComponentB` is that the use of `React.createClass` is under-the-hood and completely opaque. We can change it whenever we want/need to without breaking users' code. An idea I had a few weeks back is that we can target the same representation that Babel uses to backport ES6 code to ES5. It looked pretty simple a few weeks ago. But first I'd really want to see some benchmarks before making that choice and I haven't had time to really investigate that.

> The only other concern I have right now is compile time, on a mid-sized project compile speed really suffered. It's hard to debug, but my guess is there's too many implicits? On a smaller project everything is faster, but making changes in Scala.js code becomes a pain after a while.

I use this lib in a very large project and the compile-time isn't the best but I'm not sure where the blame lies. I think it's just Scala being Scala, with Dotty being our Glorious Prophet foretold to one day arise from experimental status and save all us Scala users who keep faith. I doubt the implicits in this lib are doing anything to slow down compilation, there's no recursive implicit resolution or Shapeless-like or anything like that.

**Comment by mariussoutier** [comment]
I think it's more than Scala-slow, 8-12 seconds per compile is a lot. Maybe Scala.js is really slow right now, not scalajs-react. I haven't tried any other Scala.js framework yet.

**Comment by japgolly** [comment]
I lump Scala.JS slow in with Scala slow and I suspect it's all the same. That being said, happy to be shown wrong! If you find anything quantifiable please open an issue and we'll see what we can do. There was a compiler plugin released recently that you could use to give you a breakdown of your compilation time but I haven't been able to find it. If you find that tool, that might quickly yield some answers.

**Comment by mariussoutier** [comment]
On every compile (i.e. Play reload), Scala.js generates the whole fastopt.js, no? I guess that's even slower than just generating the classfiles that have changed.

**Comment by mariussoutier** [comment]
Will look out for that tool, might help diagnosing this...

**Comment by ngbinh** [comment]
@mariussoutier `fastOptJs` can also be incremental so a small change to your frontend should end up with a quite short `fastOptJs` (in the tens of seconds if the change is small)

**Comment by mariussoutier** [comment]
@ngbinh Right now minimal changes (like changing a String value) take 8 seconds when the JVM is warmed up.

**Comment by rators** [comment]
Creating a React.Component class that can be extended does create some restrictions that may not be as fun as a functional approach. It will however make it easier to convince ES6 tsx developers to consider Scala.JS if they already know Scala.

**Comment by japgolly** [comment]
Fixed on `topic/neo` branch.

(Extending an ES6 class was mentioned here but is tracked by #87.)

**Comment by BardurArantsson** [comment]
Does this mean that topic/neo is nearing merge/completion, or is there still a long way to go?

**Comment by japgolly** [comment]
@BardurArantsson it's getting close to completion. I expect that this time next month it'll all be done.

**Comment by ikamthania** [comment]
Can a snapshot version be available anytime sooner than that? Can't wait to see what is coming up.

**Comment by japgolly** [comment]
@ikamthania I can do you one better: progress is going well so I expect to publish RC1 later this week. :)

**Comment by japgolly** [comment]
@ikamthania An update: I was hoping to get an RC out last week but 1) there were more changes still to be make that I thought, and 2) being a new parent is significantly eating into my dev time :(

An RC will be out sometime within the next 7 days.
