### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#260]
Getting closer...

https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html

**Comment by japgolly** [comment]
WIP on https://github.com/japgolly/scalajs-react/tree/topic/react15

Tested under PhantomJS, Firefox,. Chrome.
All good except:
* `AddonTest.perf` no longer works under PhantomJS. (#https://github.com/ariya/phantomjs/issues/13652)
* `AddonTest.cloneWithProps` is currently failing.

**Comment by ngbinh** [comment]
Landed https://facebook.github.io/react/blog/2016/04/07/react-v15.html

**Comment by japgolly** [comment]
Pfft, React 15.0.0 is soooo 7th-of-April. I'm a 15.0.1 kind of guy.

https://facebook.github.io/react/blog/2016/04/08/react-v15.0.1.html

**Comment by ngbinh** [comment]
lol! as usual! 👍
