### ISSUE TITLE
React Router - navigate from outside of component

### ISSUE THREAD

**Issue by nlhkh** [japgolly/scalajs-react#261]
Is it possible to control navigation from outside of a React Component?

Currently the only method of getting a reference to a `RouterCtl` is by rendering a `Component` with `renderR` or `dynRenderR`.

What I think would be cool to have is, for the case if I use `autowire` and `Ajax`, I can have an interceptor that will redirect the router to a Login page whenever a `401` occurs.

In ReactJS in plain Javascript, this is possible in 2 ways:
- Store router state in Redux store: effectively a router state is just an application state, and placing the router state in a store allows you to control the router by dispatching actions.
- Pass reference of router: in `react-router`, a history object can be passed around to control the router.

**Comment by japgolly** [comment]
> Is it possible to control navigation from outside of a React Component?

Yes but you'll need to look at the situation slightly differently. If the router isn't mounted, then it won't be listening for URL changes and the routed page won't be rendered. For the router to react to URL changes, the router needs to be active (mounted) and so, if it's mounted, then there will exist a `RouterCtl`. When the router mounts, you simply pass the `RouterCtl` to whatever logic needs it, (so usually start something up, or connect to something). To not do, would mean you're ignoring a genuine dependency in your app's logic.

Alternatively, you can just use the HTML5 history api, use push-state, and set the URL directly. If the router is mounted, it will react. It most situations this would be considered a hack though; `RouterCtl` gives you URL safety which you would lose by bypassing it.

**Comment by nlhkh** [comment]
I see your point. I will try out your suggestion.

**Comment by japgolly** [comment]
This is answered right? Closing question.

**Comment by nlhkh** [comment]
Yes. Thanks David!
