### ISSUE TITLE
What's the proper way to initial state by props?

### ISSUE THREAD

**Issue by wenLiangcan** [japgolly/scalajs-react#265]
Thank you for writing this awesome library, I have a few questions while learning how to use it:

The first one is, in `jsx` we can do this:
```jsx
 class MyComponent extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
                data: this.props.data
            };
        }
}
```

The solution I used currently to achieve this goal in `Scala.js` is like this:
```scala
val MyComponent = ReactComponentB[Int]("MyComponent")
        .initialState(State(0))
        .renderBackend[Backend]
        .componentDidMount($ => $.modState(_.copy(data = $.props)))
        .build
```

But this is not initialization actually. Can I write state initial code inside the `Backend` class?       

Another question is what's the usage of the method `getInitialState()` provided by `scalajs-react`?       

In `react.js` we would provide an implementation for this method, but seems it is not going to be implemented or overridden in `scalajs-react`.

**Comment by ramnivas** [comment]
@wenLiangcan You can use `initialState_P` to initialize the state based on props. Like so:
```
.intiialState_P(props => State(prop.data))
```

**Comment by wenLiangcan** [comment]
Thank you ! @ramnivas

**Comment by japgolly** [comment]
@wenLiangcan Also FYI, there are a number of other similar methods if you need it in a different shape: https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/ReactComponentB.scala#L104-L112

**Comment by wenLiangcan** [comment]
@japgolly Thanks a lot, that's very helpful!
