### ISSUE TITLE
Create Callback.{when,unless}

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#266]
Both in object (replacing `ifTrue`) and in instance (replacing `conditionally`).
Then do it in `CallbackOption` too (if needed).

**Comment by ramnivas** [comment]
+1 `ifTrue` reads weird. `when` will be a nicer substitute and `unless` offers a natural counter conditional.

Are you considering these methods on object or instance of both? If offered for the instance form, it may look more like Ruby's `if`/`unless` that comes after an expression (https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Control_Structures).

**Comment by japgolly** [comment]
Yeah I was actually coding in Haskell over the easter break and `hlint` (Haskell lint tool) pointed out the existence of `when`/`unless` to me. 

Putting it on both means nicer syntax (like Ruby) but it's also inefficient in that your app will first build-up a callback then check if it's needed and, if not, throw it away. It's a nearly always going to be a minuscule inefficiency so the nicer syntax is probably worth it. Maybe more laziness is the better answer if I find anything that looks affected (I haven't looked).

**Comment by japgolly** [comment]
Closed via e0563b2a42d3ff14ed10404840f2e9f89b20d407 and 51a923b7e4ed3d6f6e7d5a35bd26fcc597e11a99.
