### ISSUE TITLE
Router not reacting on hash changes in Internet Explorer.

### ISSUE THREAD

**Issue by mblund** [japgolly/scalajs-react#267]
I have a problem with the hash based routing together with IE, when the user change manually change the url in the address bar. I'm using the router in scalajs-react 0.10.3 and scalajs 0.6.7

To easy reproduce the error, go to 
https://japgolly.github.io/scalajs-react/#examples/timer
with Internet explorer (11). The timer page is shown.

Now manually change the end of the url from /timer to /todo  and press enter. The todo page is now not shown as expected. Hit refresh and the todo page will be loaded.

This only occurs in IE (11) and not in Chrome or Firefox.

I was able to do a quick workaround, but this is probably not the most idiomatic way to solve it. 

``` scala
val (router,routerLogic) = Router.componentAndLogic(baseUrl,routerConfig)
window.addEventListener("hashchange", { (event: dom.Event) =>
  routerLogic.syncToWindowUrl.map(resolution=> routerLogic.ctl.refresh).flatten.runNow()
  event.preventDefault()
}, false)
```

Is this a know bug/feature?
Is there a better way to fix this?

**Comment by japgolly** [comment]
Thanks for reporting this and for suggesting the fix. To answer your two questions, I have no idea! I don't have web stuff in my brain lately. I'd have to do some reading up on using `hashchange` *and* `popstate` together, and confirm it works in Chrome & Firefox (I don't use Windows so no IE for me.) Now that we have Selenium support, testing this in the unit tests would be even better.

**Comment by mblund** [comment]
Maybe Backbone.History in http://backbonejs.org/backbone.js could give some easy to grasp inspiration

> Handles cross-browser history management, based on either [pushState (http://diveintohtml5.info/history.html) and real URLs, or [onhashchange](https://developer.mozilla.org/en-US/docs/DOM/window.onhashchange) and URL fragments. If the browser supports neither (old IE, natch), falls back to polling."

**Comment by nghuuphuoc** [comment]
Maybe related to this issue.

On IE 11, using `<.a(^.href = routerCtrl.urlFor(Page).value)` generates the correct link for `a` element, but clicking on that will NOT bring us to associate page (Although it works on Chrome and Firefox).

To fix that, we use `<.a(^.href = routerCtrl.link(Page)`. This works on Chrome/Firefox/IE 11.
