### ISSUE TITLE
Compile documentation with tut

### ISSUE THREAD

**Issue by OlivierBlanvillain** [japgolly/scalajs-react#286]
I would be happy to contribute a PR to compile the documentation with [tut](https://github.com/tpolecat/tut), WDYT?

**Comment by japgolly** [comment]
Hey @OlivierBlanvillain, I think that would be incredibly useful. :+1:

If you like, you can just do a smidgen first and I'd be happy to review before you go to far.

**Comment by OlivierBlanvillain** [comment]
Well, that didn't went really far: https://github.com/japgolly/scalajs-react/commit/0b6f14a837af3d861384e8318464b0ac5bc04404 :confused:

**Comment by japgolly** [comment]
Lol :boom: that was quick :D

Btw I noticed that if we change the Scala snippet directives to `tut` and keep the files in `doc` the directory, then it loses syntax highlighting on GitHub which isn't good. I think it'll be a good idea to rename the `doc` dir to `doc-gen`, `doc-src`, `doc-tut` or something similar, then have tut spew its glorious output into the `doc`. Most Scala snippet blocks will likely need `tut:silent` cos in most cases we wouldn't want the REPL output.

**Comment by japgolly** [comment]
I'm going to close this until tut supports Scala.JS.
