### ISSUE TITLE
Make vdom's := type-safe

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#291]
```scala
<.div(^.style := "height:20rem"), ...)
```
at least with `ReactDOMServer.renderToStaticMarkup` throws exception:
```
Invariant Violation: The `style` prop expects a mapping from style properties to values, not a
string. For example, style={{marginRight: spacing + 'em'}} when using JSX. This DOM node was
rendered by `Loading`.
```

where as it works like mummy's little angel if changed to:
```scala
<.div(^.style := js.Dynamic.literal("height" -> "20rem").asInstanceOf[js.Object], ...)
```

Extremely annoying. Now we need what? A typed js.Object builder? Sigh.

**Comment by ngbinh** [comment]
does something like https://github.com/jducoeur/jsext/blob/master/src/main/scala/org/querki/jsext/JSOptionBuilder.scala work? Not sure if you want to pull in external dependency or just build a small internal `js.Object` builder yourself though.

**Comment by japgolly** [comment]
Thanks @ngbinh but no, I just forget how to use my own library. :confused:

We can just use `^.height := "20rem"` without using `^.style` directly and it does the right thing.

The problem is that `:=` is untyped. It would be nice to type it. Our fork has already diverged far from Scalatags so we may as well.

**Comment by japgolly** [comment]
Fixed on `topic/neo` branch.
