### ISSUE TITLE
Add support for / update examples to show handling of external, custom Events

### ISSUE THREAD

**Issue by nacmacfeegle** [japgolly/scalajs-react#294]
Not sure if this is a bug or a suggested improvement, but I'll add it here for tracking purposes.

The code on the [examples page](https://japgolly.github.io/scalajs-react/#examples/event-listener) shows an `EventListener` that can respond to browser events that originate *outside* of the component. 

It would be nice if the scalals-react framework would also support non-standard, custom events in the same way, e.g:

```
val Main = ReactComponentB[Unit]("Custom EventListener Example")
  .initialState("Wouldn't it be great to see custom events here?")
  .renderBackend[Backend]
  .configure(
    // Listen for custom events
      EventListener[Event].install("customEvent", _.backend.logCustomEvent, _ => dom.window)
  )
  .build

  class Backend($: BackendScope[Unit, String]) extends OnUnmount {
    def logEvent(desc: String)       = $.modState(_ + "\n" + desc)
    def logCustomEvent(e: Event)     = logEvent("Custom event fired.")

    def render(state: String) =
      <.pre(
        ^.border  := "solid 1px black",
        ^.width   := "90ex",
        ^.height  := "20em",
        ^.padding := "2px 6px",
        state)
```

So, if a custom event is generated (possibly even by another framework), the component can still react to it:

```
$("button#trigger").click(function() {
  $(window).trigger("customEvent");
  console.log("event generated");
 });
```

As things stand, the above does not change the text in the component when the external custom event is fired; however, as the [examples page](https://japgolly.github.io/scalajs-react/#examples/event-listener) shows, external click events can be trapped and acted upon.

**Comment by japgolly** [comment]
I would've thought your snippet would Just Work. Do you know why it does? Are you sure it's not a jquery problem or jquery-compatibility problem?

**Comment by nacmacfeegle** [comment]
@japgolly not ruling out jQuery compatibility (problems or even [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK)).. However, I tried firing the event from another scalajs-react component that imports `org.scalajs.jquery.jQuery` (as opposed to using something included externally) and experienced the same issue. 

For now, I'm working around it by using `jQuery.on` inside a `start` method in the backend, and it seems to be able to pick the events up okay.

**Comment by japgolly** [comment]
The way `EventListener` works is just to attach and remove listeners from DOM like this:
https://github.com/japgolly/scalajs-react/blob/master/extra/src/main/scala/japgolly/scalajs/react/extra/EventListener.scala#L38-L39

AFAIK that's the normal way you listen to DOM events. If the events you're posting aren't being detected by `EventListener` I suspect that any other DOM listening JS would miss them too. It's probably this `wontfix` from https://bugs.jquery.com/ticket/11047.

**Comment by nacmacfeegle** [comment]
Confirmed that this is a jQuery issue -- many thanks or pointing out the bug. If I jQuery out of the picture and generate events this way, everything works:

```
  var customEvent = document.createEvent('Event');
  customEvent.initEvent('customEvent', true, true);
  document.dispatchEvent(customEvent);
```
Thanks again.

**Comment by japgolly** [comment]
No worries mate. Happy to hear you got it working.
