### ISSUE TITLE
Absorb Scalatags performance PR

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#295]
Might be beneficial to our fork:

https://github.com/lihaoyi/scalatags/pull/126

**Comment by oswaldo** [comment]
Hello, as you mention scalatags here, have you ever considered integrating/extending it?

I haven't looked in much depth into both source codes yet to say if that would be even possible, but I imagine that it could work pretty well also in the point of view that people already trying scalatags could transparently add scalajs-react to start experimenting while scalajs-react would consequently benefit from every improvement done in scalatags.

I even started a template project [here](https://github.com/oswaldo/react-scalajs-scalatags) so I can start exploring this idea if I find the time to do so.

Cheers,
Oswaldo

**Comment by japgolly** [comment]
Hi @oswaldo. This library originally did extend it back in the day, but it was too hard to adjust it to scalajs-react's needs, and so it was forked. In the next version of this library, it will again go through more  change.

**Comment by japgolly** [comment]
Reviewed. Nothing is applicable to scalajs-react.
