### ISSUE TITLE
Question: How to make HOC (high order component)

### ISSUE THREAD

**Issue by nghuuphuoc** [japgolly/scalajs-react#298]
How I can adopt the following things from ES6 to ScalaJS
```javascript
// This function passes a default props to given component
// Returns new component
const defaultProps = (props, BaseComponent) => (
  class extends React.Component {
    static displayName = 'defaultProps${BaseComponent.displayName}'

    render() {
      return <BaseComponent {...props} {...this.props} />
    }
  }
)
```

**Comment by japgolly** [comment]
It's just a function like `(P,B) => C`. You can do the same in Scala with a function of the same shape.

**Comment by nghuuphuoc** [comment]
The problem to me is that I don't know how to make this kind of `<BaseComponent {...props} {...this.props} />` in ScalaJS. Can you help me?

**Comment by japgolly** [comment]
Sorry; for this kind of question please ask in the gitter.im chat room.

I'd say: If you look at Scala's capabilities and think about what you want for your larger context you'll work it out :) But really, check out the chat room. There's a very helpful and knowledge bunch of really cool, smart people there and I'm sure they'll be happy to provide more detail.
