### ISSUE TITLE
Support onClickCapture and friends

### ISSUE THREAD

**Issue by jtcwang** [japgolly/scalajs-react#299]
From the react docs:

> The event handlers below are triggered by an event in the bubbling phase. To register an event handler for the capture phase, append Capture to the event name; for example, instead of using onClick, you would use **onClickCapture** to handle the click event in the capture phase.

Should we add support for this as well? I think we can just add the relevant code in `HtmlAttrs.scala` - Do you see any problems with this?

**Comment by japgolly** [comment]
What exactly is the distinction? Is capture/bubbling like saying will-fire/has-fired?

What is your use case for which you need this? (Not for PR purposes, I'd just like to learn and understand.)

Adding that to `HtmlAttrs` sounds fine.

**Comment by jtcwang** [comment]
Here's a good explanation: http://stackoverflow.com/questions/4616694/what-is-event-bubbling-and-capturing

So `onClickCapture` that's bound on a container element will allows you to handle events in the container before  the inner elements receives the event. This is useful in many cases when you want to stop propagation of the event to inner elements if some logic determines that you don't want the inner element to see the event at all.

**Comment by jtcwang** [comment]
So I looked at the React source code and here is the full list, as salvaged from

**Comment by japgolly** [comment]
Sorry I left this hanging for the last 2 weeks. Life be very busy these days.

Yes, I'd be happy for you to add those events. You have two options (or you can do both) - I don't mind.

1) Add it to `master` and I'll do a release that will be the last non-bugfix release for v0.x.y

2) Add it to `topic/neo` branch in [this file](https://github.com/japgolly/scalajs-react/blob/topic/neo/neo/src/main/scala/japgolly/scalajs/react/vdom/HtmlAttrs.scala). If you do this, all the fields are in alphabetical order so please follow suit.

**Comment by jtcwang** [comment]
I'm not in dire need of this. I'll add it to `topic/neo` branch

**Comment by jtcwang** [comment]
Since this is merged into `topic/neo`. I think we can close this.

**Comment by japgolly** [comment]
No worries. If you didn't see, I dropped a msg in gitter to say that unfortunately I've had to postpoone work on neo. I'll pick it again in January.

**Comment by jtcwang** [comment]
Yeap I saw that. Do appreciate the efforts you put into this project regardless!
