### ISSUE TITLE
Support @JSExport for Components to be used in legacy codebases

### ISSUE THREAD

**Issue by DomBlack** [japgolly/scalajs-react#300]
I'm trying to introduce Scala.JS to an existing code base and would like to start doing all new React development in Scala.JS, however at the moment it doesn't appear to be possible to `@JSExport` the component for inclusion in the legacy React.
### Example Scala.JS React Component

``` scala
package com.example.ui

import japgolly.scalajs.react._
import japgolly.scalajs.react.vdom.prefix_<^._
import org.scalajs.dom.html

import scala.scalajs.js.annotation.JSExport

@JSExport
object TestComponent {
  case class Props(name: String)

  case class State(count: Int)

  class Backend($: BackendScope[Props, State]) {
    def clicked(): Callback = $.modState(s ⇒ s.copy(s.count + 1))

    def render(P: Props, S: State): ReactTagOf[html.Element] =
      <.div(
        ^.className := "test-component",
        ^.onClick --> clicked,
        <.span(
          "Hello " + P.name + " (" + S.count + ")"
        )
      )
  }

  private val component =
    ReactComponentB[Props]("TestComponent")
      .initialState(State(0))
      .renderBackend[Backend]
      .build

  def apply(P: Props): ReactElement = component(P)
}
```
### Legacy Use in pure JSX;

``` jsx
<div>
   <com.example.ui.TextComponent name="World" />
</div>
```

**Comment by japgolly** [comment]
This ability isn't in place at the moment but if you'd like to add it, I don't think it'd be a huge amount of work. If you're willing to give it a shot but aren't sure how I'm happy to provide suggestions and guidance to help.

**Comment by japgolly** [comment]
I believe we do now have the ability to use components created by scalajs-react, in JS.
See [Interoperability doc](https://github.com/japgolly/scalajs-react/blob/master/doc/INTEROP.md).
