### ISSUE TITLE
Statefull sub-component example

### ISSUE THREAD

**Issue by joss75321** [japgolly/scalajs-react#301]
After going through documentation and examples, I was stumped over how to build react components in scala that included a Backend and could be used conveniently by parent components as none of the sub-components included Backends. https://github.com/tastejs/todomvc/tree/master/examples/scalajs-react provided a good mechanism but that example is a little bit much, it might be better to have a shorter example like the one below included in your examples.

``` scala
  object Counter {

    case class Props(name: String, inc: () => Callback)
    case class State(count: Int)

    class Backend($:  BackendScope[Props, State]) {

      def increment():Callback = $.modState(s => State(s.count+1))
      }

      def render(P: Props, S:State): ReactElement = {
        <.div(
          ^.input(
            ^.`type` := "button",
            ^.value := "+",
            ^.onClick --> { P.inc().runNow() ; increment() }
          ),
          s" ${P.name}: ${S.count}"
        )
      }
    }

    val component = ReactComponentB[Props]("Counter")
      .initialState_P(p => State(0))
      .renderBackend[Backend]
      .build

    def apply( s:String, inc: () => Callback): ReactElement = component(Props(s,inc))
  }

  object TotalCounters {

    case class Props(title: String)
    case class State(total: Int)

    class Backend($:  BackendScope[Props, State]) {
      
      def incTotal() = $.modState(s => State(s.total+1))

      def render(P: Props, S:State): ReactElement = {
        <.div(
          <.h1(P.title),
          Counter("John",incTotal),
          Counter("Fred",incTotal),
          Counter("Jack",incTotal),
          <.input(
            ^.`type` := "button",
            ^.value := "Reset total",
            ^.onClick --> $.setState(State(0))
          ),
          s" Total: ${S.total}"
        )
      }
    }

    val component = ReactComponentB[Props]("Counters")
      .initialState_P(p => State(0))
      .renderBackend[Backend]
      .build

    def apply( title: String ): ReactElement = component(Props(title))
  }
```

So, if you are interested in a PR I can create one, but if you have no interest in adding that then there's no point me creating the PR. If you would be interested in a PR, then I probably need to fix some things in this example than I am doing wrong and instruction would be welcome.

If the neo branch was going to be ready fairly soon then it might not be worth your time.

**Comment by japgolly** [comment]
Sorry I'm not quite sure what you mean. Using components within other components already works regardless of whether either component has a backend. Maybe I misunderstand you?

Btw there are some big problems in your code: :scream: 
* `{ P.inc().runNow() ; increment() }` may run the callback immediately. You shouldn't call `.runNow()`. Instead change it to `P.inc >> increment`.
* Also `Callback`s are not like `Future`s. They are re-runnable tasks so don't prefix them with `() =>`. So it should be `case class Props(name: String, inc: Callback)`

Also you can use `<.input.button` to

**Comment by joss75321** [comment]
Thanks for the code tips, I did try using >> before but it didnt work, I
must have done something else wrong, will revisit. I had a nasty brain fart
about the inner components. Initially when I tried using it, I found the
number of classes required to deal with a backend - Props/State/Backend
plus the ReactComponent val was causing confusion. One would have to either
contain each set in it's own object or have BackendForThisComponent,
BackendForThatComponent which gets ugly. I ended up tending to use as few
Backends as possible and passing the parent backends to inner components
for the callbacks with additional arguments as tuples like in your examples
but I forgot I was just being lazy and thought I was doing it out of
necessity. When I switched to keeping each set in it's own object and then
using apply to hide the unnecessary-for-outsiders Props object it helped me
a lot as there was a lot less mental effort involved in making components
with their own methods and avoiding inter-dependence using that pattern.

**Comment by japgolly** [comment]
That's awesome. It sounds like you're on the right path.

The way I do things is to put state/props/backend all in one object and then that object is the virtual component. If I can avoid backends (eg. small components) I absolutely do. Simple is awesome.

Reegarding component composition, I never ever ever pass a backend around. If you do so, the components are very highly-coupled. I, instead, declare all child component needs in the child's props 1-by-1 which might make you think at first that you have to pass 50 `Callback` instances around but I find that in practice most callbacks should be consolidated in the parent and that from the child's point-of-view, there are only a small amount - usually <4 - that it really cares about.

**Comment by japgolly** [comment]
You remind me that I was going to publish usage guidelines ages ago but forgot. I even wrote up a heap of stuff. Even better though would be something collaborative where community can contribute patterns/suggestions and multiple people suggest pros/cons, highlight trade-offs etc. That'd be cool.

**Comment by japgolly** [comment]
While I still haven't gotten around to publishing general usage guidelines and gotchas, I have done so for `Callback` recently seeing as it caused some confusion.
Anyway this is resolved so closing.
