### ISSUE TITLE
render() method not called after calling $.setState() or $.modState()

### ISSUE THREAD

**Issue by MikaelMayer** [japgolly/scalajs-react#306]
Dear developers,
I have a hard time to figure out how react works, and even more scalajs. The learning curve is hard, but I keep trying.
After spending six hours on the following problem, I give up and leave it to you.
I want to create a component, and update its state from the outside, through websockets.

Here is what I tried (two strategies in once, neither of which actually work)

```scala
object CustomTable {
  import japgolly.scalajs.react._
  import japgolly.scalajs.react.vdom.prefix_<^._
  type Props = (String => Unit) => Unit
  type State = String
  
  class Backend($: BackendScope[Props, State]) {
    def changeState(data: State) = {
      console.log("Changing state")
      $.setState(data)
    }
    
    def render(data: State, p: Props) = {
      console.log("Rendering element")
      p((data: String) => $.modState(s => data))
     <.div("Hello" + data)
  }
  val component = ReactComponentB[Props]("CustomTable")
    .initialState("world")
    .renderBackend[Backend]
    .build
  def apply() = component(_update = _)
  
  private var _update = (s: String) => ()
  def update(s: String) = _update(s)
}
```

And here this is how it is used in the code:

```scala
object Main extends js.App {
  lazy val mountedCustomTable = {
    val panelCustomTable = $("#containercustomtable")
    def get(): Option[ReactComponentM[(String⇒ Unit) ⇒ Unit,String,CustomTable.Backend,dom.raw.Element]] = {
      if (panelCustomTable =!= null) {
        panelCustomTable .map((i: Int, elem: dom.Element) => {
          return Some(ReactDOM.render(CustomTable(), elem))è 
          ().asInstanceOf[js.Any]
        })
      }
      return None
    }
    get()
  }

  def updateTable(data: String): Unit = {
    console.log("Setting data content", data)
    CustomTable.update(data) // First version: Does not work.
    mountedCustomTable.foreach{ // Second version: Does not work
      m => m.backend.changeState(data)
    }
```

as you see, there are two ways I thought I might try to modify the state.
The first one through an indirect manipulation with pointers, but the render method is not called;
The second one I use the backend of the mounted component, so it displays `Changing state` in the console, but the render method is never called either.

What am I doing wrong?

**Comment by MikaelMayer** [comment]
I found the solution. Since setState and modState are just callbacks now (which they were'nt before), I needed to replace the line:

    $.setState(data)

by 

    $.setState(data).runNow()

**Comment by japgolly** [comment]
Yes, that's it. Glad you got it sorted.
