### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#311]
I'm trying to build the neo branch but when I try to run tests via (`test` or `firefox:test`) I keep getting this error related to phantomjs:

```
  Error: WebSocket closed before being opened: [object CloseEvent]

  phantomjs://code/phantomjs-launcher4208776845920356393.js:9 in onError


  phantomjs://code/phantomjs-launcher4208776845920356393.js:11 in onError
  file:///var/folders/rl/4m0t_d494wz8_lzqj1l8yq500003mj/T/1477235618709-0/comSetup.js:55 (in function "onclose")

  phantomjs://code/phantomjs-launcher4208776845920356393.js:13
```

I'm running on OSX with phantomjs 2.1.1 installed with hombrew

Any idea of what's wrong?

**Comment by japgolly** [comment]
That's weird. They work for me but I'm on Linux so I've not tried OSX.
For the record, I'm on PhantomJS 2.1.1 as well.

**Comment by japgolly** [comment]
We'll eventually switch over to Node.JS + jsdom for testing. Good to cose this?

**Comment by cquiroz** [comment]
Sure, I gave up on phantom js long ago
