### ISSUE TITLE
Support React.PureComponent

### ISSUE THREAD

**Issue by jtcwang** [japgolly/scalajs-react#314]
```
React.PureComponent is exactly like React.Component but 
implements shouldComponentUpdate() with a shallow prop and state comparison.
```
https://facebook.github.io/react/docs/react-api.html#react.purecomponent

With scala's immutability ecosystem, we should really take advantage of shallow comparison (`eq`) in `shouldComponentUpdate` to take for essentially free preformance gain by avoiding virtual dom calculations altogether.
It'll be cool to have a method called `pureComponent` somewhere before `.build` is called to attach a `shouldComponentUpdate` with a shallow shallow comparison.

**Comment by japgolly** [comment]
We already have this, in fact we've had this for years in scalajs-react.

Before you call `.build`, you just need to add:
```scala
  .configure(Reusability.shouldComponentUpdate)
```

Doc: https://github.com/japgolly/scalajs-react/blob/master/doc/PERFORMANCE.md#reusability

Demo: https://japgolly.github.io/scalajs-react/#examples/reusability

**Comment by jtcwang** [comment]
Even better than expected! Sorry for missing it in the docs!
