### ISSUE TITLE
How to trigger hashchange when using router

### ISSUE THREAD

**Issue by nghuuphuoc** [japgolly/scalajs-react#317]
I want to do some things when the hash changes.
My approach is to listen to `hashchange` event:

```
private case class Backend(scope: BackendScope[Props, State]) extends OnUnmount {
    def onChangePage(e: HashChangeEvent): Callback = {
      Callback {
        println(s"newUrl=${e.newURL}, oldUrl=${e.oldURL}")
      }
    }
  }

  private val component = ReactComponentB[Props](componentName)
    .initialState(State(...))
    .renderBackend[Backend]
    .configure(
      EventListener[HashChangeEvent].install("hashchange", _.backend.onChangePage, _ => dom.window)
    )
    .build
```

The `Backend.onChangePage` is called when I click the `Back` button of browser, but it isn't called when I click a link generated by `routerCtrl.link(Page)` despite the fact that clicking on that link will bring us to new page and the hash in URL is changed.

**Comment by japgolly** [comment]
Any update here? Is there anything that this lib should do differently?
