### ISSUE TITLE
Add ^.svg.path attribute

### ISSUE THREAD

**Issue by neutrospec** [japgolly/scalajs-react#318]
animateMotion element has "path" attribute.
but ^.svg.path is missing.

**Comment by neutrospec** [comment]
I tried `"path".reactAttr := "M..."` but react.js rejected too.
according to [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion) 'path' is valid attribute. spooky.
I could do work around by using `<mpath xlinkRef="">`.

**Comment by garhirunrat** [comment]
Have to tried this?
```
<.svg.svg(
    ^.svg.viewBox := "0 0 1 1",
    ^.svg.width := "1",
    ^.svg.height := "1")(
    <.svg.path(
           ^.svg.d := "..."
    )
)
```

**Comment by neutrospec** [comment]
Yes. <.svg.path works.
^.svg.path does not exist. and i think react.js does not support “path” attribute neither.
