### ISSUE TITLE
Blocking transition changes in the router

### ISSUE THREAD

**Issue by tilk** [japgolly/scalajs-react#321]
As I understand currently, there is no way to tell the router to disallow switching to other locations - e.g. when an edit is in progress and the data is unsaved (or even unsaveable - for example when not valid). Irreversibly losing user input is not a good behavior. One can try adding checks in various callbacks, but this is inelegant and does not solve the issue with browser navigation buttons.
Or is there a method I'm not aware of?

**Comment by japgolly** [comment]
No there isn't anything built in to the Router for this. Navigation to a route is total: https://github.com/japgolly/scalajs-react/blob/master/extra/src/main/scala/japgolly/scalajs/react/extra/router/RouterCtl.scala#L19

One idea could be to use `.when` or `.unless` on the `Callback`.
Eg: `^.onClick ==> routerCtl.set(page).unless(editIsInProgress)`.

It might also be an idea to add a method to RouterCtl like:
```scala
trait RouterCtl[A] {
  def modifyRouting(f: Callback => Callback): RouterCtl[A]
}
```
in which you can get a new RouterCtl instance which has your additional logic applied each time a route is executed. Or something like that.

**Comment by japgolly** [comment]
@tilk I was just looking at `RouterCtl` and there's an `onSet` method that sounds like it'll do what you need:
https://github.com/japgolly/scalajs-react/blob/master/extra/src/main/scala/japgolly/scalajs/react/extra/router/RouterCtl.scala#L43-L48

**Comment by japgolly** [comment]
Closing this. `RouterCtl#onSet` is the solution here as it can be used to customise actions when a route is requested. In this case, customise would mean checking whether an edit is in progress and if so, returning a different `Callback` disallowing and maybe notifying the user.
