### ISSUE TITLE
Need to fix and to extend docs for Setup section

### ISSUE THREAD

**Issue by akarasev** [japgolly/scalajs-react#325]
[Setup section](https://github.com/japgolly/scalajs-react/blob/master/doc/USAGE.md#setup) is very small and should be extended for newcomers (e.g. as I am)

For example, I've faced an issue after I've carefully performed those two steps and I have: 

> [info] Fast optimizing C:\tmp\scalajs-react\target\scala-2.12\scala-js-tutorial-fastopt.js
> [info] Running org.example.TutorialApp
> [error] module.js:471
> [error]     throw err;
> [error]     ^
> [error] 
> [error] Error: Cannot find module 'react'
> [error]     at Function.Module._resolveFilename (module.js:469:15)
> [error]     at Function.Module._load (module.js:417:25)
> [error]     at Module.require (module.js:497:17)
> [error]     at require (internal/module.js:20:19)
> [error]     at C:\Users\avkar\AppData\Local\Temp\1484704765073-0\react-dom.js:16:24
> [error]     at Object.<anonymous> (C:\Users\avkar\AppData\Local\Temp\1484704765073-0\react-dom.js:40:3)
> [error]     at Module._compile (module.js:570:32)
> [error]     at Object.Module._extensions..js (module.js:579:10)
> [error]     at Module.load (module.js:487:32)
> [error]     at tryModuleLoad (module.js:446:12)
> org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
> 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:107)
> 	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
> 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:684)
> 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:771)
> 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:765)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> [trace] Stack trace suppressed: run 'last compile:run' for the full output.
> [error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
> [error] Total time: 3 s, completed 18.01.2017 8:59:25

I believe, if the Setup section would be more descriptive, it will help.

Thanks!

**Comment by japgolly** [comment]
This issue needs more information. I've not seen that error. Did you solve it?

**Comment by akarasev** [comment]
No, I didn't. What kind of info do you need?

**Comment by japgolly** [comment]
I've got nothing to add to the doc cos I've not experienced the problem you're having. No more info = no progress possible here.

**Comment by akarasev** [comment]
It happens only when I tried to set up a pure Scala.js project from scratch. I'm able to run a sample based on Play Framework [ochrons / scalajs-spa-tutorial](https://github.com/ochrons/scalajs-spa-tutorial)

It's probably related to Node.js. Do I need to install `react` module using Node.js?

**Comment by akarasev** [comment]
Btw, I've asked about it on [StackOverflow](http://stackoverflow.com/questions/41710674/unable-to-run-scalajs-react-project). You may take look there or I could duplicate that info here. It's up to you.

**Comment by japgolly** [comment]
Ah ok, let's talk about it on SO then and hopefully get more eyes.

**Comment by akarasev** [comment]
The solution discussed [here](http://stackoverflow.com/questions/41710674/unable-to-run-scalajs-react-project). So, the issue might be closed.

**Comment by japgolly** [comment]
Glad that worked out for you :)
