### ISSUE TITLE
Unable to render a tag of type input due to requiring a child

### ISSUE THREAD

**Issue by mdedetrich** [japgolly/scalajs-react#327]
ReactJS version: 0.11.3

I am currently trying to make a wrapper for antdesign, and I am having issues rendering their Input component, you can see the relevant code at https://github.com/mdedetrich/scalajs-antdesign/blob/master/src/main/scala/scalajs/antdesign/Input.scala#L96-L100

When I try the following code

```scala
<.span(^.className := "someField")(
  Input(value = someField.asString)()
)
```

It compiles fine, however then the browser responds with the following error

```
input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`. Check the render method of Input.
```

Which makes sense, since Input fields aren't meant to have an inner element however if you try to do the following

```scala
<.span(^.className := "someField")(
  Input(value = someField.asString)
)
```

There is an example of the issue uploaded at the following repo https://github.com/mdedetrich/scalajs-antdesign-issue, specifically https://github.com/mdedetrich/scalajs-antdesign-issue/blob/master/client/src/main/scala/example/ScalaJSExample.scala#L18

You will get a compile error, is there any way around this?

**Comment by japgolly** [comment]
Is it not because of [this](https://github.com/mdedetrich/scalajs-antdesign/blob/master/src/main/scala/scalajs/antdesign/Input.scala#L99) which is always providing children?

I'm a little unsure about that cast to `ReactComponentU_`. Have you checked the Types doc? I forget how it works cos I've been working on a redesign of scalajs-react atm ([see here](https://github.com/japgolly/scalajs-react/tree/topic/neo)) and in the new design it's muuuuuuuuuch easier and clearer to wrap JS components ([example](https://github.com/japgolly/scalajs-react/blob/74e31c9b25353a87962d6a56de02d39fac87715c/neo/src/test/scala/japgolly/scalajs/react/JsComponentTest.scala#L143-L154)). Maybe it would be easier for you to wait and/or target the new version.

**Comment by mdedetrich** [comment]
> Is it not because of this which is always providing children?

> I'm a little unsure about that cast to `ReactComponentU_`. Have you checked the Types doc?

Yes, but if thats the case, what should I be casting to instead of `ReactComponentU_`? I tried looking at the source code/docs of scalajs-react and couldn't find anything (i.e. something that is a `ReactComponentU_` that allows no children?)

> Maybe it would be easier for you to wait and/or target the new version.

This is slightly urgent from my end so not sure if targeting neo is an option (and I have other scalajs-react dependencies which don't support neo yet). Would it be possible to make a version of `ReactComponentU_` which doesn't require children for this case that is binary compatible with scalajs-react 0.11.3?

I would be willing to do a PR to implement this (with maybe some extra guidance to get me going)

**Comment by japgolly** [comment]
Wait a sec, React is saying `input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`. Check the render method of Input.` and I can see that you're [passing children here](https://github.com/mdedetrich/scalajs-antdesign/blob/master/src/main/scala/scalajs/antdesign/Input.scala#L99). It sounds to me like you should stop passing children in `antdesign/Input.scala`.

**Comment by mdedetrich** [comment]
![](http://rifleman.altervista.org/friendtest/doh.jpg)

I just changed it to this (https://github.com/mdedetrich/scalajs-antdesign/blob/master/src/main/scala/scalajs/antdesign/Input.scala#L99) i.e. 

```scala

  val f =
      React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.global.antd.Input)
    f(toJS).asInstanceOf[ReactComponentU_]
```

However I am still getting this problem

```scala
      <.div("Hello there ", name)(
        Input(defaultValue = name)
      )
```

```
[error] /Users/matthewdedetrich/github/scalajs-antdesign-issue/client/src/main/scala/example/ScalaJSExample.scala:18: type mismatch;
[error]  found   : scalajs.antdesign.Input
[error]  required: japgolly.scalajs.react.vdom.TagMod
[error]         Input(defaultValue = name)

```

**Comment by japgolly** [comment]
Hehe glad to hear it!
