### ISSUE TITLE
Route conditions not evaluated in RouterCtl#set

### ISSUE THREAD

**Issue by SerG-Y** [japgolly/scalajs-react#329]
I added condition to my route
`(staticRoute("/profile", ProfilePage) ~> renderR(ctl => Profile(ctl)))
      .addCondition(grantPrivateAccess)(_ => redirectToPage(Home)(Redirect.Push))`

When i use `<a href="/profile">` or `window.location.href = "/profile"` it works,
but when I use methods of RouterCtl (`set(ProfilePage)`) condition `grantPrivateAccess` isn`t checked and  it goes to ProfilePage
How can I fix it ?

**Comment by japgolly** [comment]
Sounds like a bug, well done!

**Comment by japgolly** [comment]
As a temporary hack, you could use `RouterCtl#contramap` to workaround this.
So something like:
```scala
def temporaryWorkaround(r: RouterCtl[MyPage]): RouterCtl[MyPage] =
  r.contramap {
    case ProfilePage | AccountPage if !grantPrivateAccess() => Home
    case p => p
  }
```

**Comment by japgolly** [comment]
As a temporary hack, you could use `RouterCtl#contramap` to workaround this.
So something like:
```scala
def temporaryWorkaround(r: RouterCtl[MyPage]): RouterCtl[MyPage] =
  r.contramap {
    case ProfilePage if !grantPrivateAccess() => Home
    case p => p
  }
```

**Comment by japgolly** [comment]
Hey @SerG-Y, I think you might have a bug in your app. I just wrote a unit test for this issue and it passes. 0791d7604465a052dd047e4845977aa3cf8df092 shows that calling `.set` will still check the route condition.

**Comment by SerG-Y** [comment]
This bug manifests itself only when I change the value (for example `isUserLoggedIn`) in real-time.
You can see example in my gist:
https://gist.github.com/SerG-Y/b7db590c0e8d0bfbdb6e6c645b96569f

**Comment by japgolly** [comment]
You've got impure code outside of `Callback`; side-effects must be captured inside `Callback`. To be specific, `localStorage` (just like a global variable) isn't referentially-transparent and is the problem here. 

Try changing
```scala
def grantPrivateAccess = {
    val rule: js.Any = global.window.localStorage.getItem("token")
    if(rule != null)
      CallbackTo(true)
    else
      CallbackTo(false)
  }
```
to this:
```scala
val grantPrivateAccess = CallbackTo {
    val rule: js.Any = global.window.localStorage.getItem("token")
    rule != null
  }
```

**Comment by SerG-Y** [comment]
It works great! Thank you very much

**Comment by japgolly** [comment]
Awesome & no worries!
