### ISSUE TITLE
withEffectsImpure causes modeState to be marked as error by IntellJ

### ISSUE THREAD

**Issue by searler** [japgolly/scalajs-react#335]
I copied the [web source example](https://github.com/japgolly/scalajs-react/blob/master/gh-pages/src/main/scala/ghpages/examples/WebSocketsExample.scala).
sbt builds the project without any issues and the code works as expected.

However, IntellJ marks the 
 `direct.modState(_.log("Connected."))`
lines as faulty with the error
 `expected: (MountedWithRoot.this.State) => MountedWithRoot.this.State : actual : (MountedWithRoot.this.State) =>Any`

The error does not occur if the `modState` is a no-op, simply returning the parameter.

The alternative implementation ` $.modState(_.log("Connected.")).runNow()` is accepted by the IDE and is functional

This is obviously a deficiency in the IDE, which impacts the usability of scalajs-react.
Is there a way to express this logic in a manner that does not cause Intellj to fail?

Thank you

**Comment by japgolly** [comment]
Hi. It's very annoying to see red in IntelliJ only to discover that it works fine in scalac/SBT and is an IntelliJ bug. It's not just one or two issues, there are literally hundreds of similar bugs in IntelliJ Scala plugin, last time I checked there were over 700. The bugs affect many, many libraries in the community. It's a sad state of affairs.

There are no simple changes that could be made here to workaround IntelliJ's bugs. I think the only solutions are:
* switch IDEs, anything based on Ensime is 100% accurate (I think)
* raise an issue with IntelliJ and beg them to fix it. Frustrating as their product/output may be, they are nice people and can be convinced to prioritise fixes. I already asked them to fix an error that would've caused *all* new scalajs-react usage to be red. It took a while, but they kindly did fix it after a few months.
* Live with it and/or wait. I'm in this shit bucket. I only trust SBT and always have it open. I'm *hoping* that they'll eventually switch to a method more reliable than trying to reimplement scalac (maybe scala.meta?) but who knows how long that will take.
