### ISSUE TITLE
 Getting CSSProperties from HtmlStyles

### ISSUE THREAD

**Issue by dbolotin** [japgolly/scalajs-react#338]
Is there any way to convert `HtmlStyles` to a raw react `CSSProperties` ([link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/index.d.ts#L625)) object?
We are trying to write binding to ant-design using approach described in the "Interopability" section from the docs you recently published (we are on 1.0.0-RC1), and need this type to pass to underlying component in props (see e.g. this [line](https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx#L26)).

**Comment by dbolotin** [comment]
This is the workaround we came up with:
```scala
import scala.scalajs.js
import scala.scalajs.js.{Dynamic, JSON}

import japgolly.scalajs.react.vdom.{Builder, TagMod}

@js.native
trait CSSProperties extends js.Object

object CSSProperties {
  def apply(mods: TagMod*): CSSProperties = {
    val builder = new Builder
    for (m <- mods)
      m.applyTo(builder)
    val dynamic = builder.render("a").rawNode.asInstanceOf[Dynamic]
    dynamic.selectDynamic("props").selectDynamic("style").asInstanceOf[CSSProperties]
  }
}
```

**Comment by japgolly** [comment]
Hmm, that's something I hadn't considered. Not all `TagMod`s are styles, some are tags, attributes. Would it make more sense to have something exposed on [`Style`](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/vdom/Style.scala)? Have a subclass of `TagMod` that identifies it as a style? We could add a method to it (or `TagMod` for a less precise, less typed option) that returns the style as an object.

**Comment by dbolotin** [comment]
Yes, definitely, if there where a specific `trait` for style `TagMod`s it would be possible to make implementation "more type-safe". I have some doubts about `TagMod.Composite`, it seems hard to make it track TagMod type, so two, say, `StyleTagMod`s combined will not give `StyleComposite`. Or I am missing the point of `TagMod#apply` method and `TagMod.Composite`? What is the use-case for it? Anyway, composition seems to be of little use for style `TagMod`s, so all this may not be important.

*Small update about implementation*: additionally to the previously posted code we added implicit conversion from tuples of `TagMod`s to `CSSProperties`:
```scala
...
implicit def fromTuple3(mods: (TagMod, TagMod, TagMod)): CSSProperties = 
    apply(mods._1, mods._2, mods._3)
...
```
this allows to use the following syntax:
```scala
object SomeComponent {
    def apply(..., style: CSSProperties, ...) = ...
}

SomeComponent(style = (^.borderColor := "black", ^.borderWidth := 1.px))
```

**Comment by japgolly** [comment]
Hi @dbolotin, unfortunately I don't have capacity to give this attention. If you've got time and good ideas try a PR, cheers.

**Comment by dispalt** [comment]
I just mentioned this in gitter @japgolly but even if you could make the `Builder` class non-final or some of the attributes `props` or `style` package-private (thus denoting there be dragons) this would be even a little less hacky

**Comment by japgolly** [comment]
This came up again in #385 and I had an easy solution in mind (for whatever reason I didn't before). I've made this change on master: 7ab69eb92a8e2afc595fa60b6057d7a50368c1ea

Ttake a look [at this](https://github.com/japgolly/scalajs-react/blob/7ab69eb92a8e2afc595fa60b6057d7a50368c1ea/core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala#L42-L55). If you use that builder then you get easy access to props/style/children as raw JS objects.

I'll probably add a method for this soon but for now, you can use it like this:
```scala
val myVdom: TagMod = ...
val b = new Builder.ToJs{}
myVdom.applyTo(b)
// now use the results
b.addStylesToProps()
b.props // js.Object
b.nonEmptyProps // js.UndefOr[js.Object]
```

WDYT?

**Comment by dispalt** [comment]
I like it, thanks, I've been using the workaround but obviously this is much better,

**Comment by japgolly** [comment]
This is fixed in v1.1.0. Now you can call `.toJs` on any `TagMod` and get all the styles as a `js.Object`.

**Comment by dbolotin** [comment]
Thanks! We will upgrade as soon as release will be in maven.

**Comment by japgolly** [comment]
Ok release is in Maven. Please give it a try.
I'm going to close this issue for now but feel free to re-open it if you need.
