### ISSUE TITLE
markdown editor demo in scalajs-react

### ISSUE THREAD

**Issue by scweang** [japgolly/scalajs-react#339]
Hi~~~

I begin to learn scala.js and this library planning to apply it to my future projects. I'm trying to implement code in https://facebook.github.io/react/ and I have implemented the first two successfully.

However, I'm stuck in the markdown editor. I don't know how to use remarkable in scala.js and scalajs-react. Can there be a demo showing how to use scala.js to implement this case?

Thanks a lot in advance for your help~

**Comment by scweang** [comment]
I've solved this. Sorry for open an issue rushly.

**Comment by japgolly** [comment]
No worries.
