### ISSUE TITLE
Have ScalaComponent.builder generate ES6 classes

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#340]
Currently when you use `ScalaComponent.builder` it uses `React.createCreate` under-the-hood. In order to generate ES6 classes instead, nearly all the work has been done (hoorah 🎉 ). It's just blocked by https://github.com/scala-js/scala-js/issues/2805 (although there is a non-ES6 workaround available).

Note: when this ability becomes available I might allow users to choose whether to generate ES3/ES6. It's totally opaque so it shouldn't matter. As for the default, I'm thinking I'll probably just keep the current method as default until:
1. Somebody demonstrates that the ES6 method results in improved performance. (Just saying so isn't enough; let's see quantifiable evidence, even if its just a few simple benchmarks.)
2. Or, React deprecates `React.createClass`.

**Comment by chandu0101** [comment]
https://github.com/facebook/react/issues/8854

don't bet on `React.createClass` any more ;) ,  remove that nigga  from your code base :P

**Comment by japgolly** [comment]
Thanks @chandu0101! Ok maybe I'll take the workaround approach and get rid of this for 1.0...

**Comment by japgolly** [comment]
Closed via e74028afa76d275f84d634d3f0242f482b502969

Now `.build` creates a class extending `React.Component.`
Users can also (for whatever reason) call `.buildWithReactCreateClass` instead if desired, maybe as a temporary workaround if something goes wrong with the new method.
