### ISSUE TITLE
autoFocus attribute doesn't work when used on a div (with tabIndex :=1 also) (RC1)

### ISSUE THREAD

**Issue by bpatters** [japgolly/scalajs-react#342]
When I set tabindex on a <div> element and the autofocus attribute the element doesn't have focus, and receive key events, until I click on the element.

**Comment by japgolly** [comment]
Yeah that's a problem with React itself, you'll have to raise an issue them for that.

I had the same problem here: https://japgolly.github.io/scalajs-react/#examples/callback-option
To see how I worked around it, search that page for `outerRef`.

**Comment by bpatters** [comment]
Cool thanks, that worked for me :).
