### ISSUE TITLE
Standardizing on Cats?

### ISSUE THREAD

**Issue by a1russell** [japgolly/scalajs-react#345]
Since 1.0.0 hasn't quite been released yet, I'm wondering whether we can discuss standardizing on Cats rather than Scalaz.

As evidenced by the [recently announced joint effort by popular libraries doobie, http4s, and Matryoshka](https://http4s.github.io/fp-ecosystem/), Cats is gaining momentum versus Scalaz.

In fact, I've personally avoided using scalajs-react in the past in part because of the Scalaz dependency/association.

I'm curious whether you might consider moving to Cats instead.

**Comment by japgolly** [comment]
Hi @a1russell, scalajs-react doesn't have a dependency on Scalaz, although it used to a long, long time ago. Now it has an optional extension module that provides Scalaz support but neither `core`, `test` or `extra` use it.

Users are free to use the Scalaz module, the Cats module, neither or both. :)

Does that address your query?

**Comment by a1russell** [comment]
Oh! Is it just the tests that depend on it, then? I saw Scalaz in the [build file](https://github.com/japgolly/scalajs-react/blob/v1.0.0-RC2/project/Build.scala) and guess I did not read it thoroughly enough.

**Comment by japgolly** [comment]
Well it's a bit unconventional but only the tests of the `test` module do (*whaat?*); the actual `test` module that gets exported doesn't depend on it (*hoorah!*).

**Comment by a1russell** [comment]
Ah, okay, hah.

I was a excited to see #341 get merged. Will it be ported to the neo branch, as well?

**Comment by japgolly** [comment]
The neo branch became 1.0.0-RC1 which was merged into master. Master is the
new neo branch now so in that sense, yes; done! In fact it's been released
already too because it was part of 1.0.0-RC2.

**Comment by a1russell** [comment]
Oh, I understand now. That's great! Closing this.

**Comment by japgolly** [comment]
No worries; cheers!
