### ISSUE TITLE
modState and setState callback not respecting the >> operator

### ISSUE THREAD

**Issue by markotron** [japgolly/scalajs-react#349]
Hi there, 

In the Common Mistakes section of the Callback doc, it says that the correct version of chaining `modState` callback with another is: 

`val increment: Callback =
  $.modState(_ + 1) >>
  Callback.log("Incremented count by 1")`

However, when I tried something like this: 

`bs` is of type `BackendScope[Unit, Int]`
`val cb = bs.modState(_ + 1) >> bs.state >>= (s => Callback(println(s)))`

I get an unexpected value - if the initial state is zero, calling `cb` for the first time will print `0`, calling it for the second time will print `1`, and so on.

After checking the `modState` function I realized that there is a second parameter. If I put the callback `bs.state >>= (s => Callback(println(s)))` there, it works. 

Am I doing something wrong here?

PS. The code on which I tested this behavior is almost the same as the one above, the only difference is that the state is not and Int but a custom class: 
`bs.modState(s => s.copy(selectedType = selectedType)) >> bs.state >>= (s =>
      Callback(println(s.selectedType)))`

Thanks,
Marko

**Comment by ramnivas** [comment]
This is because `modState` (which maps to `setState` in React) is async. So in your case, `_ + 1` will be executed by React sometime in future. This is why when you used the second parameter version, things worked correctly (React calls the function passed as the second parameter once the update expressed in the first parameter is actually executed).

**Comment by markotron** [comment]
Hi Ramnivas, 

thanks for the quick reply. Ok, that's what I thought. But, then the documentation is not correct, right? 

This will not do what it should: `$.modState(_ + 1) >> Callback.log("Incremented count by 1")` as you cannot be certain that the `log` method will be executet after the `modState` method.

Best,
M

**Comment by ramnivas** [comment]
Yah, I think "Scheduled to increment count by 1" might make the behavior clear.
