### ISSUE TITLE
Allow child/children of String type for Js components

### ISSUE THREAD

**Issue by ramnivas** [japgolly/scalajs-react#350]
I am trying to create a scalajs-react wrapper for the MDC button component (https://kradio3.github.io/react-mdc-web/components/button/). Here is what I got

```scala
package mdc

import japgolly.scalajs.react._
import japgolly.scalajs.react.vdom.VdomElement

import scala.scalajs.js

object Button {
  private val RawComponent = js.Dynamic.global.Button

  private val component = JsComponent[js.Object, Children.Varargs, Null](RawComponent)

  def apply(className: js.UndefOr[String] = js.undefined,
            raised: js.UndefOr[Boolean] = js.undefined,
            dense: js.UndefOr[Boolean] = js.undefined,
            primary: js.UndefOr[Boolean] = js.undefined,
            compact: js.UndefOr[Boolean] = js.undefined,
            accent: js.UndefOr[Boolean] = js.undefined,
            onClick: js.UndefOr[Callback] = js.undefined)(children: VdomElement) =
    component(js.Dynamic.literal(className = className, raised = raised, dense = dense, primary = primary, compact = compact, accent = accent,
      onClick = () => onClick.map(_.runNow())))(children)
}
```

This is fine when I use it the following way:
```scala
 Button(raised = true, primary = true, onClick = onViewDetails)(span("Details"))
```

But I will like to avoid the `span` around `"Details"`:
```scala
 Button(raised = true, primary = true, onClick = onViewDetails)("Details")
```

I don't see a way to make a String be accepted as a VdomElement. How do I do that?

p.s. Note that I am not defining the `Props` type as explained in the examples, since I have  `apply` defined to give me the needed type safety.

**Comment by japgolly** [comment]
According to the Scala types and React doc, that wouldn't be legal. That being said docs coming from JS-land aren't very trustworthy... have you tried this is JS-land to confirm that it works? Or alternatively, you could try some hacks like `VdomElement("Details".asInstanceOf[japgolly.scalajs.react.raw.ReactElement])` to see if it's really legal or not.

If it *is* ok, it looks like `vdom/Implicits.scala` will need an extra case.

**Comment by ramnivas** [comment]
According to https://facebook.github.io/react/docs/jsx-in-depth.html#children-in-jsx, it seems passing string as a child is legal in React.

I tried your suggestion of `VdomElement("Details".asInstanceOf[japgolly.scalajs.react.raw.ReactElement])` and it works fine, so indeed an implicit conversion should do the trick.

I didn't try in the JS-land per se, the Button example (https://kradio3.github.io/react-mdc-web/components/button/) comes from a live React app, so I guess that means it works in the JS land.

**Comment by japgolly** [comment]
I was just thinking about this and I thought, *wait, children are node-lists, not elements...*.
The declaration of `VdomElement` is in your code above, not the library. I didn't realise that but that's good, we can fix your example above without library changes.

So what you've done there is create a private JS component with a constructor that needs props (js.Object) and children. If you want to have a usage pattern similar to above where you massage the props

**Comment by japgolly** [comment]
ah we typing at same time :D
I'll my edit my comment above to finsih

**Comment by japgolly** [comment]
...yourself and then expect children to be provided externally, what you could do is just provide the props to the constructor which results in a constructor where only the children need be provided.

Instead of `(p)(c) => component(p)(c)`, use `(p) => component.mapCtorType(_ withProps p)`

So for your example:
```scala
  def apply(className: js.UndefOr[String] = js.undefined,
            raised: js.UndefOr[Boolean] = js.undefined,
            dense: js.UndefOr[Boolean] = js.undefined,
            primary: js.UndefOr[Boolean] = js.undefined,
            compact: js.UndefOr[Boolean] = js.undefined,
            accent: js.UndefOr[Boolean] = js.undefined,
            onClick: js.UndefOr[Callback] = js.undefined) =
    component.mapCtorType(_.withProps(
(js.Dynamic.literal(className = className, raised = raised, dense = dense, primary = primary, compact = compact, accent = accent,
      onClick = () => onClick.map(_.runNow())))
    ))

```

**Comment by japgolly** [comment]
Also for reference:
* https://github.com/japgolly/scalajs-react/blob/v1.0.0-RC2/core/src/main/scala/japgolly/scalajs/react/component/Generic.scala#L27
* https://github.com/japgolly/scalajs-react/blob/v1.0.0-RC2/core/src/main/scala/japgolly/scalajs/react/CtorType.scala#L80

**Comment by japgolly** [comment]
And for further reference, looking at https://github.com/japgolly/scalajs-react/blob/v1.0.0-RC2/core/src/main/scala/japgolly/scalajs/react/CtorType.scala#L68-L69 I see `(children: ChildArg*)` where above it has `type ChildArg = vdom.VdomNode` which means if you just preferred your original approach you could change `(children: VdomElement)` to `(children: VdomNode*)`.

**Comment by ramnivas** [comment]
This is great! Thanks for pointing me in the right direction. I'll add more here as I experiment through.

For my purpose, this issue may be closed. I wonder, though, for general usage, given how React allows string as a child (and I have seen this being used in many places, several in the react-mdc itself), providing an implicit conversion (or some other mechanism to the same effect) would be a good idea, anyway.

**Comment by japgolly** [comment]
Glad to hear it!

React allows String as a child because children are what it calls "nodes", not "elements". Thus if you use `VdomNode` here in scalajs-react it will work as expected, i.e. String will be allowed implicitly and React will accept it as a child.

> For my purpose, this issue may be closed. 
np will close
