### ISSUE TITLE
The best way to get the state in a backend class

### ISSUE THREAD

**Issue by markotron** [japgolly/scalajs-react#351]
Hi, 

I'd implemented a component that has an input box and does something when the user hits the enter key. 

I defined an `onKeyUp` method. The method combines the information from the text field and the properties. What's the best way to get the properties object? 

Is it ok to send the properties as the parameter (as I'm calling it from the `render` method where the prop object is available) to the `onKeyUp` method (this will make the function pure) or I should use the `backend.props` callback in the method to get the object and then flatMap it other callbacks? 

What if the function needs the properties object and the state object to do the work?

Best, 
M

**Comment by japgolly** [comment]
Hi @markotron. There are two ways, like you say yourself, I'll just frame them a little differently:

1) Make the event handler nullary and independent('ish). It gets props and/or state from `BackendScope` and `flatMap`s it all together. These callbacks can be declared once, stored as a `val` in the backend class.

2) Make the event handler a function that requires a single instance of props and/or state and then using it, returns a callback. Any other functions that you want to build on top of this (compose with) would similarly need to declare single instances of props and/or state to thread though, then the only place you can use it (without cheating) becomes your render method.

Both ways are pure. Both ways are easy to test (the former with a little help from `ReactTestVar`).
I don't know of any huge advantage or disadvantage to going either way. I mostly prefer the former myself.

If you're composing multiple modifications of state on the other hand, then it's a different story...
