### ISSUE TITLE
What happened to Addons

### ISSUE THREAD

**Issue by edmundnoble** [japgolly/scalajs-react#352]
The title says it all. Now they all just extend js.Any, so there's no Scala API. I don't understand the comment that's been left in place; and there is no mention in the changelogs of any of the contents, and there is no explanation of how to use the addons after the change.

**Comment by japgolly** [comment]
I don't understand your issue. It's still there: https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/ReactAddons.scala

Could you tell me what is it specifically you're trying to do?

**Comment by japgolly** [comment]
This may be helpful if it's the `CSSPropTransWhateverThingy` you're using: https://japgolly.github.io/scalajs-react/#examples/animation

**Comment by edmundnoble** [comment]
My mistake; I searched `CSSTransitionGroup` in IntelliJ's class search and only found the `WebpackRequire.CSSTransitionGroup` object.

**Comment by japgolly** [comment]
ah np. Good though because this confirms that there are actually users of `React.addons.CSSBlah` out there and I didn't continue supporting it for nothing. :grin:
