### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by KadekM** [japgolly/scalajs-react#353]
On various linked tuts from github page (i.e. https://japgolly.github.io/scalajs-react/#examples/todo)
there is code
`ScalaComponent.build[Unit]("TodoApp")` which I believe should be
`ScalaComponent.builder[Unit]("TodoApp")`

Tiny change, but I think it could be little discouraging someone new trying to learn lib not to be able to copy  & paste without problems.

**Comment by japgolly** [comment]
Ah, thanks for pointing this out. This part of the API changed in 1.0.0-RC2 and now the github-pages need recompiling and republishing. I'll do that now...

**Comment by japgolly** [comment]
Ok fixed. Thanks for the report.

**Comment by KadekM** [comment]
Np. Thanks for **awesome** library @japgolly
