### ISSUE TITLE
Bump Scala/ScalaJS versions for Scalajs-react v0.11.x

### ISSUE THREAD

**Issue by mdedetrich** [japgolly/scalajs-react#354]
Since 0.6.15 is the last version for scalajs 0.6.x series (which adds a lot of improvements) and due to how scalajs binary compatibility works, I created a branch which bumps the versions in the 0.11.x series of scalajs-react.

The intention is that this should be the last release of scalajs-react for the 0.11.x series and since there are a lot of projects with non trivial code sizes that use scalajs-react 0.11.3, in the interests of binary compatibility it would be good to have a release which uses the latest version of scalajs

I have implemented the changes in https://github.com/mdedetrich/scalajs-react/tree/v0.11.4. The only other possible change that I can see is bumping the base react version from 15.3.2, however I think that is out of scope and will cause more problems.

@japgolly Would it be possible to create a branch based off the v0.11.3 tag (https://github.com/japgolly/scalajs-react/tree/v0.11.3), probably called v0.11.x, so I can make a PR against this branch, and then release 0.11.4?

Also I think in general its a good idea to have a 0.11.x branch for scalajs-react if issues like this prop up in the future (and we can trivially bump versions)

**Comment by japgolly** [comment]
Sure, all very good points, I'll create a `series/v0.11.x` branch now. :+1:

**Comment by mdedetrich** [comment]
Scalajs 0.6.16 just came out now, let me quickly rebump and make another PR

**Comment by japgolly** [comment]
Alrighty v0.11.4 is on its way to maven central

**Comment by mdedetrich** [comment]
Ill close the issue then, thanks a lot!
