### ISSUE TITLE
Changing the router location in React phases does not execute the route

### ISSUE THREAD

**Issue by simerplaha** [japgolly/scalajs-react#355]
In the sample code here, `router.set` does not seem to work in any of React's phases. In the actual code I'm trying to redirect in `LoginComponent` to `DashboardURL` during `componentDidUpdate` phase on successful User login. To keep things simple in this sample I've added `router.set(DashboardURL)` in `componentDidMount`. 

I can see that URL does gets set to `#dashboard` in the browser's address bar but the DashboardComponent never renders. Dashboard only renders if I clicked on the link "Link to Dashboard". 

I'm using scalajs-react 1.0.0 and React.js 15.5.4.

```scala
import japgolly.scalajs.react._
import japgolly.scalajs.react.extra.router.{Redirect, RouterConfigDsl, RouterCtl, _}
import japgolly.scalajs.react.vdom.html_<^._
import org.scalajs.dom
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSExport, JSExportTopLevel}

sealed trait LocationURL
case object DashboardURL extends LocationURL
case object LoginURL extends LocationURL

@JSExportTopLevel("Main")
object Main extends js.JSApp {

  @JSExport
  override def main(): Unit = {
    val router = Router(BaseUrl.until_#, Routes.routerConfig.renderWith((_, resolution) => resolution.render()))
    router().renderIntoDOM(dom.document.getElementById("myApp"))
  }
}

object Routes {
  val routerConfig = RouterConfigDsl[LocationURL].buildConfig {
    dsl =>
      import dsl._
      import japgolly.scalajs.react.vdom.Implicits._

      (emptyRule
        | staticRoute(root, LoginURL) ~> renderR(LoginComponent(_))
        | staticRoute("#dashboard", DashboardURL) ~>
        render {
          println("Does not print") //does not get here when the URL is set to DashboardURL in componentDidMount
          <.div("Dashboard")
        }
        ).notFound(redirectToPage(LoginURL)(Redirect.Replace))
  }

val LoginComponent =
    ScalaComponent.builder[RouterCtl[LocationURL]]("LoginComponent")
      .render_P(
        router =>
          <.div("Login page", 
           <.br,
            router.link(DashboardURL)("Link to Dashboard")
          )
      )
      .componentDidMount(_.props.set(DashboardURL))
      .build
}
```

**Comment by japgolly** [comment]
It it a prohibition of React maybe? `router.link` uses `.set` under the covers so if `.link` works then I'd imagine `.set` would too.
(You could also test that quickly with `<.button("Test", ^.onClick --> router.set(DashboardURL))`).

If it is some restriction of React not allowing it directly in it's lifecycle hooks, you could try using `setInterval` to run it after 0ms and see if that makes a difference.

**Comment by simerplaha** [comment]
`setInterval` seems to do the trick.

I will try it in Javascript and see if it's prohibited React.

Thank you :)
