### ISSUE TITLE
How to translate a field in a component without a value

### ISSUE THREAD

**Issue by i-am-the-slime** [japgolly/scalajs-react#357]
I am trying to translate this:
```javascript
<DatePicker
      showTime
      format="YYYY-MM-DD HH:mm:ss"
      placeholder="Select Time"
      onChange={onChange}
      onOk={onOk}
    />
```
And I am wondering about the "showTime" field. Is this a boolean in my façade?

**Comment by i-am-the-slime** [comment]
Boolean seems to work. Might want to document it some day.

**Comment by japgolly** [comment]
> Might want to document it some day.

PR welcome :)
