### ISSUE TITLE
How to use `Callback` with existing react components

### ISSUE THREAD

**Issue by i-am-the-slime** [japgolly/scalajs-react#358]
Can I just write the function façade, e.g.:

`var onChange: js.Function2[String, String, Unit] = js.native`

Like this instead:

`var onChange: js.Function2[String, String, js.Any] = js.native`

?

**Comment by i-am-the-slime** [comment]
It would just probably never run the Callback I guess.
Hmm...

**Comment by japgolly** [comment]
`Callback`s aren't meant to be passed to JS, they're meant to be fed back into scalajs-react. You're not even supposed to call `.runNow()` generally speaking.

Can you post a snippet of what you're doing?

**Comment by i-am-the-slime** [comment]
I have a façade that looks somewhat like this:

**Comment by japgolly** [comment]
If you're asking for callback types then wiring it up to facades yourself, then yes, you'll need to call `.runNow()` in a JS function. Or actually, there are methods starting with `.toJs` that will be helpful, check those out.

**Comment by SkyWriter** [comment]
It would be extremely helpful if INTEROP.md included an example of a callback with [optionally] a ReactEvent as a parameter. I've been struggling to find an elegant way to handle third-party components callbacks for a few days already.

@japgolly if you would point an example of proper callback interop handling I could make up a clarifying MR for INTEROP.md file myself.

And thanks for the wonderful work! Most of the scalajs-react experience is a pure joy for me!

**Comment by japgolly** [comment]
Hi @SkyWriter, awesome to hear that you're enjoying the library! That'd be awesome if you could make a PR for the interop doc.

How about this, say you have some facade like:
```scala
  @JSName("Example") @js.native
  object RawComponent extends js.Object

  type OnOk     = js.Function0[Unit]
  type OnChange = js.Function1[ReactEventFromInput, Unit]
  
  @js.native
  trait Props extends js.Object {
    var onOk    : js.UndefOr[OnOk]     = js.native
    var onChange: js.UndefOr[OnChange] = js.native
  }

  val component = JsComponent[Props, Children.Varargs, Null](RawComponent)
```

It has two different types of Callback-appropriate methods: `OnOk` and `OnChange`.

You could define a more Scala-friendly `props` creation method with `Callback`s like this:
```scala
  def props(onOk    : js.UndefOr[Callback]                        = js.undefined,
            onChange: js.UndefOr[ReactEventFromInput => Callback] = js.undefined): Props = {
    val p = (new js.Object).asInstanceOf[Props]
    onOk.foreach(f => p.onOk = f.toJsCallback)
    onChange.foreach(f => p.onChange = f.andThen(_.runNow()): OnChange)
    p
  }
```

or even like this if you don't mind the fields always being defined:
```scala
  def prop2(onOk    : Callback                        = Callback.empty,
            onChange: ReactEventFromInput => Callback = _ => Callback.empty): Props = {
    val p = (new js.Object).asInstanceOf[Props]
    p.onOk = onOk.toJsCallback
    p.onChange = onChange.andThen(_.runNow()): OnChange
    p
  }
```

@i-am-the-slime is this similar to your case too?

**Comment by SkyWriter** [comment]
Fantastic! Thanks for taking your time to elaborate it!

**Comment by japgolly** [comment]
Question: Answered. Closing.
