### ISSUE TITLE
Keep state in the `Router`

### ISSUE THREAD

**Issue by i-am-the-slime** [japgolly/scalajs-react#364]
I would like to have all my changes in state be reflected in the URI so that it's possible to share a link to the webpage at any given point in time.
I don't see any functionality like `setState` in the router however and I was wondering how to achieve this.

**Comment by japgolly** [comment]
I would imagine you would declare your route with a string-like param that you `.xmap` back to and forth from your state class. (See https://github.com/japgolly/scalajs-react/blob/master/doc/ROUTER.md#routex)

As for how to keep the URL up-to-date when the state changes, you'll have to figure that out for yourself or ask if anyone else has done it. I don't remember if the current routing infrastructure has everything you need or if it needs another function or two. I could read the docs and code but then so could you so I'll detach here.

**Comment by i-am-the-slime** [comment]
I could get it to work by really just updating the URI appropriately in component did update and parsing stuff inside the router.
