### ISSUE TITLE
Consider bringing back configureSpec

### ISSUE THREAD

**Issue by ngthanhtrung** [japgolly/scalajs-react#376]
I think `configureSpec` is useful for people who want to configure React classes at low-level. I also have some use-cases of it in previous versions of `scalajs-react`, for example context interoperability.

WDYT?

**Comment by japgolly** [comment]
Things are a little different now in that we have two means of creating Components:

* [`ViaReactComponent`](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/builder/ViaReactComponent.scala)
* [`ViaCreateClass`](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/builder/ViaCreateClass.scala)

Would you need to configure differently based on which method is used?

If not, then you could modify [`Builder`](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/builder/Builder.scala#L344-L356) to be:
```scala
    def build(implicit ctorType: CtorType.Summoner[Box[P], C]): Scala.Component[P, S, B, ctorType.CT] = {
      var c = ViaReactComponent(this)
      c = customiseRawClass(c) // <------ like this? ████████
      fromReactClass(c)(ctorType)
    }

    def buildWithReactCreateClass(implicit ctorType: CtorType.Summoner[Box[P], C]): Scala.Component[P, S, B, ctorType.CT] = {
      var c = ViaCreateClass(this)
      c = customiseRawClass(c) // <------ like this? ████████
      fromReactClass(c)(ctorType)
    }
```

Would that work?

**Comment by japgolly** [comment]
Actually I just remembered there's already a supported (but undocumented) way that you can do this!

Use `c.mapCtorType(_.addMod( f ))` where `c` is your component, and `f` is a `js.Object => Unit`.

Example:
```scala
  val Component = ScalaComponent.builder[Props]("Blah")
    .renderBackend[Backend]
    .build
    .mapCtorType(_.addMod { rawJsComponent =>
      rawJsComponent.asInstanceOf[js.Dynamic].customProperty1 = 123
      rawJsComponent.asInstanceOf[js.Dynamic].customProperty2 = "hello"
    })
```

**Comment by ngthanhtrung** [comment]
Thank you! Both way work!

So, what's the plan now? Out of these 2 solutions, the former sounds a bit hacky to me, since it's like adding a feature without systematic thinking. The later is better IMHO because at least we know that we're dealing with the raw class directly (knowing explicitly that we're going to do something hacky is less hacky LOL). However, it's still not nice as `configureSpec`, as with `configureSpec` users know its purpose clean and clear.

**Comment by japgolly** [comment]
No worries. The ability to externally modify anything related to components is very important, thus `mapCtorType` is the way to go here. The `.mapCtorType(_.addMod(...))` pattern is definitely less clearer and less convenient than a `configureSpec` function on the builder but I think that's acceptable because the use case is both advanced and uncommon. If it's so common that needs a simpler interface then I'd say we build a convenience method that desugars to `.mapCtorType(_.addMod(...))`.

Anyhow, closing now because this is supported.

**Comment by ngthanhtrung** [comment]
Fair enough.
