### ISSUE TITLE
Render to node?

### ISSUE THREAD

**Issue by DavidWhit** [japgolly/scalajs-react#400]
Alright, I've looked over the docs and I'm not getting it. 
How from say this js
```
ReactDOM.render(
  <MultiThemeProvider>
    <Router history={browserHistory} >
      <Route path="/" component={App} />
      <Route path="/quickorder/:form" component={QuickOrder} />
      <Route path="/admin" component={Admin} />
      <Route path="/orders(/:view)" component={OrderSwitch} />
      <Redirect from="*" to="/" />
    </Router>
  </MultiThemeProvider>,
  document.getElementById('root'),
);
```
Ignore the routes and theme wrapper. When I create a built component how do I render it to the html id place holder.  I see the deprecated render and to use the renderIntoDom yet it doesnt exist in ReactDOM and when I browse the lib I don't find it. I'm sure this is trivial but I'm just done looking at it for now as I haven't been productive.

**Comment by malaman** [comment]
Check [ghpages](https://github.com/japgolly/scalajs-react/tree/master/gh-pages/src/main/scala/ghpages) folder.
Render into HTML happens [here](https://github.com/japgolly/scalajs-react/blob/master/gh-pages/src/main/scala/ghpages/GhPages.scala#L66)

**Comment by DavidWhit** [comment]
Ah! this is the example I was looking for.  Thanks
