### ISSUE TITLE
Exporting to JS

### ISSUE THREAD

**Issue by vangogh500** [japgolly/scalajs-react#401]
Hi, it wasn't immediate obvious from the docs on interop if it were possible to export scala react components back to js for use with js apps. Could someone explain the process?

Thanks!

**Comment by japgolly** [comment]
Hi. Just call `.raw` to get the raw JS React component. That's it. Now use it like you would any other JS component.

If you're not sure what props it expects in JS-land, call `.root` (see https://github.com/japgolly/scalajs-react/blob/master/doc/TYPES.md#roots), and inspect its type. scalac output is very noisy but Intellij gives concise description.

Example:
![image](https://user-images.githubusercontent.com/202935/29160635-5e4be55e-7df6-11e7-814b-c7564ea9a93b.png)
This shows that it expects props of type `Box[Props]`.
Box is [defined here](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/internal/Box.scala).

If you this thing, it would be greatly appreciated if you could share your experience in a PR to update the existing `INTEROP.md` for any future users with similar needs.

**Comment by japgolly** [comment]
Closing cos I think this question has been answered. Feel free to re-open if needed.
