### ISSUE TITLE
StateSnapshot does not work in a backend

### ISSUE THREAD

**Issue by Tamriel** [japgolly/scalajs-react#402]
The main component in the StateSnapshot [example](https://japgolly.github.io/scalajs-react/#examples/state-snapshot) does not use a backend, but I need one. So I created one in this [repo](https://github.com/Tamriel/scalajs-react-statesnapshot/blob/master/src/main/scala/app/components/Main.scala). Its code

```
case class Name(firstName: String, surname: String)
class MainBackend($ : BackendScope[Unit, Name]) {
      def render(name: Name) = {
            val firstNameLens = GenLens[Name](_.surname)
            val firstNameV = StateSnapshot.zoomL(firstNameLens).of(name)
```
gives `could not find implicit value for parameter t: japgolly.scalajs.react.StateAccessor.ReadImpureWritePure[app.components.Main.Name,app.components.Main.Name]`.
Creating a StateSnapshot without zooming with `StateSnapshot.of(name)` gives the same error.

**Comment by japgolly** [comment]
To use it with BackendScope you need to construct it differently. Look at
the source code of StateSnapshot companion object, it's a mini DSL.

Also doc available at
https://github.com/japgolly/scalajs-react/blob/master/doc/EXTRA.md#statesnapshot

**Comment by Tamriel** [comment]
Thank you very much for the clarification!
I was able to solve it by simply using `.setStateVia($)` instead of `.of($)`:
```
class MainBackend($ : BackendScope[Unit, Name]) {
  def render(name: Name) = {
    val firstNameSnapshot =
      StateSnapshot.zoomL(Name.firstName)(name).setStateVia($)

    <.div(
      <.label("First name:", NameChanger(firstNameSnapshot)),
      <.p(s"My first name is ${name.firstName}")
    )
  }
}
```

**Comment by japgolly** [comment]
Awesome, I'm glad to hear it :)
