### ISSUE TITLE
What's the best way to modify state based on props?

### ISSUE THREAD

**Issue by pnachum** [japgolly/scalajs-react#405]
Sometimes the computation of new state should depend on the component's props. For example, if a `Counter` component accepts an `incrementAmount` prop that defines how much to increment its value by. 

```jsx
class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = { count: 0 };

    this.increment = this.increment.bind(this);
  }

  increment() {
    this.setState({
      count: this.state.count + this.props.incrementAmount,
    });
  }
  
  render() {
    return (
      <div>
        {this.state.count}
        <button onClick={this.increment}>+</button>
      </div>
    )
  }
}

<Counter incrementAmount={2} />
```

I'm wondering what's the best way to implement this in Scala.js. I think this works, but not sure if it's correct, or if there's a better alternative
```scala
class Backend(bs: BackendScope[Int, Int]) {
  def increment(): Callback =
    bs.props.flatMap(incrementAmount => bs.modState(_ + incrementAmount))
}
```

**Comment by malaman** [comment]
This answer might help:
https://github.com/japgolly/scalajs-react/issues/351

**Comment by pnachum** [comment]
I see. That does help.

I wonder if maybe it should be possible to access props through `modState`. Something like 
`modState_P( (State, Props) => State )`

That would be similar to one of the overloads of React's `setState` https://facebook.github.io/react/docs/react-component.html#setstate

**Comment by japgolly** [comment]
Oh damn, that `setState` overload didn't exist before. :(
Anyway, what you've already got is the recommended way. Just one small nitpick... I'd change it to:
```scala
  def increment: Callback =
    bs.props.flatMap(incrementAmount => bs.modState(_ + incrementAmount))
```
The empty `()` usually signifies the presence of side-effects in Scala, where as the above function is pure. In fact you could even change it to `val increment: Callback` without affecting behaviour.

**Comment by japgolly** [comment]
Created new issue for this: #432
