### ISSUE TITLE
JS error on upgrade past 1.0.0

### ISSUE THREAD

**Issue by richbirch** [japgolly/scalajs-react#425]
Firstly I'd like to say a big thanks for giving us this awesome project. It's been a pleasure to use.

I'm trying to upgrade from v1.0.0 in order to not drop behind too far. Unfortunately any version from 1.0.1 onwards gives me the JS below.

I appreciate you probably need more info from me so please ask and I'll provide. In the meantime if you've got any thoughts as to what may have changed to cause this error then that would be awesome. 

Many thanks
Rich

```
ViaReactComponent.scala:213 Uncaught TypeError: Cannot read property 'Component' of undefined
    at $c_Ljapgolly_scalajs_react_component_builder_ViaReactComponent$.init___ (ViaReactComponent.scala:213)
    at $m_Ljapgolly_scalajs_react_component_builder_ViaReactComponent$ (ViaReactComponent.scala:11)
    at $c_Ljapgolly_scalajs_react_component_builder_Builder$Step4.build__Ljapgolly_scalajs_react_CtorType$Summoner__Ljapgolly_scalajs_react_component_JsBaseComponentTemplate$ComponentWithRoot (Builder.scala:349)
    at $c_Ljapgolly_scalajs_react_extra_router_Router$.apply__Ljapgolly_scalajs_react_extra_router_BaseUrl__Ljapgolly_scalajs_react_extra_router_RouterConfig__Ljapgolly_scalajs_react_component_JsBaseComponentTemplate$ComponentWithRoot (Router.scala:13)
    at $c_Ldrt_client_SPAMain$.main__V (SPAMain.scala:117)
    at $c_Ldrt_client_SPAMain$.$$js$exported$meth$main__O (SPAMain.scala:106)
    at $c_Ldrt_client_SPAMain$.main (SPAMain.scala:106)
    at scalajsbundler-fastOptJS-launcher.js:1
$c_Ljapgolly_scalajs_react_component_builder_ViaReactComponent$.init___ @ ViaReactComponent.scala:213
$m_Ljapgolly_scalajs_react_component_builder_ViaReactComponent$ @ ViaReactComponent.scala:11
$c_Ljapgolly_scalajs_react_component_builder_Builder$Step4.build__Ljapgolly_scalajs_react_CtorType$Summoner__Ljapgolly_scalajs_react_component_JsBaseComponentTemplate$ComponentWithRoot @ Builder.scala:349
$c_Ljapgolly_scalajs_react_extra_router_Router$.apply__Ljapgolly_scalajs_react_extra_router_BaseUrl__Ljapgolly_scalajs_react_extra_router_RouterConfig__Ljapgolly_scalajs_react_component_JsBaseComponentTemplate$ComponentWithRoot @ Router.scala:13
$c_Ldrt_client_SPAMain$.main__V @ SPAMain.scala:117
$c_Ldrt_client_SPAMain$.$$js$exported$meth$main__O @ SPAMain.scala:106
$c_Ldrt_client_SPAMain$.main @ SPAMain.scala:106
```

**Comment by japgolly** [comment]
> Firstly I'd like to say a big thanks for giving us this awesome project. It's been a pleasure to use.

Thanks for saying so! I'm always happy to hear that users are happy :)

As to the error, nope, I've never seen that before. Looking at [the code](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/builder/ViaReactComponent.scala#L213) though, it seems that `React.Component` is `undefined` in your environment. Just type `React.Component` into your browser's JS console if it's undefined you know that you've got a problem with your React dependencies (and not this lib, thankfully).

**Comment by richbirch** [comment]
Thanks so much for your swift response. I'll try to delve deeper now you've given me a good pointer

**Comment by richbirch** [comment]
So we've typed React.Component into the console and it seems it does exist:

```
ƒ ReactComponent(props, context, updater) {
	  this.props = props;
	  this.context = context;
	  this.refs = emptyObject;
	  // We initialize the default updater but the real one gets injected by the
```

Does that mean it's not a react dep? I'm not sure where to go from here. If you have any more ideas on how to further diagnose it then I'd be very grateful.

**Comment by richbirch** [comment]
Solved it!

We were using version 0.6.0 of sbt-web-scalajs-bundler, and upgrading to 0.9.0 has resolved the issue. I'm guessing it was due to an ancient version of webpack it was using, but who knows?

Thanks for your quick response. Keep up the good work!
