### ISSUE TITLE
Using react-handsontable via JSComponent

### ISSUE THREAD

**Issue by richbirch** [japgolly/scalajs-react#427]
Hi

Once again thanks for providing us with this fantastic tool!

I'm trying to figure out how to use a 3rd party react component, namely handsontable (https://github.com/handsontable/react-handsontable).

I've been following the guide interop guide (https://github.com/japgolly/scalajs-react/blob/master/doc/INTEROP.md) and have the following code for a HotTable component:

```
object HotTable {
  @JSImport("react-handsontable", "HotTable")
  @js.native
  object RawComponent extends js.Object

  @js.native
  trait Props extends js.Object {
    var data: Seq[Seq[String]] = js.native
  }

  def props(data: Seq[Seq[String]]): Props = {
    val p = (new js.Object).asInstanceOf[Props]
    p.data = data
    p
  }

  val component = JsComponent[Props, Children.None, Null](RawComponent)
}

```

But upon trying to use it:

```
<.div(HotTable.component(HotTable.props(Seq(Seq("yeah"))))())
```

I get a js error:

> Uncaught TypeError: Cannot read property 'ctor__Ljapgolly_scalajs_react_CtorType' of null
>     at $c_Ldrt_client_components_TerminalContentComponent$Backend.render__Ldrt_client_components_TerminalContentComponent$Props__Ldrt_client_components_TerminalContentComponent$State__Ljapgolly_scalajs_react_vdom_TagOf (Generic.scala:13)
>     at TerminalContentComponent.scala:194
>     at $c_sjsr_AnonFunction1.apply__O__O (AnonFunctions.scala:15)
>     at ViaReactComponent.scala:256
>     at $c_sjsr_AnonFunction1.apply__O__O (AnonFunctions.scala:15)
>     at Object.<anonymous> (ViaReactComponent.scala:252)
>     at ReactCompositeComponent.js:796
>     at measureLifeCyclePerf (ReactCompositeComponent.js:75)
>     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
>     at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)

At this point I'm a little stuck. Any pointers as to where I'm going wrong would be awesome.

Thanks

**Comment by japgolly** [comment]
Yeah this is one thing that jumps out at me, this line:
```scala
    var data: Seq[Seq[String]] = js.native
```

The `Props` you're defining here is tagged with `@js.native` and needs to represent HotTable's JS props. I'm pretty sure they not using `scala.Seq` :laughing: It probably needs to be `js.Array[js.Array[String]]` I'd imagine. Try changing it to that (look up the hottable docs to confirm), change the `def props` helper function to convert from Scala to JS and then give that a try.

**Comment by richbirch** [comment]
Thanks. You may have guessed by now that I don't really know what I'm doing :)

I've updated to the following:

```
object HotTable {

//  @JSImport("react-handsontable", "HotTable")
  @JSName("HotTable")
  @js.native
  object RawComponent extends js.Object

  @js.native
  trait Props extends js.Object {
    var data: js.Array[js.Array[String]] = js.native
    var colHeaders: Boolean = js.native
    var rowHeaders: Boolean = js.native
  }

  def props(data: Seq[Seq[String]]): Props = {
    val p = (new js.Object).asInstanceOf[Props]
    import js.JSConverters._
    p.data = data.map(_.toJSArray).toJSArray
    p.colHeaders = true
    p.rowHeaders = true
    p
  }

  val component = JsComponent[Props, Children.None, Null](RawComponent)
}
```

I still get the same error unfortunately. There are a couple of things that I'm just not sure about:

1. whether to use JSName or JSImport. I'm using scalajs-bundler for the npm modules. I *think* that means I can just use JSName, but I haven't really been able to figure it out for sure.

2. when I use the component, should I be adding the extra pair of parenthesis at the end? It seems to be happy with either, ie
`HotTable.component(HotTable.props(Seq(Seq("yeah"))))`
or
`HotTable.component(HotTable.props(Seq(Seq("yeah"))))()`

I feel like I need to try an extremely simple react component just to see if I can get anything working at all. So far I've failed at using any 3rd party react component and it's just not clear to me what I'm doing wrong.

As always, any help/pointers would be awesome

Thanks
Rich

**Comment by richbirch** [comment]
We just tried another data table component: 

https://github.com/nadbm/react-datasheet

With this one we get:

> $c_jl_AssertionError {s$1: "assertion failed: Invalid JsComponent: undefined", e$1: null, stackTrace$1: null, stackdata: $c_jl_AssertionError, 

We managed to get ReactCollapse working so we're just wondering now if there are certain components that just won't function with scalajs / scalajs-react. Do you know if this could be the case?

Do you have any tips on how to go about debugging this stuff? It's a bit of a black box to us at the mo.

Cheers
Rich

**Comment by richbirch** [comment]
Stop press!

We figured it out after a lot of unpicking. We just needed to change the JSImport line to name the export as the default, ie JSImport.Default:

`@JSImport("react-handsontable", JSImport.Default)`

Phew. Massive relief. Feels like a whole new world has now opened up to us!

Thanks for the earlier reply
Rich

**Comment by japgolly** [comment]
Glad it worked out!

You know, in those cases I would've expected [this assertion](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/Js.scala#L10) to trigger and give you a proper warning that you've got an invalid component instead of an NPE.

**Comment by japgolly** [comment]
Oh I see that it triggered later in your comments. I wonder why not in the first case. Plus it would be nice to have a friendlier error message like "Please ensure that you're @JsImport whatever-whatever..." I'll open an issue for it.

**Comment by richbirch** [comment]
Fantastic. Hopefully these issues will help guide others to get it working in future.

Have a great New Year!
