### ISSUE TITLE
React rerenders on prop change (removes from DOM and adds it back in)

### ISSUE THREAD

**Issue by vangogh500** [japgolly/scalajs-react#429]
Hi so I don't know if anyone else has run into this problem but I'm trying to create a progress bar with css animations.

Here is the code:
```scala
case class Props(percentage: String)

def component = ScalaComponent.builder[Props]("Progress")
    .renderP { P =>
      val width_danger = Math.min(P.percentage, 33)
      val width_warning = Math.min(Math.max(P.percentage - 33, 0), 33)
      val width_success = Math.min(Math.max(P.percentage - 66, 0), 34)
      <.div(
        Attr("className") := "progress",
        <.div(
          Attr("className") := "progress-bar bg-danger",
          Attr("role") := "progressbar",
          Attr("style") := js.Dictionary("width" -> (width_danger + "%")).asInstanceOf[js.Object],
          Attr("aria-valuenow") := width_danger,
          Attr("aria-valuemin") := 0,
          Attr("aria-valuemax") := 100),
        <.div(Attr("className") := "progress-bar bg-warning",
          Attr("role") := "progressbar",
          Attr("style") := js.Dictionary("width" -> (width_warning + "%")).asInstanceOf[js.Object],
          Attr("aria-valuenow") := width_warning,
          Attr("aria-valuemin") := 0,
          Attr("aria-valuemax") := 100),
        <.div(Attr("className") := "progress-bar bg-success",
          Attr("role") := "progressbar",
          Attr("style") := js.Dictionary("width" -> (width_success + "%")).asInstanceOf[js.Object],
          Attr("aria-valuenow") := width_success,
          Attr("aria-valuemin") := 0,
          Attr("aria-valuemax") := 100)
      )
    }.build
```

And CSS:
```css
.progress-bar {
  transition: width 0.7s ease-in-out;
}
```

When I go on the browser inspector and manually change the widths, the animation works. But when I change the props via code it will not. I am guessing because the code removes the component and adds everything back in every rerender. Which I don't think is supposed to be the behavior of react.

EDIT: Figured out that the whole form component that was used to change the props is remounting everything in it every time the state changes. Is this a result of how this library was created or is there a way to get around this issue?

**Comment by japgolly** [comment]
Ah yep. To clarify: React itself uses reference equality on components so if you recreate (re-build) a component more than once, even though the code and content is exactly the same, React will consider them different components, unmount the current one, then mount the new one.
