### ISSUE TITLE
Add ^.display.grid and related attributes

### ISSUE THREAD

**Issue by joan38** [japgolly/scalajs-react#436]
Missing: `^.display.grid`, workaround: `^.display := "grid"`
Missing: `^.gridTemplateColumns`, workaround: `Style("grid-template-columns") := "1fr 0fr 0fr 0fr"`
Missing: `^. gridTemplateRows`, workaround: `Style("grid-template-rows") := "1fr 0fr 0fr 0fr"`
Missing: `^. gridColumnStart`, workaround: `Style("grid-column-start") := "2"`
Missing: `^. gridColumnEnd`, workaround: `Style("grid-column-end") := "five"`
Missing: `^. gridRowStart`, workaround: `Style("grid-row-start") := "row1-start"`
Missing: `^. gridRowEnd`, workaround: `Style("grid-row-end") := "3"`
Missing: `^. gridColumn`, workaround: `Style("grid-column") := "3 / span 2"`
Missing: `^. gridRow`, workaround: `Style("grid-row") := "third-line / 4"`
Missing: `^. gridArea`, workaround: `Style("grid-area") := "main"`
Missing: `^. gridTemplateAreas`, workaround: `Style("grid-template-areas") := "main"`
Missing: `^. justifySelf`, workaround: `Style("justify-self") := "start"`
Missing: `^. gridTemplate`, workaround: `Style("grid-template") := ""`
Missing: `^. alignSelf`, workaround: `Style("align-self") := "start"`
Missing: `^. gridColumnGap`, workaround: `Style("grid-column-gap") := "100px 50px 100px"`
Missing: `^. gridRowGap`, workaround: `Style("grid-row-gap") := "10px"`
Missing: `^. gridGap`, workaround: `Style("grid-gap") := "10px 15px"`
Missing: `^. justifyItems`, workaround: `Style("justify-items") := "center"`
Source: https://css-tricks.com/snippets/css/complete-guide-grid/

I'm wondering something, it sounds like we are doing a hard copy from what we have in scalacss, so can't we ditch all the CSS stuff from scalajs-react and replace it with scalacss? Is it possible to define scalacss attributs directly in the tags without creating an object extending StyleSheet.Inline?

**Comment by japgolly** [comment]
This would be a pretty easy PR if you have time.

As to the overlap with styles here and in ScalaCSS, to make a long story short, that was the plan but ScalaCSS needs a rewrite first. If I can get enough money through Patreon or maybe some one-off bounty to do so, I would consider taking a month or two off work later this year to dedicate to the effort. (Unlikely though)

**Comment by SkyWriter** [comment]
David, could you do a quick review and tell me if I'm going in the right direction at all with this pull request? Thanks and have a great weekend!

**Comment by japgolly** [comment]
PR merged
