### ISSUE TITLE
ref attrribute for react components

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalajs-react#44]
Hi , 
  I am trying to port the following jsx code 
https://github.com/callemall/material-ui/blob/master/src/js/flat-button.jsx

``` javascript
   <Ripple ref="ripple" className="mui-flat-button-ripple" />
        <Ripple className="mui-flat-button-focus-ripple" />
```

how can i achieve this ( ref attributes on components ) in scala-js react ?

Thank You
Chandra

**Comment by jclyons** [comment]
Hi JapGolly,

Still not clear on how to create a ref to component. Can you maybe give an example of this?

**Comment by japgolly** [comment]
@jclyons Glad to hear it.
