### ISSUE TITLE
Add a ReaderT CallbackTo

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#442]
ReaderT CallbackTo aka Kliesli CallbackTo

What to call this? `ReaderCallback`, `CallbackReader`, `CallbackFn` (yuk)?

**Comment by cquiroz** [comment]
Cool, are you going to use `Kliesli` from cats, scalaz or your own?

Maybe call it `Kallback` 😄

**Comment by japgolly** [comment]
lol @ `Kallback` :laughing: 

Nah I decided to call it `CallbackKleisli`, `Kleisli` because `Reader` and `Fn` are ambiguous, eg. `CallbackReader` might sound like something that reads callbacks. As anyone who reads `Kleisli` will either know exactly what it is, or think what the hell is that and read the type signature and eventually move into the former category.

**Comment by japgolly** [comment]
Oh @cquiroz, and no, I'm not using anything from Scalaz or Cats because I don't want `core` or `extra` to depend on them at all. They're 100% optional.

Ah! Which reminds me, I need to add type-classes to the Scalaz/Cats modules for this before I merge.
