### ISSUE TITLE
Reusability example breaks demo site

### ISSUE THREAD

**Issue by Tamriel** [japgolly/scalajs-react#459]
The example [https://japgolly.github.io/scalajs-react/#examples/reusability](url) shows just a single button (no nav bar anymore) and throws this error to the console:

```
react-dom.production.min.js:162 TypeError: 
Failed to execute 'replaceChild' on 'Node': parameter 1 is not of type 'Node'.
    at ghpages.js:548
    at C.G (ghpages.js:530)
```

**Comment by japgolly** [comment]
Fixed. Thanks for reporting
