### ISSUE TITLE
React.js v16.3.0: New lifecycles and context API

### ISSUE THREAD

**Issue by ngbinh** [japgolly/scalajs-react#462]
https://reactjs.org/blog/2018/03/29/react-v-16-3.html

Looks like we need some changes on scala.js react

**Comment by japgolly** [comment]
> Looks like we need some changes

`scalajs.js.Dynamic`, what's the problem? :trollface:

**Comment by Myrddin27** [comment]
@japgolly I wouldn't mind trying to start a PR for this update, but I would definitely require some pointing in the right direction.

**Comment by cquiroz** [comment]
I could contribute too

**Comment by japgolly** [comment]
Hi there. Yes! I'm more than happy to accept contributions and happy to guide them in the right direction. You'll just have to understand that over the next month I'm not going to have much time to spend on this so prepare your expectations for delays in feedback. I may not even have internet for the first two weeks of June. But after around 4 weeks from now I should be able to spend time on this and plan to give scalajs-react lots of attention and get a new release out with React 16.3 support. You're more than welcome to get the ball rolling on it now. :)

**Comment by japgolly** [comment]
FYI my work on this begins now. Watch this space....

**Comment by japgolly** [comment]
Also if you made any progress now's the time to share :)

**Comment by japgolly** [comment]
* [ ] Context API
  -- https://reactjs.org/docs/context.html

* [ ] `React.createRef()`. Maybe weaker than what we already have.
  -- https://reactjs.org/docs/refs-and-the-dom.html

* [ ] `React.forwardRef`
  -- https://reactjs.org/docs/forwarding-refs.html

* [ ] Lifecycle changes -- https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
  * Deprecate
    * componentWillMount
    * componentWillReceiveProps
    * componentWillUpdate
  * Add
    * getDerivedStateFromProps
    * getSnapshotBeforeUpdate

* [ ] `StrictMode`
  -- https://reactjs.org/docs/strict-mode.html

**Comment by japgolly** [comment]
Mostly closed via #480 . Will create a separate issue for `React.forwardRef`
