### ISSUE TITLE
Add an error-catching component to extra

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#463]
Already created and using for `gh-pages`:

https://github.com/japgolly/scalajs-react/blob/master/gh-pages/src/main/scala/ghpages/examples/util/ErrorHandler.scala

I think this would be quite convenient.

**Comment by nafg** [comment]
What's a use case for CallbackTo[VdomNode]?

**Comment by japgolly** [comment]
Maybe it sends log event to server

**Comment by nafg** [comment]
https://reactjs.org/docs/react-component.html#componentdidcatch now says

> **Note**
> In the event of an error, you can render a fallback UI with `componentDidCatch()` by calling `setState`, but this will be deprecated in a future release. Use `static getDerivedStateFromError()` to handle fallback rendering instead.

See https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror

**Comment by japgolly** [comment]
No point. This isn't where this lib should be building on top of React.
