### ISSUE TITLE
getDOMNode can throw exceptions

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#464]
If the component isn't mounted, calling `.getDOMNode` causes React to throw an exception. One wouldn't deliberately call `.getDOMNode` on an unmounted component but a way in which it can happen that looks safe is, calling it from a `setState` callback: a parent `setState` can cause the component to legitimately unmount.

I'm very unhappy about this but the right thing to do is make `.getDOMNode` return an `Option` or `FailureReason \/ ?`. Types should reflect reality so it's good in that sense but we just changed backwards-compatibility on this method in the last release. Now it will have to change again :(

Maybe an opaque type representing `Unmounted | TextNode | Element` would be best. We could get rid of the implicit methods, provide a better API and make it easier to incorporate future changes here.

**Comment by cquiroz** [comment]
I guess `A \/ B` would leave us tied to scalaz which I wouldn’t want in `scalajs-react`. If you go down that route could you  use `Either` instead

**Comment by japgolly** [comment]
Ah I know I thought using `\/` above but yeah I would implement using `Either`. The `core` module will remain dependency free.

**Comment by japgolly** [comment]
Closed via #473
