### ISSUE TITLE
Automatic component name

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#470]
Now that `sourcecode` is already a dependency anyway, what do you think of making the component name string optional? I've been using something like the following in a bunch of projects for a while:

```scala
object Component {
  def apply[P](implicit name: sourcecode.FullName): Builder.Step1[P] =
    ScalaComponent.builder[P](name.value.stripSuffix(".component"))
}
```

That way, in the normal pattern of

```scala
object ComponentName {
  val component = ...
}
```

the component would be named ComponentName, but if the val used some other name, let's say helperComponent, then it would be named ComponentName.helperComponent.

Of course, it would look a bit different if it were a seamless part of the built in API, and the assumption about convention might be a bit less safe to make.

Thoughts?

**Comment by japgolly** [comment]
That's an awesome idea! Only concern is how to add it without breaking backwards compatibility. An overload looks ambiguous

**Comment by nafg** [comment]
Not sure what you mean by ambiguous, but it would work to overload `EntryPoint.apply`. Testing in ammonite:

```scala
@ implicit val i: Int = 99 
i: Int = 99

@ object O { def apply[A](implicit j: Int) = j; def apply[A](name: String) = name } 
defined object O

@ O[Boolean] 
res4: Int = 99

@ O[Boolean]("name") 
res5: String = "name"
```

Alternatively, you could have a helper in `japgolly.scalajs.react.component.Scala` that delegates to the existing `builder.apply`, either a nullary apply, so while `ScalaComponent.builder[P]("name")` will continue to work, you would also be able to write just `ScalaComponent[P]`

**Comment by nafg** [comment]
Another option might be to do something like this, if it works:

```scala
sealed class ComponentName(val name: String)
object ComponentName {
  implicit def fromSourceCodeFullName(implicit fullName: FullName) = new ComponentName(fullName.value)
  implicit class explicitString(private val self: String) extends ComponentName(self)
}
```

and then just _change_ the existing EntryPoint.apply method, so that instead of taking a string, it takes an implicit ComponentName. If you pass a string explicitly, as in current usage, it will use the implicit class to convert it to a ComponentName (you could use an implicit def conversion instead if you prefer, since we're not adding extension methods). And if you leave off the parameter, it will run implicit search which will trigger implicit search for a FullName.

The only thing I'm not sure of is where the FullName would be materialized. It's possible it would just generate a FullName for `ComponentName.fromSourceCodeFullName`, rendering it useless.

**Comment by nafg** [comment]
BTW I should mention that sourcecode is not strictly necessary for this feature -- reflection (getClass.getName) works as well. Obviously sourcecode has advantages, just wanted to mention that reflection works too.

**Comment by nafg** [comment]
Actually, one advantage of reflection is that you can define it in a base class. For instance, one pattern I use sometimes when I need a "generic" component, is to have a class with a type parameter, and concrete objects for each version. For instance,

```scala
class FancyTypedSelect[ItemType] {
  case class Props(items: Seq[ItemType])
   val component = ...
}

object PersonEditor {
  object InsurancePlanSelect extends FancyTypedSelect[InsurancePlan]
  ...
        <.div(
          InsurancePlanSelect.component(InsurancePlanSelect.Props(insurancePlans))
        )
  ...
}
```

Using reflection, the component name would be InsurancePlanSelect. Using an implicit sourcecode.FullName, without doing any extra work, the name would be FancyTypedSelect. (With some extra work it would probably be possible to get the subclass name.)

I'm not sure which behavior is "better" though.

**Comment by japgolly** [comment]
Interesting... In think we both agree that it would be nice to have an automatic default name generated (thanks for confirming that Scala doesn't consider the overloads ambiguous btw). So I think the remaining questions are:

1. Use sourcecode or reflection.
2. Argument as string or dedicated type.
3. Sensible transformation on derived name (eg. stripping `.component` as a suffix.
4. How would one provide their own automatic derivation and/or transformation logic.

I have no answers cos I haven't thought about this in detail yet but my current thoughts on the above are:

1. Reflection means that the SJS class name transformation flag will have an effect. That's probably a very good thing. If I decide to zap all class names in a prod build I'd probably want the display names of components zapped too.
2. I think this will depend on 4 in that a dedicated type might be necessary for implicit customisation.
3. I'd use a regex and include a few more times in there
4. This ability is quite important I think and the hardest. I guess the Scala way is to give it a type, provide a default implicit (or default parameter value if macros necessitate it), then allow the user to define their own implicit. Which is kind of shit cos the user has to manually import their implicit all the time and if they forget, the library default will be silently used. Any thoughts on how to do better?

**Comment by nafg** [comment]
You could have the API be in a trait with a default object that extends it.
If you import that object you get the default behavior. If you want
different behavior, you extend the the trait, override whatever, and import
your object instead of the default object.

**Comment by japgolly** [comment]
* be able to disable this by compiler flag (like SJS 1.0 flags in 0.6)
* maybe be able to specify the format by compiler flag too
