### ISSUE TITLE
Passing scalacss as props to component

### ISSUE THREAD

**Issue by vangogh500** [japgolly/scalajs-react#472]
Was trying to set up a system where I could pass inline styles as props to a component. Is this possible?

`ScalaComponent.builder[Seq[scalacss.internal.StyleA]]("PrimaryNavBar")
   .render_P(styles => <.div(styles:_*, "Hello world"))...
`

I get the following error:

type mismatch;
[error]  found   : Seq[scalacss.internal.StyleA]
[error]  required: Seq[japgolly.scalajs.react.vdom.TagMod]

**Comment by dvkndn** [comment]
I think the issue is not about the type of prop, but about the way you are using it: `<.div(styles:_*`

`styles` here is not something that you can pass directly to a tag as a tag mod. You need to use its `htmlClass` I think.

Something like <.div(^.cls := styles.htmlClass)`

**Comment by japgolly** [comment]
`.render_P(styles => <.div(styles:_*, "Hello world"))` isn't valid Scala. Try one of the following:

* `.render_P(styles => <.div("Hello world", styles:_*))`
* `.render_P(styles => <.div(styles:_*)("Hello world"))`

**Comment by rpiaggio** [comment]
@vangogh500 Maybe this is what you are looking for?  https://japgolly.github.io/scalacss/book/ext/react.html

**Comment by japgolly** [comment]
Assuming closed for reasons above. Feel free to reopen if necessary.
