### ISSUE TITLE
JsComponent should accept a forwardRef

### ISSUE THREAD

**Issue by quanganhtran** [japgolly/scalajs-react#474]
The background is very similar to facebook/react#12453

scalajs-react component check is not sufficient:
https://github.com/japgolly/scalajs-react/blob/8362b2b62d98bcc9f4ef63a78bd0adf0862f5404/core/src/main/scala/japgolly/scalajs/react/component/InspectRaw.scala#L11-L15

**Comment by japgolly** [comment]
Thanks. Use `JsComponent.force` in the meantime,

**Comment by japgolly** [comment]
Fixed in a906e9754372a782af936977ded59a5aaa5e32a2
