### ISSUE TITLE
Include debounce functionality?

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#487]
Thoughts on including a built in debounce function?

I have this code lying around, not sure how bulletproof it is. It can debounce functions, Callbacks, and Futures.

```scala
object Debounce {
  private val DefaultDuration = 250.milli

  def apply[A](duration: FiniteDuration = DefaultDuration)(f: A => Unit): A => Unit = {
    var timeout = Option.empty[SetTimeoutHandle]
    (a: A) => {
      def run(): Unit = {
        timeout = None
        f(a)
      }

      timeout.foreach(timers.clearTimeout)
      timeout = Some(timers.setTimeout(duration)(run()))
    }
  }

  def callback[A](duration: FiniteDuration = DefaultDuration)(f: A => Callback): A => Callback =
    apply[A](duration)(f.andThen(_.runNow())).andThen(_ => Callback.empty)

  def future[A, B](duration: FiniteDuration = DefaultDuration)(f: A => Future[B])
                  (implicit executionContext: ExecutionContext): A => Future[B] = {
    var timeout = Option.empty[SetTimeoutHandle]
    var invocationNum = 0

    (a: A) => {
      invocationNum += 1
      val promise = Promise[B]

      def run(): Unit = {
        timeout = None
        val curInvocationNum = invocationNum
        f(a).onComplete { t =>
          if (invocationNum == curInvocationNum)
            promise.complete(t)
        }
      }

      timeout.foreach(timers.clearTimeout)
      timeout = Some(timers.setTimeout(duration)(run()))

      promise.future
    }
  }
}
```

**Comment by japgolly** [comment]
Hey @nafg, yeah I'm cool to have a debounce method on `CallbackTo` :+1:

If you're going to PR I'd just say, 1) please no implicit duration, and 2) just include some unit tests pls.

**Comment by japgolly** [comment]
Closed via #742. I didn't end up using your code but thanks anyway.

**Comment by nafg** [comment]
I didn't understand the implementation, but in general rate limiting and debouncing are not the same thing.

Rate limiting usually means throttling, meaning that a subsequent event that occurs too soon is deferred or dropped. One example of when this is useful is to avoid polling a server too frequently.

Debouncing means each event is delayed for a certain amount of time to ensure it isn't superseded by a subsequent one. If not then the event goes through. If it is superseded, the first event is dropped and the superseding one is subject to the same behavior. Debouncing is necessary any time you want to show results of the user's changes in as real time as possible but to respond to each and every change would be too expensive. For example, in an autocomplete dropdown you want to wait until the user has stopped typing for at least a fraction of a second. Otherwise (if you update on every key typed) you're just doing work that the user will never even benefit from. But you absolutely, positively don't want to throw away the latest version of what they typed just because they typed too soon.

Can you clarify which behavior rateLimit has?

**Comment by japgolly** [comment]
Thanks for the explanation. To be honest I was thinking debouncing and rate-limiting are the same thing so thanks for your example use case which demonstrates the different quite nicely. What I implemented is definitaly rate-limiting in that judgement, invocation and rejection all happen immediately when a callback is fired. The rejection case is [here](https://github.com/japgolly/scalajs-react/pull/742/files#diff-8f04f8078a6cc098834c7e7273e4f003R24), showing that if the sliding window is full, the (latest) calls are rejected until the space occurs in the sliding window again. Definately not what you would want with async autocomplete as if the user types 10 times, the first half could go through and the second half would be dropped. Will have to tackle this again next release (and study your implementation a bit more closely).

**Comment by japgolly** [comment]
Ok cool, I added proper debounce this time around and used your snippet too so thanks for that. I wouldn't have thought to add `invocationNum` to the async version so yeah, your snippet was a big help. I'll release 1.7.4 with this feature in it today.

**Comment by tomasherman** [comment]
Hello, im trying to use this feature with an material-ui autocomplete `onInputChange` api, which expects a function that returns unit. 

I have this code to get the callback into required shape:
```scala

      val onInputChange = (_: Any, input: String) => {
        if(input != null && input != "") {
          StateManagementClient.suggestSecurity(input).debounce(Duration.ofSeconds(5)).flatMap(state.zoomStateL(State.suggestions).setState(_).asAsyncCallback).runNow()
        }
      }
```

But it's not working ... instead of just processing the latest event, all events are processed with the delay provided - this is somewhat obvious as for new change of the input, new code mentioned above is started. But im not sure how to combine these two features together. Any guidance would be very appreciated. Thanks! :)
