### ISSUE TITLE
Use raw.React.Ref in VdomTag

### ISSUE THREAD

**Issue by dvkndn** [japgolly/scalajs-react#500]
I'm trying to use [`react-text-mask`](https://github.com/text-mask/text-mask/tree/master/react) which has the following usage:

```jsx
<MaskedInput
  render={(ref, props) => (
    <input ref={ref} {...props} />
  )}
/>
```

My question is how can I write that `ref` assignment in ScalaJS React?

So far, I think the type of `ref` is `raw.React.Ref` (it's actually `raw.React.RefFn` in this case, but I think it's better to use just `Ref`?)

However, I can't figure out how to use that ref in a VdomTag:

```scala
private def rawRender(ref: raw.React.Ref): React.Element = {
  <.input(???).rawElement
}
```

**Comment by dvkndn** [comment]
One thing I can do is using `VdomAttr`. Not sure if this is the best way since it seems to accept everything:

```scala
private def rawRender(ref: raw.React.Ref): React.Element = {
  <.input(VdomAttr("ref") := ref).rawElement
}
```

**Comment by japgolly** [comment]
Hey. Wrap the raw Ref use `Ref.fromJs` or `Ref.forwardedFromJs` (maybe there should be a `Ref.fromJsFn` too?), then use `.withRef(r)`

**Comment by japgolly** [comment]
Oh wait, you're trying to pass a Scala ref to JS, not the other way around? In that case use call `.raw` on the ref and pass that.

**Comment by japgolly** [comment]
This question is better asked in Gitter or StackOverflow though so closing. If you find there's something unsupported that needs a library change pls create an issue or reopen this and we can go from there
