### ISSUE TITLE
Reusability out of Props/State

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#501]
I have a virtualized table component, which only displays n rows out of a large amount of rows, only showing what's visible on the scroll window

I want to add `Reusability` but that ends up comparing all rows. I haven't found a way to have a function `P => Reusability[P]` or `S => Reusability[S]` to accomplish that.

Is there a way? If not, do you think it could be added?

**Comment by japgolly** [comment]
Two ways come to mind.

1) Create components for each row and give them their own reusability, then have the parent do quick reusability checks like reference eq and row count without checking content. (I've done this in a big table and it works well)

2) Create a Reusability fn by hand and put whatever logic in there you need or think is appropriate. You'll have to take much more care. This is how they do it in JS.

**Comment by japgolly** [comment]
This question is better asked on StackOverflow or Gitter so I'll close. We can continue discussing this one here though. And of course, any lib changes needed and re can reopen.
