### ISSUE TITLE
fontawesome webjar intergation 

### ISSUE THREAD

**Issue by ashu2012** [japgolly/scalajs-react#502]
Hi,

I am trying to add fontawesome webjar with scalajs .jar. I dom't want to add as class style part but as svg icon in vdome node. Kind of struggling as not able to find  documents or example. 

fontawesome that i am integrating:-
https://github.com/fdietze/scala-js-fontawesome

**Comment by ashu2012** [comment]
hi, i even tried:-<.i(^.cls:= fontAwesome.freeSolid.faHome.iconName)(fontAwesome.freeSolid.faHome.icon)

but not getting any success

**Comment by japgolly** [comment]
I do font-awesome like this `<.i(^.cls:= "blah")`. Not sure about that FontAwesome API.
This question is better for the Gitter channel or StackOverflow.
