### ISSUE TITLE
Integrate with Cats' IO (take 2)

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalajs-react#503]
I'd like to revive the [attempt](https://github.com/japgolly/scalajs-react/pull/361) at providing interop with Cats' effect type IO (possibly SyncIO) as an optional replacement for Callback.

See also some recent discussion about this in [Gitter](https://gitter.im/japgolly/scalajs-react?at=5b6cc33f26e68560fdd3f5f9).

My project already has various conversions between Callback/IO but they are somewhat limited as IO can handle asynchronous effects.  Specifically, there exists a transformation from `CallbackTo[A] -> IO[A]` as `CallbackTo` is guaranteed to be synchronous.  However, one cannot safely go from `IO[A] -> CallbackTo[A]` as `IO` could have asynchronous effects.  

One thing that has changed since the introduction of that PR is the addition of `SyncIO` which limits effects to synchronous types.  With that, we have the following transformations:

```scala
IO[Unit] -> Callback
SyncIO[A] -> CallbackTo[A]
CallbackTo[A] -> IO[A]
```

As discussed in Gitter/PR, the current progress appears to be:

* defined an Effect type for IO
* got modState working with IO using `Generic.MountedRoot[IO, P, S]` vs `BackendScope` which is fixed on Callback

However there are lots of places in the code that appear hard-coded on Callback.  The biggest hurdles that I encounter:

* [event handlers ](https://github.com/japgolly/scalajs-react/blob/034ab4dd023571453f9925eb2d78446985e085af/core/src/main/scala/japgolly/scalajs/react/vdom/Attr.scala#L59)(`-->`, `==>`).  
  * Somewhat tangential, but as the `DomCallbackResult` implies, I don't really see a reason for these to take an A as you can't do anything with the return type.  I'd rather see the caller forced to `.void` callback
* the `Effect.extract` methods assumes a synchronous response.  I honestly am having trouble understanding how/where this is used and whether A is ever anything but Unit.  Would it be possible to split `Effect` into `Effect` and `SyncEffect` where extract is moved onto the latter type class?

**Comment by japgolly** [comment]
Closing this as it doesn't seem possible.

**Comment by mpilquist** [comment]
Note cats-effect defines SyncIO now, which guarantees synchronous execution - no async boundaries.

**Comment by japgolly** [comment]
Oh cool. Is that coming in cats-effect 2.0 or is it already in 1.x?

**Comment by mpilquist** [comment]
It’s in 1.0.0 and 1.1.0.
