### ISSUE TITLE
React 16.6 & React 16.7

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#504]
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

**Comment by ngbinh** [comment]
https://reactjs.org/blog/2018/12/19/react-v-16-7.html should be straightforward after 16.6 I guess

**Comment by japgolly** [comment]
Yeah, thanks @ngbinh ; should be straightforward.

I was hoping to have this release out by the end of the year but haven't had enough opportunity. Looking at a Jan release instead. For anyone interested you watch the progress on the `series/v1.4.x` branch.

**Comment by japgolly** [comment]
Completed on series/v1.4.x branch
