### ISSUE TITLE
Document how to do SSR with Graal

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#505]

**Comment by japgolly** [comment]
https://twitter.com/japgolly/status/1057029579502608384

This morning on the train: Benchmarking scalajs-react SSR under graalvm.

Warmup = 1000 renders
Benchmark = 100 renders

Graal CE ❤️
```
p50 =   4 ms
p90 =   5 ms
p95 =   5 ms
p98 =  12 ms
p99 =  20 ms
```

Graal EE 💰
```
p50 =   5 ms
p90 =   5 ms
p95 =   6 ms
p98 =  11 ms
p99 =  12 ms
```

**Comment by japgolly** [comment]
https://twitter.com/japgolly/status/1057555386767527936

SSR with scalajs-react and @graalvm:

After a 10,000 render warmup (~30 sec), p99 = 1ms!!

🔥🔥🔥 ONE MILLISECOND! 🔥🔥🔥

Node with a warmup of 0 and 10,000 has p98 of 1ms and curiously, a p99 of 3ms pretty consistently!

**Comment by japgolly** [comment]
Don't forget to expose `hydrate`

**Comment by japgolly** [comment]
* Router in SSR tries to pushState/replaceState
  - let it crash and hide from logs?
  - or, have the router be SSR aware and....?

* need to render after hydration...
  - if window.location.hash is set (because server doesn't consider)
  - if localStorage isn't available and I decide to disable the remember me button

**Comment by quanganhtran** [comment]
Just want to give some support to this issue. I am experimenting with exactly SSR on GraalVM using Scala.js and `scalajs-react`.

My biggest challenges so far is related to cross-compiling data models to use on both Scala and Polyglot JS side. Scala from Java perspective has all its fields set to private, exposing only accessors and mutators, therefore polyglot objects cannot be used by Scala.js code run with Graal.js. I see that you are communicating between the layers using serialized data (with `boopickle`). I am looking for a way to utilize `ProxyObject` to directly use Polyglot objects in JS code.

I am following your repo at [japgolly/scala-graal](https://github.com/japgolly/scala-graal). Would love to see what are your findings!

**Comment by japgolly** [comment]
Hi! Yeah if you could make that work that would be really cool but I don't
think it's possible. You'd need to use reflection and a lot of guessing at
coercion (eg `Some(Some(None)))`) and not too mention that scalajs has its
own structure to represent Scala data.

For me, it's very important that any solution be able to work for any data,
and if it won't there should be a compile time error. I think if you go
down the road you're considering, that you both won't be able to support
all types of data, and you'll run into a lot of runtime errors either
translating or consuming within Graal. That being said you should
definitely try if you're keen, if you were able to prove me wrong that
would be awesome and very interesting. :)

**Comment by tarsa** [comment]
GraalVM 1.0.0-RC15 uses libgraal by default. Maybe that would improve the percentiles (measurements)?

https://www.graalvm.org/docs/release-notes/#10-rc15
> By default, libgraal is now used when running the java launcher or when using the --jvm mode for the language launchers. The libgraal library is a version of the Graal compiler pre-compiled by native-image. In addition to improving startup time, libgraal completely prevents the Graal compiler from interfering with the heap usage and profiles of application code. It has execution properties similar to other native HotSpot compilers such as C1 and C2.

**Comment by japgolly** [comment]
Thanks @tarsa. I still haven't had a chance to re-benchmark but I'll report findings back here when I do.

**Comment by EivydasKoc** [comment]
Any news on this issue? Curently looking into options of implementing React SSR for my existing application

**Comment by japgolly** [comment]
Hey @EivydasKoc. Yeah this has been on my list for ages now. The code itself is fine, and it's even live in production at https://shipreq.com. You can see it at https://github.com/japgolly/scala-graal and jump right in if you're willing to look at the tests and use your imagination. But you might have to use it a lot to understand how it's supposed to work and how the pieces tie together so yeah, I really really should document this. This is has been a good reminder so thanks for the ping. I've got a few things that I need to get done first but I'll make polishing the library a bit more and properly documenting it a priority. Can't promise a time but I'm guessing around 2 weeks.

**Comment by japgolly** [comment]
Argh, I'm such an idiot. A few weeks after the above comment (i.e. August 2020) I created an SSR tutorial and spread it on social media but completely forgot to update this issue and link to it from scalajs-react. Sorry to anyone watching this issue who doesn't follow me who didn't see me share this back then.
