### ISSUE TITLE
usage of ScalaComponent.static fails with compile error japgolly.scalajs.react.ScalaComponent.Component[Unit,Unit,Unit,japgolly.scalajs.react.CtorType.Nullary] does not take parameters

### ISSUE THREAD

**Issue by enijns** [japgolly/scalajs-react#506]
I ran into this issue trying to upgrade scalajs-react from 1.1.1 to 1.3.1:
```scala
package whatever

import japgolly.scalajs.react._
import japgolly.scalajs.react.vdom.all._

object Bug {

  val Fails = ScalaComponent.static("Fails")(div("no"))

  val noo = Fails()
  /**
    * [error]      japgolly.scalajs.react.ScalaComponent.Component[Unit,Unit,Unit,japgolly.scalajs.react.CtorType.Nullary] does not take parameters
    * [error]      L10:  val noo = Fails()
    **/

  val Works = ScalaComponent.builder[Unit]("Works").render_P(_ => div("ok")).build

  val goo = Works()
}
```

**Comment by enijns** [comment]
Router seems to have similar issues:
```scala
japgolly.scalajs.react.extra.router.Router[uz.wm.frontend.FrontendApp.Page] does not take parameters
[error]      L24:    router().renderIntoDOM(document.body)
```

**Comment by cquiroz** [comment]
This could be due to the scala 2.12.7 regression, can you try with 2.12.6?

**Comment by enijns** [comment]
Which regression are you referring to? I will try with 2.12.6 tomorrow...

**Comment by enijns** [comment]
Found it: https://github.com/scala/bug/issues/11174

**Comment by japgolly** [comment]
Indeed. Is Scala regression unfortunately. I'll see if I can find some kind of workaround based of Adriaan's idea but I doubt it will be possible.

**Comment by japgolly** [comment]
@enijns If it's ok with you (probably after you confirm everything's ok on 2.12.6) do you mind we close this issue? I've belatedly raised #507 to track it and inform users coming to check/report the issue,

**Comment by enijns** [comment]
2.12.6 works fine.

Don't waste too much time on this issue, it would be good if this breakage was better documented. But the existence of #507 is good enough for me documentation-wise...
