### ISSUE TITLE
[ATTENTION] Scala 2.12.7 has a regression - Breaks scalajs-react projects

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#507]
Scala bug report: https://github.com/scala/bug/issues/11174

A fix for the regression has been merged into Scala 2.12.8-SNAPSHOT.

Examples: #506

**Comment by japgolly** [comment]
I've not been able to come up with a workaround. :(

**Comment by japgolly** [comment]
Scala 2.12.8 works.
Resolved via 8b515a50

**Comment by FabioPinheiro** [comment]
I think we have the some regression after on the SBT version 1.2.4 or +  
Because the sbt module 'compiler-bridge_2.12' is using Scala 2.12.7

**Comment by japgolly** [comment]
@FabioPinheiro I've experienced it working with SBT 1.2.{6,7,8} using Scala 2.12.8. Are you sure that your build is configured to use Scala 2.12.8?

**Comment by FabioPinheiro** [comment]
Yes I'm using Scala 2.12.8
@japgolly I noticed that this is what happens when using sub modules.

Here I smaller example that I can give an error:
https://github.com/FabioPinheiro/CompilationErrorShowcase

**Comment by FabioPinheiro** [comment]
After all I was using Scala 2.12.7
The problem was that I only defined the Scala version on the root project
Didn't know that I need to define for each sub-module
Thx for the help
