### ISSUE TITLE
modState and Callback with state

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#519]
At the moment `modState` takes a `Callback` as:

`def modState(mod: S => S, callback: Callback): Callback`

However I often want to have the new state on the `Callback`. Could it be possible to have a method with this signature?

`def modState(mod: S => S, callback: S => Callback): Callback`

Where `callback` is called with the new state?

**Comment by japgolly** [comment]
No, unfortunately that's a limitation with React itself.

**Comment by japgolly** [comment]
It's been a few months. I'm assuming lack of reply means solved, please reopen otherwise.
