### ISSUE TITLE
Support for mixins?

### ISSUE THREAD

**Issue by benjaminjackman** [japgolly/scalajs-react#52]
Is there any support for mixins? I am making some behaviour that would cross cut components and mixins would be the perfect fit. I didn't find any mention of it in the docs or code.

I am referring to mixins from here:
http://facebook.github.io/react/docs/reusable-components.html#mixins

**Comment by japgolly** [comment]
Between `.configure` and `.mixinJS` I think we've got this covered. Newer Scala-based mixins are functioning happily in the `extra`  module using `.configure`. You good to close this @benjaminjackman ?

**Comment by benjaminjackman** [comment]
definitely

**Comment by japgolly** [comment]
sweet
