### ISSUE TITLE
Reusability on JsComponents

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#520]
Is there a way to use the `Reusability` concept on a wrapped JS Component?

**Comment by japgolly** [comment]
A JS component of something that's already been created so far as React is
concerned so it can't be further modified to add
shouldComponentUpdate/Reusability. What you can do though is just make a
Scala wrapper and add reusability at that level. If you wait a few days and
use v1.4.0, you can use a "functional" component and React.memo which is
supposedly at a little more lightweight.

**Comment by japgolly** [comment]
It's been a few months. I'm assuming lack of reply means solved, please reopen otherwise.
