### ISSUE TITLE
Error rendering component with React.Suspense

### ISSUE THREAD

**Issue by allantl** [japgolly/scalajs-react#522]
Got an error with `React.Suspense` (React 16.7.0). Am I missing something?

```
import japgolly.scalajs.react._
import japgolly.scalajs.react.vdom.html_<^._
import org.scalajs.dom

object App {

  def main(args: Array[String]): Unit = {

    def body = {
      val main = AsyncCallback
        .pure(<.div(^.color := "#070", "Async load complete."))
        .delayMs(2000)

      React.Suspense(
        fallback = <.div(^.color.red, "Loading..."),
        asyncBody = main
      )
    }

    val Main =
      ScalaComponent
        .builder[Unit]("Main")
        .stateless
        .render_(<.div(^.fontSize := "175%", body))
        .build

    val container = dom.document.getElementById("root")
    Main().renderIntoDOM(container)
  }
}
```

Browser stack trace:

<img width="588" alt="screen shot 2019-02-03 at 00 55 31" src="https://user-images.githubusercontent.com/14335852/52166940-c9ea0400-274e-11e9-928f-d629725ea967.png">

Replication repo: https://github.com/allantl/scalajs-react-suspense

**Comment by japgolly** [comment]
Hey. I can reproduce your issue locally but there's a twist. If I copy-paste your code into scalajs-react's `AjaxExample1.scala` and launch gh-pages locally, the same code works fine without any error. 

https://github.com/japgolly/scalajs-react/blob/issue/522/gh-pages/src/main/scala/ghpages/examples/AjaxExample1.scala

This suggests to me that it might be an issue with scalajs-bundler or webpack.

**Comment by teozkr** [comment]
Looking into the emitted JS (by just running `fastOptJS`, bypassing the bundler), for some reason it seems to compile this:

```scala
val suspenseE = Raw.React.createElement(Raw.Suspense, suspenseP, lazyE)
```

into this:

```javascript
var suspenseE = $i_react.createElement($i_react, suspenseP, lazyE);
```

In other words, for some reason it's passing `React` as the component, rather than `React.Component`.

**Comment by teozkr** [comment]
This is because `japgolly.scalajs.react.raw.Suspense` is defined like this:

```scala
@JSImport("react", JSImport.Namespace, "React.Suspense")
@js.native
object Suspense extends js.Any
```

According to the documentation for the relevant overload of `JSImport`:

> Namespace import (import the module itself), with a fallback on a global variable.  
> When linking with module support, this is equivalent to @JSImport(module, name).  
> When linking without module support, this is equivalent to @JSGlobal(globalFallback). 

That means that if compiling for an environment without modules (such as a legacy browser environment) then it's (correctly) interpreted as an alias for `React.Suspense`, but if compiled for an environment *with* modules then it gets interpreted as `import * as Suspense from "react"`, which is obviously wrong.

**Comment by japgolly** [comment]
Hmmm, Github closed this when I merged the PR. v1.4.1 is on its way to Maven Central, give it a try and if this problem persists, please re-open this.

**Comment by teozkr** [comment]
Thanks!
