### ISSUE TITLE
withRef removes key on element in full build causing " Each child in an array or iterator should have a unique "key" prop."

### ISSUE THREAD

**Issue by chiller** [japgolly/scalajs-react#523]
I have reproduced the problem in this repo https://github.com/chiller/scalajs-react-key-debug

This code:
```
      <.div(
        <.div("loop container",
          (1 to 5).map( i =>
            if (i == 3) <.canvas(
              ^.key := s"swaggy-key-$i",
              ^.title := "anyone there?"
            ).withRef(canvasRef)
            else <.canvas( ^.key := s"swaggy-$i" )
          ).toVdomArray
        )
      )
```
shows up like this in the browser  after a full optimized build:
![screenshot 2019-02-12 at 14 45 43](https://user-images.githubusercontent.com/154856/52639598-e7e50080-2ed4-11e9-885f-71fca49e2a1e.png)

This causes the warning:
` Each child in an array or iterator should have a unique "key" prop.`

Edit: to clarify further: it doesn't happen on `sbt fastOptJS`

**Comment by japgolly** [comment]
A fix for this is coming soon in v1.4.2. Thanks a lot for providing a reproduction project. It helped a lot!!
