### ISSUE TITLE
TagMod from string does not typecheck

### ISSUE THREAD

**Issue by axos88** [japgolly/scalajs-react#543]
```
    val foo = Some(40)
    <.div(foo.map(_.toString).getOrElse("a"))
```

```
[error] /home/akos/xxx/foo.scala:34:40: type mismatch;
[error]  found   : Object
[error]  required: japgolly.scalajs.react.vdom.TagMod
[error]     <.div(foo.map(_.toString).getOrElse("a"))
```

`foo.map(_.toString).getOrElse("a")` should already be a `String`, but this fixed it (although IntelliJ arguably correctly highlights the `asIntanceOf[String]` call as unnecessary, since it should typecheck:

```
    val foo = Some(40)
    <.div(foo.map(_.toString).getOrElse("a").asInstanceOf[String])
```

Obviously this also works:
```
    val foo = Some(40)
    val bar = foo.map(_.toString).getOrElse("a")
    <.div(bar)
```

**Comment by japgolly** [comment]
I don't think there's anything that can be done about that. I think the only solution would be a change to Scala itself.

**Comment by japgolly** [comment]
Closing as there's nothing to be done here. We can always reopen if there's an idea about something that could be done.
