### ISSUE TITLE
Router does not ignore hash part

### ISSUE THREAD

**Issue by axos88** [japgolly/scalajs-react#546]
Is there a way to make the router ignore the hash part, if using `/`-based routes?

**Comment by dvkndn** [comment]
I believe the hash is indeed a part of the url that the router must take into account when using `/`-based routes :D so it's better if you do explicitly declare them. For example this is what we did:

https://github.com/anduintransaction/design/blob/10fc6d488b0f59bb2c221bbcae8b73807cf7e140/docsSrc/src/main/scala/design/anduin/docs/app/router/Router.scala#L42

https://github.com/anduintransaction/design/blob/10fc6d488b0f59bb2c221bbcae8b73807cf7e140/docsSrc/src/main/scala/design/anduin/docs/app/router/Router.scala#L59

This also allows us to link to the correct section using the goold old hash. For example: https://anduin.design/checkbox#indeterminate take you not only to the correct route but also the desired section

**Comment by japgolly** [comment]
I'm just reading the docs @ https://github.com/japgolly/scalajs-react/blob/master/doc/ROUTER.md

Seems you could just append `~ ("#" ~ remainingPath).option`

**Comment by axos88** [comment]
@japgolly Where in the docs is this mentioned? This feels like a workaround (for example in case of dynamic routes now I need to either pmap it to get rid of the remainingpath that I don't need (as @dvkndn mentioned, that part is taken care of by the browser), or add it to the case classes that I map to, which is a hack, since I don't actually need it only to satisfy the router.

The use case is an auth callback from `auth0`, which supplies the token and some data as part of the hash for some reason, and not as get parameters. I'm using a native library to parse out that data, and it's reading directly from `window.location`, so I have no reason to extract that info.

Also having any `#foo` links on a page would then brake the router, unless this hack is specified on every single route that has them.

I still feel like this should be a RouterConfig option to be able to globally enable/disable this.

**Comment by dvkndn** [comment]
I'm not japgolly but I think I can help you to clear something :sweat_smile: 

> @japgolly Where in the docs is this mentioned?

The documentation of scalajs-react is quite detailed, but also quite, well, technical. It shows you all that you can do instead of just the common ones. So what we are looking is somewhat a composition of:

> - RouteB[String] from the remainder of the unmatched URL.
> - remainingPath - Captures the (non-empty) remaining portion of the URL path.
> - a ~ b concatenates a to b. 
> - .option makes this subject portion of the route optional and turns a RouteB[A] into a RouteB[Option[A]]. Forms an isomorphism between None and an empty path.
> - .caseClass[A] maps the route type(s) to a case class.

Now to be honest I did spend quite a time to figure out what I showed you above. However, after that, it was pretty nice to know the whole thing :+1: 

> This feels like a workaround
> which is a hack, since I don't actually need it only to satisfy the router.

It's not really a hack or a workaround. In my opinion, this is quite expected. In a world of strong typing, you must explicit about what is going to exist, **no matter you are going to use it or not**. So if a part of the URL (the hash part) will be available, it's better (and safer) that we explicitly cover it

> I'm using a native library to parse out that data, and it's reading directly from window.location, so I have no reason to extract that info.

Ah, the convenient of JS world :D

> unless this hack is specified on every single route that has them.

Exactly what I did :sweat_smile: There are about 30 routes in my project and every single of them is strongly and explicitly allow this "hash" thing. Safeness > convenient, I think 

> I still feel like this should be a RouterConfig option to be able to globally enable/disable this.

I agree with this one, for the sake of convenient :D but I'm not sure it's possible

**Comment by axos88** [comment]
My problem, and why I still feel that including the same thing (that ends up unused) in thirty routes is a hack because the application's routing layer should not know or care about whether the rendered html contains a "scrolling link", one with a fragment in it (whose handling is completely handled by the browser). Seems like an single-responsibility violation and also that's a lot of code repetition.

If we follow this workaround - and I uphold my opinion on this - suddenly ** a basic change to the markup (adding a fragment link), that doesn't even touch the JS/ScalaJS code will require changes to the router, and this is definitely something I'd like to avoid. **

Now don't get me wrong, I'm a super-invested guy in strongly typing - and frown upon everything else - I guess that's why we use scalajs instead of js, right?, but this has very little to do with type safety. I don't see the connection between ignoring the fragment part, and the introduction of type safety issues. The fragment simply does not make part of the processed information (the same way the browsers widow size, or language settings are not part of the routing info - although I could imagine wanting to route the user to other routes based in that info - but in most cases it's not needed). It is also not part of the caseClass, so why should the framework assume it to be empty then? If we want to make an assumption to the fragment part of the url - we need to make it part of the caseClass for sure. But if we don't, it's actually counter-intuitive that we are making assumptions on it.

Also according to the [https://tools.ietf.org/html/rfc3986#section-3](RFC) the `fragment` part of the url is not part of the `path` (or in RFC terms the `hier-part`), so `remainingPath` is a bit misleading, it should only match up to the start of the fragment, or the query params. 

I understand that in some cases (like when people use fragment-based routing), the fragment must NOT be ignored, but in other cases (where people use real html5 path-level routing), it can be desired. So it should be a configuration option.

Having a caseClass without a parameter, and having it with an extra parameter that is never read (mind the difference between an optional field that is Some/None, and one that is NEVER read) contains exactly the same amount of information (actually if the compiler would be smart enough it could optimize it away). The principle of "something-that-contains-the-same-value" and "something-whose-value-is-only-written-and-never-read" carries NO information applies.

@japgolly what are you thougts on this?

So to solve this issue, I would consider something like this (although either a breaking change, or we need to find an alternative name for the remainingPath matcher). Note that this is just some raw brainstorming material here:

A router configuration parameter that allows partial matching the URL (ignoring the query or the fragment part, or both, or even the end of the path, but I'm not sure there is an actual use case for this)

  - `remainingUrl` should match everything (the way remainingPath works right now)
  - `remainingPath` should only match the path part of the url (the naive approach would suggest to 
match up to the first `?` or `#`). To keep backward compatibility, we should probably come up with a new name for this, and deprecate `remainingPath` in favour of `remaningUrl`
  - `remainingFragment` (should match the remaining fragment. Actually I'm not sure it's implementation would be any different to `remainingUrl`, unless we can make sure that we are actually already in the fragment part)
  - `ignoreFragment` (should be like '#' ~ remainingFragment), but provide Unit - in case you only want to   ignore it for a single route, or a few.
  - `remainingQuery` should match the remaining query params, and probably provide a `Map(String->String)`
  - possibly an `ignore` RouteMapper [is this a thing? ], that takes a RouteB[Any] and returns a RouteB[Unit] - this would allow to write things like ` / "stuff" / int / "bar" / uuid.option / remainingPath.ignore`

**Comment by japgolly** [comment]
FYI I haven't read or responded to this yet, but I do plan to when I have
time. Don't want you to mistake my silence for dismissal. Thanks for your
patience.

**Comment by axos88** [comment]
@japgolly ?
Just hit this again. And the fun part is that an external srervice is redirecting to my SPA, and I may or may not get a query part, and the order of the query arguments changes from request to request....

In this case I'd like the ability to extract the query params, but I don't care about their order... Accessing them from within the route is fine too though. (Possibly an initialStateFromProps, and access the data through ctl?)
