### ISSUE TITLE
Update scala.js bundler 0.15.0

### ISSUE THREAD

**Issue by ngbinh** [japgolly/scalajs-react#553]
https://scalacenter.github.io/scalajs-bundler/changelog.html#version-0.15.0
I think it is required to have scala.js 1.0 version of scala.js react

**Comment by japgolly** [comment]
Is there any changes required within scalajs-react? scalajs-react doesn't depend on scalajs-bundler and it seems that we're using a version of Scala.JS that's compatible with scalajs-bundler. I think we're already all good, right?

**Comment by ngbinh** [comment]
You are right in term of scala.js bundler. But I believe you will need to use scala.js bundler 15.0 to build scala.js react for scala.js 1.X

**Comment by japgolly** [comment]
My understanding is that bundler now supports scala.js 1.x but not the other way around. I believe when scala.js v1.x is ready I'll be able to use it without using bundler.

Are you ok to close this issue? When Scala.JS v1.x is ready I think it's better to have a new Scala.JS v1.x issue open.

**Comment by ngbinh** [comment]
supporting scala.js 1.X was the main goal of this ticket. You are right that we do not need scala.js bundler to do so.
