### ISSUE TITLE
Publish for scala 2.13.0

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#556]

**Comment by FabioPinheiro** [comment]
Has anyone tried compiling for Scala 2.13?
Are we block and other libraries?

**Comment by FabioPinheiro** [comment]
First we merge https://github.com/japgolly/scalajs-react/pull/551

**Comment by nafg** [comment]
@FabioPinheiro thanks for looking into it. Can you open a PR, I think it will expedite the process.

**Comment by FabioPinheiro** [comment]
For com.github.julien-truffaut # monocle-core and monocle-macro
We need updated the libs to 1.6.0 (Still on 1.6.0-RC1)

https://mvnrepository.com/artifact/com.github.julien-truffaut/monocle-core
https://mvnrepository.com/artifact/com.github.julien-truffaut/monocle-macro

**It seems from from the mvnrepository that they are dropping support for Scala 2.11**

I also don't know what is this cats especial library version.
It (still?) does not exit on version 1.6.0 but maybe is related with this pr
https://github.com/julien-truffaut/Monocle/pull/678

**Comment by FabioPinheiro** [comment]
utest also dropping support for Scala 2.11 https://mvnrepository.com/artifact/com.lihaoyi/utest

**Comment by cquiroz** [comment]
Monocle is going to support 2.13 soon after cats does. The PR you refer to is preparation work for that. scala 2.11 support is gone and scalaz support will also be frozen at the current version

**Comment by calvinmo** [comment]
Monocle cats now supports 2.13 (https://github.com/dragisak/monocle-cats/issues/3) which appears to be the final hold up on this ticket if I am not mistaken.

**Comment by cquiroz** [comment]
Why are you referring to `monocle-cats`? The original `Monocle` is now (starting in version 2.x) cats only. Is `monocle-cats` a fork?

**Comment by calvinmo** [comment]
If I missed something RE `Moncle` please forgive me.  But as far as I can see `Monocle` as well as `moncle-cats` (both of which are dependencies of this project).  I will admit though I haven't actually checked out this project and gone through the motions of the upgrade in question.

**Comment by cquiroz** [comment]
Don't worry I think it is just a name clash. But starting in 2.0 there will be a single `monocle` artifact and be cats only. There is still a scalaz based monocle with version 1.6

**Comment by calvinmo** [comment]
OK so it seems I am misinformed.  Ultimately I only desire for scalacss to support 2.13 (https://github.com/japgolly/scalacss/issues/153)  - what issue can I track to watch for when this library does support 2.13?

**Comment by FabioPinheiro** [comment]
@calvinmo the monocle-cats @japgolly reference on  https://github.com/japgolly/scalacss/issues/153 was the cats module of Monocle https://mvnrepository.com/artifact/com.github.julien-truffaut/monocle-core_2.12/1.5.0-cats 
See https://github.com/japgolly/scalajs-react/pull/559/files#diff-215113124f1de02f228327ba7abb45f7R18

@cquiroz Thanks for the clarification. 
We may want to upgrade this Library to `2.0.0-RC1` but may it would better better after supporting Scala 2.13. For now `1.6.0` is good enough or at less should be different should be a different PR/commit.

@calvinmo This is now only block by a bug https://github.com/scala/bug/issues/11660
Meanwhile there is still no RC. But if you want to try you can clone this PR https://github.com/japgolly/scalajs-react/pull/559 the and do a `publishLocal`

**Comment by japgolly** [comment]
Just a note on Monocle versions, I'm happy to just take the latest stable versions. It's not integral to scalajs-react itself which we keep dependency-free -- in fact if you look in the `.internal` package you'll see I've already hand-rolled a few optics because they're so small and simple to write :smile: 

Because the Monocle extension modules are just to provide a few useful integrations to users who are already using Monocle downstream I think it's ok to just take the latest working version without worrying about semver. In our case here I think we should just take the latest Monocle versions for both scalaz and cats that we need to get Scala 2.13 compilation. It sounds like we might be changing `ext-monocle` to depend on Monocle 2.x and cats, and replace `ext-monocle-cats` with `ext-monocle-scalaz` and keep it on 1.6. WDYT?

**Comment by nafg** [comment]
I didn't understand what the question has to do with semver. If it's a
question of bumping scalajs-react's major version number what's the reason
not to do so?

**Comment by japgolly** [comment]
My point is the opposite. Regardless of whatever version number Monocle chooses to use, if we need it in this PR, let's just use it in this PR. When we merge and release this PR, it will be v1.5.0-RC1.

**Comment by FabioPinheiro** [comment]
I agree with @japgolly. Monocle is bringing scalaz as a dependency on version 1.6 but will bring cats on the next version. Which may come and brake other libraries that depend on ScalaCss. 

Can you do a first RC or is anything missing?

**Comment by cquiroz** [comment]
I also agree with @japgolly. going in the future `monocle` scalaz probably won't be updated as there is a desire to maintain only one branch which would be cats based. It is really up to you to decide a version number. I suppose the cats version on `ext-cats` and `ext-monocle` need to be aligned

**Comment by japgolly** [comment]
> I suppose the cats version on ext-cats and ext-monocle need to be aligned

Yes, agree. Similarly the scalaz versions of ext-monocle-scalaz and ext-scalaz should be the same too.

> Can you do a first RC or is anything missing?

I think we just need to revise the monocle versions/modules still, right? If you don't beat me to it @FabioPinheiro , I'll get to it this coming weekend.

**Comment by nafg** [comment]
http://julien-truffaut.github.io/Monocle/release_notes.html says

> 2.0.0-RC1 (cats only)
> 1.6.0 (scalaz only, last major release with scalaz)

**Comment by japgolly** [comment]
v1.5.0-RC1 on its way to Maven Central with Scala 2.13 support (and some other things). Thanks again to @FabioPinheiro!!

https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/1.5.0.md

**Comment by nafg** [comment]
Can someone remind me if 1.5.0 final is blocked on anything?
