### ISSUE TITLE
Manual invocation of window.history.replaceState is converted into a pushState call

### ISSUE THREAD

**Issue by raquo** [japgolly/scalajs-react#585]
My use case is as follows:

* User arrives at `/section` URL which loads a ScalaJS-React SPA
* Loading that page triggers an AJAX request
* If AJAX returns a certain kind of response, I need to **replace** the URL with `/section/N`. I do not want to **push** this new URL, I specifically need to replace the `/section` entry in the history stack, because otherwise the browser's back button won't work properly.

Normally this is achieved by a `window.history.replaceState` call, however ScalaJS-React Router seemingly does not expose such functionality. I see how I can replaceState-redirect certain URLs, but that mechanism does not allow for fetching data asynchronously before deciding whether to redirect or not, as far as I can tell. Maybe I'm missing something?

Anyway, that would have been fine if I could just call `dom.window.history.replaceState` manually, but that doesn't work either – ScalaJS-React Router intercepts the call, and does a `pushState` instead.

There is no good way around this either. For example, a server-side redirect won't catch users who navigate to `/section` via ScalaJS-React Router, from some other page of the SPA.

**Comment by japgolly** [comment]
Sounds like we should add an overload of `def set(target: A)` like `def set(target: A, method: Redirect.Method)` so that you could specify `Redirect.Replace`.

**Comment by raquo** [comment]
@japgolly If that is possible, that would solve the issue entirely.

**Comment by japgolly** [comment]
Hey @raquo , I've just merged #587 to address this. Are you now happy to close this?

**Comment by raquo** [comment]
Yes, thank you very much! As you suggested, I will just use the new `def set(route: Route, via: SetRouteVia)` instead of the old `def set(route: Route)` to trigger a ReplaceState on demand.
