### ISSUE TITLE
Release for scalajs 1.0.x

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#599]
It would be great if we could get scalajs-react release for both 0.6 and 1.0 branches of scala.js

I wish cross compiling them were easier

**Comment by japgolly** [comment]
Yeah, tell me about it. Pain in the ass. But yeah, I'm keen on this too. Last I tried I was blocked by upstream dependencies. I'll try again soon.

**Comment by nafg** [comment]
Being that 1.0 is no longer prerelease, why bother publishing for 0.6.x anymore?

**Comment by cquiroz** [comment]
We’re still lacking several dependencies, in particular shapeless needs a fix on a macro to work with Scala.js 1.0 and shapeless is needed for Monocle, etc
I think cats an cats-effect also need a release with 1.0

**Comment by nafg** [comment]
Can you link to the relevant issues in those repos?

**Comment by nafg** [comment]
There are a bunch of @scala-steward PRs with dependency updates, that could help...

Cats 2.1.1 was just released for scalajs 1.0.0

Cats-effect PR: https://github.com/typelevel/cats-effect/pull/796

Monocle PR: https://github.com/julien-truffaut/Monocle/pull/817

There's this commit in Shapless but I don't see a release for it: https://github.com/milessabin/shapeless/commit/c7a9d60805bef519bdae5e8fd0b71fa9ee994b8c

**Comment by nafg** [comment]
https://github.com/milessabin/shapeless/pull/967#issuecomment-593135545:
> I've just back-published 2.3.3 for 2.{11,12,13}.

**Comment by matthughes** [comment]
Monocle 2.0.4 has been released. and Cats has been released with 2.1.2.

**Comment by nafg** [comment]
I guess you mean cats-effect. Does that mean that all upstream dependencies are published for scala.js 1.0? Is there anything else blocking?

**Comment by matthughes** [comment]
Yeah sorry I meant cats-effect.  I don't know about any scalaz dependencies but I believe those were the last big two.

**Comment by japgolly** [comment]
Scalaz itself is already published for SJS 1.0 but we still need a Monocle
1.6.x (the Scalaz version) to be published too

**Comment by cquiroz** [comment]
I don't think that will happen, Monocle 1.6 is not going to be updated, only the cats version

**Comment by japgolly** [comment]
I'm sure we can get Monocle 1.6 published for SJS 1.0 somehow. I don't want to elaborate now though :)

**Comment by nafg** [comment]
Any update?
Do we really need to have monocle-scalaz support when monocle dropped it?

**Comment by japgolly** [comment]
Good chance I'll be spending a lot of time on this very soon. A few non-tech real-life blockers to resolve first.

**Comment by fsvehla** [comment]
@japgolly Is there anything I can do to help?

**Comment by mikla** [comment]
Looks like we only wait `nyaya` to published for sjs1. All other dependencies are ready for sjs1.

**Comment by japgolly** [comment]
Monocle 1.6.x and Nyaya have been published for SJS 1.0. I believe that's all upstream dependencies on scalajs-react! :tada: Big thanks @mikla for the help!

**Comment by japgolly** [comment]
@fsvehla I only just now saw your message. Sorry about that. No I think we're good now, the roadblocks are clearing. That being said if there's anything in the issues that you'd like to work you're more than welcome too. :)

**Comment by japgolly** [comment]
I'm going to post progress here because I know there's a lot of interest. I started work on this yesterday. :tada: 

Unfortunately it's nowhere near as easy as any other library I've seen (because JS is a first-class citizen here as opposed to just a compilation-target for a fundamentally Scala library). After some failed attempts I don't think that cross-building is possible. I might try again once I get SJS 1.0 working.

Speaking of which, there are some subtle differences that aren't mentioned in the SJS 1.0 release notes. And I might have discovered some SJS bugs that we might end up having to wait for but I'm not sure yet...

Stay tuned.

**Comment by japgolly** [comment]
https://github.com/scala-js/scala-js/issues/4026

**Comment by japgolly** [comment]
https://github.com/scala-js/scala-js/issues/4029

**Comment by japgolly** [comment]
https://github.com/scala-js/scala-js/issues/4030

**Comment by japgolly** [comment]
https://github.com/scala-js/scala-js/issues/4031

**Comment by japgolly** [comment]
Got it working, merged!

**Comment by rpiaggio** [comment]
That's great news thank you so much!

**Comment by japgolly** [comment]
Thanks @rpiaggio ! Getting much closer to release. I'll look at your PR tomorrow.
