### ISSUE TITLE
classSet overrides className (and vice-versa)

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalajs-react#60]
More of a discussion point, but do you think classSet and className should be mutually exclusive?  Right now they are.  Even using just multiple classNames, the last declared one in wins.  Should we consider making them additive?

```
div(className := "foo", className := "bar")  // == <div className="foo bar">

// Above seems like a contrived example, but I ran into this like this:
// Helper method
def bootstrapInput(mods: TagMod*) = input(`type` := "text", className := "form-control")

// Use results in <input type="text" className="hasValidation" placeholder=Enter name" ></input>
bootstrapInput(placeholder := "Enter name", className := "hasValidation")
```

**Comment by japgolly** [comment]
FYI, it's not obvious from my previous post but I do acknowledge the need to have to different functions add to the `class` attribute. Just don't know (nor have thought too hard about) an appropriate solution. I definitely wouldn't code something specific to the `class` attribute, we'd have to think about how the solution would work with all attributes, and the effects of either changing `:=` semantics or adding a different operators, etc.

**Comment by japgolly** [comment]
Thought more about this. ClassName is 90%+ of cases that we're aware of so I decided it's worth it to make an exception (at least for now) to solve just this specific case, rather than putting it off trying to figure out the <10%.
