### ISSUE TITLE
ScalaJS 0.6.0 Build

### ISSUE THREAD

**Issue by benjaminjackman** [japgolly/scalajs-react#63]
Any plans/thoughts to build against the newer version of scala-js?

**Comment by japgolly** [comment]
Nah, none. They're still on milestones atm, when they reach RCs I'll start. I think that's still about a month off or so.

Am happy to take a PR for M3 and put it on a branch if people are interested.

**Comment by OlivierBlanvillain** [comment]
If you are feeling adventurous you can try my fork [1]. Things seems to work fine for my limited usage of React, but I was too lazy to port the tests because of all the dependencies.

[1]: https://github.com/OlivierBlanvillain/scalajs-react

**Comment by japgolly** [comment]
RC1 is out.
http://www.scala-js.org/news/2015/01/12/announcing-scalajs-0.6.0-RC1/

**Comment by japgolly** [comment]
Upgraded in 9a10cac12ee56f416af5e602c704f6f630d478d9.
Released 0.7.2-RC1.

**Comment by codeck** [comment]
0.6.0 is out
http://www.scala-js.org/news/2015/02/05/announcing-scalajs-0.6.0/

**Comment by japgolly** [comment]
Sorry for the delay; I was overseas. Build for 0.6.0 final is on its way...
