### ISSUE TITLE
Modularizing routing rules

### ISSUE THREAD

**Issue by ramnivas** [japgolly/scalajs-react#69]
Meta question: Is there a better venue to ask this kind of questions (a forum?). This question isn't an issue per se, but trying to understand design philosophy in order to use scalajs-react more effectively.

Is there a way to modularize routing rules? For example, I will like to have all person-related routes to be in a separate class/object and organization-related routes in another, and so on. Looking at the tutorial, it seems that there can be only one object that extends `RoutingRules` and the component based on it (`AppPage.router(...)`) needs to be rendered in the app.

In AngularJS, routing rules for a module goes with the module itself (and then through module dependency, aggregated at the app level).

**Comment by japgolly** [comment]
> Meta question: Is there a better venue to ask this kind of questions (a forum?). This question isn't an issue per se, but trying to understand design philosophy in order to use scalajs-react more effectively.

This project has started getting more questions and discussion than I expected. To be honest I also sort of wanted to see what it would be like to use Github for the purpose. It's not bad; I'm undecided. :) Also recently opened up a gitter chat room for this (link on front page). We'll see how that goes. If that's not effective I'll probably start a mailing list.

> Is there a way to modularize routing rules?

I don't see why not. The `RoutingRules` is just a trait, its open and you're free to use it however you wish. I imagine you could have modularised routing rules in separate traits and then mix them in as needed. Don't view `RoutingRules` as a box in which you have to squash your needs into, instead view it as a building block such that if there's something it doesn't do, you just create another building block on top of it as you like. In fact `RoutingRules` isn't even required to use `Router` itself.

> In AngularJS, routing rules for a module goes with the module itself (and then through module dependency, aggregated at the app level).

If Angular's design is the best choice for your project the power of Scala itself should be enough for you  to mimic it. I don't think Angular has much to offer in terms of successful design such that it would be the best solution to a problem in Scala.JS.

**Comment by japgolly** [comment]
I hope that helps. I'm going to close this issue now. If it's impossible for you to achieve your goal of modularised routes, reopen this issue and we'll fix it so that it gives you the right amount of freedom. If you want to submit a PR to provide a recommended way of modularised routes with some internal support, it'll probably be worth having some discussion first. Cheers.

**Comment by ramnivas** [comment]
Thanks!

Just in case someone comes across the same question, here is what I tried that works:

```scala
trait AboutRouting extends RoutingRules {
  val about = register(location("#about", AboutUs.Component))
}
```
and so on with each module with its own routing rules. And then:
```scala
object AppRouter {
  object AppPage extends AboutRouting with PersonRouting with ... {
    val root = register(rootLocation(Home.Component))

    override protected val notFound = redirect(root, Redirect.Replace)

    register(removeTrailingSlashes)

    override protected def interceptRender(i: InterceptionR): ReactElement = Menu.wrap(i.element)
  }

  val baseUrl = BaseUrl.fromWindowOrigin + "/"
  val C = AppPage.router(baseUrl)
}
```

In hindsight, this was too obvious!

p.s. I referred to AngularJS to point out parts that worked well for me in another moderate-size project and will like to see it work with scalajs-react (in the project itself or in a user-provided generic extension) as long as it doesn't contradict any core scalajs-react/react principles. For example, in issue #68, I liked that AngularJS took a common need (async loading of resources during routing) and provided a solution right out of the box.

p.p.s. I like scalajs-react so far. For the current project (not for an employer), I am explicitly trying to avoid most technologies that I am intimately familiar with in order to learn other possible approaches. React, scalajs-react, and scala.js falls into that category (but still using Scala that I have been programming in for a while!). Hoping that short-term pain will pay off in the long run (or I will have learned another approach's strengths and pitfalls!).

**Comment by ochrons** [comment]
Here's a short modularization example following @ramnivas code, but adding support for linking to other routes as well


```scala
trait Root1 extends RoutingRules {
  self: AllRoutes =>
  lazy val RootComponent = ReactComponentB[Router]("Root")
    .render(router =>
    <.div(
      <.h2("Router Demonstration"),
      <.div(router.link(root)("The 'root' route")),
      <.div(router.link(root2)("The 'root2' route")),
      <.div(router.link(root3)("The 'root3' route"))
    )
    ).build

  val root: Loc = register(rootLocation(RootComponent))
}

trait Root2 extends RoutingRules {
  self: AllRoutes =>
  lazy val Root2Component = ReactComponentB[Router]("Root2")
    .render(router =>
    <.div(
      <.h2("Router Demonstration 2"),
      <.div(router.link(root)("The 'root' route")),
      <.div(router.link(root3)("The 'root3' route"))
    )
    ).build

  val root2: Loc = register(location("#2", Root2Component))
}

trait Root3 extends RoutingRules {
  self: AllRoutes =>
  lazy val Root3Component = ReactComponentB[Router]("Root3")
    .render(router =>
    <.div(
      <.h2("Router Demonstration 3"),
      <.div(router.link(root)("The 'root' route")),
      <.div(router.link(root2)("The 'root2' route"))
    )
    ).build

  val root3: Loc = register(location("#3", Root3Component))
}

trait AllRoutes extends Root1 with Root2 with Root3

object MainRouter extends AllRoutes {
  override protected val notFound = redirect(root, Redirect.Replace)
}

object AdminMain extends JSApp {
  def main(): Unit = {
    val target = dom.document.body
    val baseUrl = BaseUrl(dom.window.location.href)
    val router = MainRouter.router(baseUrl)

    React.render(router(), target)
}
```

Perhaps there is a more convenient way to access links under other routers than using the ```self: AllRoutes =>``` method?

Note the baseUrl is using the full address so that it works nicely with local _fastOptJS_ testing.

**Comment by japgolly** [comment]
Heya, I'm overseas atm and have way less internet than I expected and so,
I'm unable to give any open source projects much attention until I get back
in a week, on the 8th. Only github access I have is via email replying. /cc
@chandu0101
