### ISSUE TITLE
Add helpers for zooming in on StateSnapshots in props that retain reusability

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#707]

**Comment by japgolly** [comment]
@rpiaggio continued from PR

> For this to work, both subcomponents would have to rerender whenever the Record changes, even if the value they are showing hasn't changed. This is because StateSnapshot wraps a SetFn, which isn't reusable in the zoomed-in StateSnapshots when the base value changes

Right, I think this is where the problem is. I don't have this problem because I make and use `Reusable` SetState fns. You can create the functions once at any level/depth without needing to know the full path back to the top stateful component. It's basically just a matter of creating the lens once, wrapping it in `Reusable` and storing it (usually as a `private val` in the `object` that houses the component that uses it). Adapting the functions into the right shape depending on how you plan to use it and what you have access to is what leads to variation in "how to do it" but the concept is the same. From a quick look at my code I've got snippets like:

```scala
    // In the top-level stateful component
    private val issuesPageSS =
      StateSnapshot.withReuse.zoomL(State.issuesPage).prepareVia($)

    // Also
    private val setFilterDead: Reusable[SetStateFnPure[FilterDead]] =
      Reusable.fn.state($ zoomStateL stateLensFilterDead).setStateFn

    def render(s: State) = {
      val state = issuesPageSS(s) // creates a reusable StateSnapshot
      def filterDeadSS = StateSnapshot.withReuse(s.filterDead)(setFilterDead)
```

In a "feature" which is like a mini library that you infuse into components (like React "hooks" but way more advanced, generic and capable):

```scala
  final case class Ctx[A, Change](stateAccess : StateAccessPure[State.ForEditor[A, Change]],
                                  asyncFeature: AsyncFeature.Write.D0[AsyncError])

  lazy val update: Reusable[SetStateFnPure[B]] =
    Reusable.byRef(stateAccess.toSetStateFn.contramap(newEditor))

  def newEditor: B => Some[E] =
    b => Some(editorCtor(StateSnapshot.withReuse(b)(update)))
```

In one case I just literally ask for it lol

```scala
  final case class Props(graph: ImplicationGraph.Props, setFilterDead: Reusable[StateSnapshot.SetFn[FilterDead]]) {
    @inline def render = Component(this)
  }

  def render(p: Props) = {

    val filterDeadButton =
      <.div(*.filterDeadButton,
        FilterDeadButton.Component(StateSnapshot.withReuse(p.graph.filterDead)(p.setFilterDead)))
```

This case here is probably the more directly applicable to what you're describing. And because we're having this discussion I've now realised that this case needs some direct support to make it easier. I'll do that today and get it in for the upcoming release. Here I'm creating a reusable `SetFn` that applies to any `StateSnapshot` passed in through props. I'm not doing a zoom but just imagine that it's in the body of the `Reusable.byRef`:

```scala
  final case class Props(filterDead: StateSnapshot[FilterDead])

  val setFilterDead: Reusable[StateSnapshot.SetFn[FilterDead]] =
    Reusable.byRef((v, cb) => $.props.flatMap(_.filterDead.setStateOption(v, cb)))

      <.div(*.headerFilterDeadButton,
        FilterDeadButton.whenLive(data.live)(StateSnapshot.withReuse(props.filterDead.value)(setFilterDead))))
```

**Comment by japgolly** [comment]
Hey @rpiaggio check out https://japgolly.github.io/scalajs-react/#examples/state-snapshot-2 and see what you think

**Comment by rpiaggio** [comment]
Hey @japgolly thank you so much for the extensive example! I had not figured out the `.withReuse.zoom*` usage and I see now how `StateSnapshot` is intended to be used. I'll definitely give it a try.

One question though: In method 1) is it necessary to store the reusable lenses? Or could they be created on the fly, eg: `p.ss.withReuse.zoomStateL(Reusable.byRef(Data.int))` ? If the answer is yes, I wouldn't mind a shorthand to do this, ie: `p.ss.newZoom(Data.int)`, that zooms into a `StateSnapshot` reusably.

**Comment by japgolly** [comment]
@rpiaggio  No worries man. I hope it's helpful!

Re method 1, it depends on whether `Data.int` is stable or not. If it's a `def` that returns different function *instances* each time it's called then no, inlining `Reusable.byRef` isn't going to work. The only way we/Reusability can check if you're using the same function/lens or a different one, is by reference equality. Eg. we don't compare ASTs or Java bytecode of functions. I actually gave a talk on this if you're interested: https://www.youtube.com/watch?v=9RvWDDZK3D8 I hope it would clarify exactly this point :)

Personally, I method 2. They're the same thing under the hood anyway, the only difference is the what the boilerplate looks like and where it goes.
