### ISSUE TITLE
Bug: zooming from StateSnapshot *instances* causes stale data

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#721]
Remove all the zoom methods from `InstanceMethodsWithReuse`. They don't work because the setters depend on the state value. Zooming with reuse has to start at `object StateSnapshot`.

Eg.
1. `SS(A(123, 456))` zoom left and right with reuse => `SS(123) | SS(456)`
2. `Left: setState(0)` => `A(123,456).copy(left = 0)` => `A(0, 456)`
3. `Right: setState(0)` => `A(123,456).copy(right = 0)` => `A(123, 0)` but should be `A(0, 0)`

Also update SS example 2. It shows two methods of zooming reuse but in light of this bug, it should be just one method.

**Comment by japgolly** [comment]
Actually don't remove the zoom methods. I think I've been here before and am going around in slow circles. Comment them out and explain why (or maybe make them deprecated forever and uncallable so that users get pointed to the right of doing it via doc or deprecation msg).

**Comment by japgolly** [comment]
FYI @cquiroz @rpiaggio . Remember the example I put online at https://japgolly.github.io/scalajs-react/#examples/state-snapshot-2 ? I said there were two options:

```md
1. Create Reusable lenses and call .withReuse.zoomL(lens)
2. Prepare a reusable setter using StateSnapshot.withReuse.zoomL.prepareViaProps
```

I made a mistake. Option 1 doesn't work. Option 2 is the proper solution.

**Comment by rpiaggio** [comment]
Thank you @japgolly for the heads up! I'm now giving `StateSnapshot` a try and I was going the `<instance>.withReuse.zoomState` way. I'll switch to always start from root then.
