### ISSUE TITLE
New Reusability.derive emits warnings with -Wunused:nowarn

### ISSUE THREAD

**Issue by rpiaggio** [japgolly/scalajs-react#735]
It seems that the new `Reusability.derive` macro introduced in `1.7.1` inserts a `@nowarn` annotation.

We use `-Wunused:nowarn`, which now produces a `@nowarn annotation does not suppress any warnings` warning, at least in some of its uses.

We also use `-Xfatal-warnings`....

**Comment by japgolly** [comment]
Oh wow I didn't know `-Wunused:nowarn` was a thing. With that flag enabled is there a way/hack to have a `@nowarn` that doesn't trigger if it's not used? Maybe `@nowarn("cat=unused,cat=nowarn")` or something?

**Comment by rpiaggio** [comment]
Thank you!

**Comment by japgolly** [comment]
No worries! Sorry about the trouble in the first place :)
