### ISSUE TITLE
Is there support for react's experimental concurrent mode?

### ISSUE THREAD

**Issue by ryanberckmans** [japgolly/scalajs-react#756]
Hi,

Is there support for react's experimental [concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html)?

If not, when might this be supported? I'd love to get a sense of whether this is six months or six years away.

Thanks!

**Comment by japgolly** [comment]
Hey @ryanberckmans . No it's not supported, I hadn't even heard of it to be honest :)
Once it's released as part of the official stable API, it'll be implemented here too. Hope that helps

**Comment by ryanberckmans** [comment]
Thanks!
