### ISSUE TITLE
problem with domAsHtml inside $.getDOMNode.map 

### ISSUE THREAD

**Issue by elkhadirzyad** [japgolly/scalajs-react#761]
in the version 1.1.1 

$.getDOMNode.map(_.domAsHtml.offsetHeight).runNow() did not give me any error

in the version 1.7.0

I got error in domAsHtml , it is not recognized.

**Comment by japgolly** [comment]
Please see the changelogs - from memory it was 1.3.0 & 1.4.0 but I could be wrong. But have a look through them, you answer is two of the majors 1.x.0 notes.
