### ISSUE TITLE
Monocle next version

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#763]
We are discussing about the next release of Monocle. There are relatively minor changes but te won't be able to easily make a release supporting scala.js 0.6.x. This is because one of the dependencies (discipline) dropped 0.6.x support

Would that affect `scalajs-react`?

**Comment by japgolly** [comment]
Go for it. If not Monocle, then it will soon be Cats because they were also saying the next major release will drop 0.6 support too. The official scalajs-react stance I broadcast a while a go is that we'll drop 0.6 support when our dependencies do.

**Comment by cquiroz** [comment]
Thanks will do so
