### ISSUE TITLE
How to implement a stack navigation?

### ISSUE THREAD

**Issue by epifab** [japgolly/scalajs-react#773]
Some context: I have a component that displays a paginated list of items. I can click on any item which take me to the item page. When I go back, however, I want to land in the exact same place I was before, which is for example in the middle of the list. I don't want the list to be reloaded.

I am looking at ways of implementing a stack navigator and I wonder if overriding the ReactRouter sounds like a good place to start.

**Comment by japgolly** [comment]
Yeah you could use the Router and have the item offset be part of the route/url.
