### ISSUE TITLE
Was scala.js 0.6.x dropped?

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#809]
If yes can you make that clearer in the 1.7.6 changelog (and anywhere else)?

If not, publishing for 0.6 must have failed and you might want to look into why.

**Comment by japgolly** [comment]
Nah it's not dropped yet. I'm surprised to see that it's not already
published. My house has been full of kids and constant distractions this
year, I must've just forgotten. I'll publish now...

**Comment by japgolly** [comment]
Ok, it's on Maven Central now.

**Comment by nafg** [comment]
Thanks!
