### ISSUE TITLE
Passing key to children

### ISSUE THREAD

**Issue by andreaferretti** [japgolly/scalajs-react#82]
I must be missing something, but I do not see a way to add the `key` property for an element of a list, unless that element is a component that I created myself. A typical case being trying to set a key for a `ReactTag` element. I  have tried both

    div(key := something)(...)

which fails with `not found: value key`, and

    div(...).set(key = something)

which fails with `value set is not a member of japgolly.scalajs.react.vdom.ReactTag`.

**Comment by japgolly** [comment]
The `.set(key = 123)` syntax is only for Components. This should work:
```scala
import japgolly.scalajs.react._, vdom.prefix_<^._
// ...
<.div(^.key := 123, "← This should work")
```

Are you importing `vdom.all._`? I advise against that because it pollutes your local namespace and then you have conflicts with your own `vals` or `defs` called `key`; this might be because of that. Also `keyAttr` is an alias in `all._` that you could try that is the issue but you prefix `all._`.

**Comment by andreaferretti** [comment]
It turns out I was importing `japgolly.scalajs.react.vdom.svg.all._`, assuming this was a superset of `japgolly.scalajs.react.vdom.all._`, but in fact `key` is not the former namespace. Importing it from the latter has solved my issue.

By the way, yes, I do not like to import that big a namespace, but I prefer to exclude/rename imports if a clash arises than having to prefix all my components and attrs, which in my opinion makes everything pretty undreadable

**Comment by japgolly** [comment]
I think it looks more readable with prefix. Amongst a sea of code, you can find the html very quickly by looking for:
```
  <.
    ^.
    ^.
    ^.
    ^.
      <.
      <.
```

But of course each to their own. Glad the import is fixed. Enjoy!
