### ISSUE TITLE
Scala 3 migration strategy

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#825]
Hi, what is the plan to port the codebase to dotty? Is that a WIP somewhere, or is that scheduled sometime in the future?

I tried using it via withDottyCompat and ran into some issues. There were a bunch of typing translation issues that said something about existentials. Also it couldn't call Callback#runNow but I think it was a scala.js bug that may have been fixed already.

**Comment by japgolly** [comment]
No plan at all atm. Next bunch of time I can spend on scalajs-react I'll be
adding hooks. I will eventually add Dotty support once Dotty is
more stable, otherwise if anyone wants it done faster and has the time and
inclination to contribute, it would be appreciated.

**Comment by japgolly** [comment]
Hey if you've made a start WDYT about creating a draft PR? We could work on it together, plus I've gotten a request from someone interested in helping.

**Comment by nafg** [comment]
I haven't but I did now, sort of. I only spent a few minutes playing with the build. I'll just post the output of git diff, and add some observations:

```diff
diff --git a/project/Build.scala b/project/Build.scala
index 252a52da..18df6c6f 100644
--- a/project/Build.scala
+++ b/project/Build.scala
@@ -32,6 +32,7 @@ object ScalajsReact {
     val ReactJs               = "16.14.0"
     val Scala212              = "2.12.11"
     val Scala213              = "2.13.3"
+    val Scala300M3            = "3.0.0-M3"
     val ScalaCollCompat       = "2.2.0"
     val ScalaJsDom            = "1.1.0"
     val ScalaJsTime           = "1.0.0"
@@ -94,12 +95,13 @@ object ScalajsReact {
   def commonSettings: PE =
     _.enablePlugins(ScalaJSPlugin, ScalafixPlugin)
       .settings(
-        scalaVersion                  := Ver.Scala213,
-        crossScalaVersions            := Seq(Ver.Scala212, Ver.Scala213),
+        scalaVersion                  := Ver.Scala300M3,
+        crossScalaVersions            := Seq(Ver.Scala212, Ver.Scala213, Ver.Scala300M3),
         scalacOptions                ++= scalacFlags,
         scalacOptions                ++= byScalaVersion {
                                            case (2, 12) => Nil
                                            case (2, 13) => scalac213Flags
+                                           case (3,  0) => Nil
                                          }.value,
         //scalacOptions               += "-Xlog-implicits",
         incOptions                    := incOptions.value.withLogRecompileOnMacro(false),
diff --git a/project/plugins.sbt b/project/plugins.sbt
index e4659019..ad8385d2 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,5 +1,5 @@
 val scalaJSVersion =
-  Option(System.getenv("SCALAJS_VERSION")).filter(_.nonEmpty).getOrElse("1.2.0")
+  Option(System.getenv("SCALAJS_VERSION")).filter(_.nonEmpty).getOrElse("1.3.1")
 
 libraryDependencies ++= {
   if (scalaJSVersion.startsWith("0."))
@@ -29,3 +29,5 @@ addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"       % "3.9.5")
 }
 
 // addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.10.0")
+
+addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.5.1")
```

1. First update everything to the latest version (merging all @scala-steward PRs... have you considered having @mergify merge them automatically?
2. Probably worth first pruning old versions. Drop 2.12 (?) and scala.js 0.6.x. Delete everything that exists in order to support them. The simpler the build is, the easier it will be.
3. Likewise if there are any significant things that you plan to deprecated or remove, maybe now is the time. The less there is to port, the better. (To remove something you need a middle version where it's just deprecated so people can get warnings guiding their migration, but you don't need to wait, you could just publish a stepping-stone version and a next version at the same time.)
4. For me the biggest issue is not that the library is not published for 3.0, but that .withDottyCompat has issues with it. So it could be beneficial to just refactor whatever code to compile across 2.13 and 3.0.0, without worrying about really making it work on 3.0. For example, comment out macros if necessary (using `???` as necessary), so you can focus on refactoring things while staying scala 2-focused. If that is enough to guide you to refactor away from existential types etc., and you can publish that for scala 2, it would enable using it with `.withDottyCompat`
5. Ultimately you will have to tackle macros. You can do this with per-scala-version source directories, like `src/main/scala-2`. SBT supports this out of the box but I'm not sure the exact naming it uses. Anyway it can be customized. So you would have different code implementing a source-compatible interface in different scala-version-specific source directories. (You can make them implement an interface to enforce the source-compatibility for things other than actual macros.)
6. The build needs a lot of fiddling. For anything that is not published for scala 3 you need .withDottyCompat (and don't publish until that can be removed). The scala-reflect dependency needs to be removed for Scala 3.
7. Dealing with all the scalac flags is annoying. sbt-tpolecat might help. In general someone needs to make an sbt plugin (or pure scala library) that lets you express scalac flags in a typesafe way, and that makes sure you do the right thing per version.

**Comment by nafg** [comment]
Hi, any update?

**Comment by japgolly** [comment]
Hey @nafg, yeah sorry about the lack of reply. Update is that as of yesterday I've started focusing on this full time so you'll be able to see a ton of progress on this and other features start appearing over the next few months.
