### ISSUE TITLE
Component that accepts children

### ISSUE THREAD

**Issue by andreaferretti** [japgolly/scalajs-react#83]
I am trying to write a wrapper component that puts a panel around whatever children are passed.

In React, I can usually do something like

    var Frame = React.createComponent({
      render: function() {
        return <div>{ props.children }</div>
      }
    });

and then use it like

    <Frame>some content</Frame>

I assume that in Scalajs-React I can explicitly pass some props that contains `Seq[ReactComponents]` as a property, but I was wondering if the case of passing children, which has special treatment in React, also gets a special treatment here

**Comment by japgolly** [comment]
I'm not sure what you mean about special treatment but it is supported. Please see the docs and/or example code from the main README. (If the docs are unclear, PRs are appreciated. :+1: )

Finally, it's better to ask questions and seek advice here ↓ instead of creating Github issues:
https://gitter.im/japgolly/scalajs-react

**Comment by andreaferretti** [comment]
I am sorry, but gitter requires access to my organization data, and I am not sure I can provide it. I will reply here, but if you find it unconvenient, just tell me, I don't want to be annoying.

In any case, I could not find any examples, either in the README or in the demo, where a component wraps other components like, say, [this one](http://react-bootstrap.github.io/components.html#panels).

I will try to better frame my question. In native React, every component implicitly accepts a list of children components, and children are passed differently from other props (say in JSX they appear as children nodes, while other props appear as attributes).

I can explicitly pass a `List[ReactComponent]` in the props, but I was wondering whether I am missing a similar mechanism (that is, every component implicitly accepting a list of children).

**Comment by japgolly** [comment]
Mate I need to go but hopefully this excerpt from the tests is enough to
answer your questions. Talk to you later.

https://github.com/japgolly/scalajs-react/blob/master/test/src/test/scala/japgolly/scalajs/react/CoreTest.scala#L233-L248

**Comment by ochrons** [comment]
You can check out my tutorial at https://github.com/ochrons/scalajs-spa-tutorial for an example of a `Panel` that wraps around its children.

**Comment by andreaferretti** [comment]
Thank you both, it works perfectly!

For future readers: what works is passing the children after the props when instantiating the component, and using a form of `render` with two parameters, like this:

    val Panel = ReactComponentB[Props]
      .render((props, children) =>
       div(className := "hello", children)
      )
      .build

    ...
    div(Panel(someProps, div("world")))

**Comment by japgolly** [comment]
Glad to hear it. When you have a `ComponentScope` or `BackendScope` instances, you can also access the children via `$.propsChildren`, similar to `this.props.children` in React.

https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/ReactComponentB.scala#L48-L49

**Comment by marcadella** [comment]
Just for the record: to make a childless component accept children, 
- Replace `.renderBackend[Backend]` with `.renderBackendWithChildren[Backend]`
- Replace `def apply(p: Props) = component(p)` with `def apply(p: Props)(child: ChildArg*) = component(p)(child:_*)`
- Replace `def render(p: Props, s: State)` with `def render(p: Props, children: PropsChildren, s: State)`
- Use the children in the `render` method (for example using `vdomNodeFromPropsChildren(children)`)
