### ISSUE TITLE
lineHeight style typo

### ISSUE THREAD

**Issue by Kyprus** [japgolly/scalajs-react#84]
The css name is currently `lineheight` when it should be `line-height`

**Comment by japgolly** [comment]
Already fixed on master. v0.8.1 will be released this week with this change.

**Comment by Kyprus** [comment]
I could have sworn I had seen a fix but I couldn't find it. Thanks!

**Comment by japgolly** [comment]
Even I checked the changelog to confirm. :D

It came in under PR #73
​
