### ISSUE TITLE
Components as classes and/or traits (ES6?)

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#87]
React is moving towards ES6 classes being the default form of existence for components. Voices in gitter all approve a similar transition in Scala.

Note: This will be in addition to `ReactComponentB` which won't be removed.

**Comment by chandu0101** [comment]
>Note: This will be in addition to ReactComponentB which won't be removed.
yay , no rewrites! , thanks mate let me know if you need any help in trivial/tedious tasks :)

**Comment by japgolly** [comment]
Thanks @chandu0101! We'll see how it goes :smile:

**Comment by japgolly** [comment]
Tried but this is a bit more involving than I'd hoped. I have a strong feeling that persevering with this now will cost me time rewriting it when React 0.14 comes out due to some changes they're making around this. Instead I'm going to push this to the release when we upgrade to React 0.14.

**Comment by japgolly** [comment]
Note to self: http://egorsmirnov.me/2015/05/22/react-and-es6-part1.html

**Comment by japgolly** [comment]
Backends are getting closer and closer to components as classes. (63aea4a241f23f9a142e53926a4f5f49d176c7a3, #78)

Idea: with a small change we could do:

```scala
class Backend($: BackendScope[Props, State]) { ... }

val Component = ReactComponentB[Backend] // With macro, P S B all known in one step
  .initialState(...)
  .build
```

Can also set the DOM node type too:
```scala
class Backend($: BackendScopeN[Props, State, html.Table]) {
```

Actually this is great. A type with no constraints at all (a class construtor param) can tell us all the static information about a component in one line with no repetition anywhere else. Can even have different `ReactComponentB` path depending on static info. This should makes it easy to solve #171 too.

**Comment by japgolly** [comment]
As of 1.0, Scala component builder now creates ES6 classes (by default) for your Scala components.
There's also a unit test confirming that one can directly extend the ES6 facade and use it like any other component in scalajs-react.
