### ISSUE TITLE
queryToMap does not support repeated parameters

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#901]
A common convention is to represent arrays as a repeated parameter. So `example.com?a=1&a=2` results in `a = [1, 2]`. In any case, however it should be interpreted it is valid to have (and want) a URL with multiple query parameters with the same name. That is why query maps are usually represented in Scala as `Map[String, Seq[String]]`. Unfortunately `queryMap` uses `Map[String, String]`, limiting its applicability.

To fix it would be a breaking API change, of course.

**Comment by japgolly** [comment]
@nafg Use the new `queryMultimap` (or `querySeq`) in the upcoming release
