### ISSUE TITLE
Release 2.0.0-RC1

### ISSUE THREAD

**Issue by jetaggart** [japgolly/scalajs-react#932]
I'm starting a new project and would like to use this lib with scala 3. I noticed you merged scala 3 support into master. I'm struggling to get things set up. Is the snapshot published somewhere? Or is there an example that's up to date with master?

Sorry if I'm missing something obvious, fairly new to this stack!

**Comment by japgolly** [comment]
Hey @jetaggart, no there isn't a snapshot published anywhere yet with Scala 3 support. I plan to release 2.0.0-RC1 late next week which will be the first release supporting Scala 3. If you want to get started earlier you could check this repo out and do `publishLocal` and use the local SNAPSHOT until next week.

**Comment by japgolly** [comment]
> Sorry if I'm missing something obvious, fairly new to this stack!

Oh btw ^^ no problem at all! Feel free to checkout the Gitter room as the community there is awesomely supportive, especially of newcomers.

**Comment by jetaggart** [comment]
Awesome, thank you! Definitely excited for the 2.0 release!

**Comment by japgolly** [comment]
2.0.0-RC1 is on its way to Maven Central :tada: 

Changelog: https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/2.0.0.md

**Comment by tomasherman** [comment]
👏 amazing, thanks :)
