### ISSUE TITLE
ReactHooks release

### ISSUE THREAD

**Issue by tomasherman** [japgolly/scalajs-react#933]
Hello,

first of all thanks for this library (and esp its documentation), it's pretty cool! I see you've recently added support for react hooks but it has not been released yet. Any ETA on when it might happen? It seems that i need them in order to work with material-ui components. 

Thanks a lot :)

**Comment by japgolly** [comment]
Hey @tomasherman , thanks for the kind words! I plan to publish a release towards the end of this week. If I run into trouble this week then definitely next week but either way, not long to go. Also if you don't mind I'll close this in favour of #932. Cheers
