### ISSUE TITLE
Race condition with `Callback`

### ISSUE THREAD

**Issue by tomasherman** [japgolly/scalajs-react#944]
Hello, 

thanks for this great library. I have some issues with `Callback`, though. But maybe it's my misunderstanding. Consider following code:

```scala
  def cb1 = CallbackTo(println("starting1")).delayMs(1000).toCallback.flatMap(_ => Callback(println("stopped1")))
  def cb2 = CallbackTo(println("starting2")).flatMap(_ => Callback(println("stopped2")))

  val cmp = for {
    _ <- cb1
    _ <- cb2
  } yield ()

  cmp.runNow()
```

My expectation would be the following output
```
starting1
(1000ms delay)
stopped1
starting2
stopped2
```

However - what i observe is the following:
![image](https://user-images.githubusercontent.com/99870/125905707-19889686-c9fb-47a5-a01f-75b34b5a947f.png)

Am i missing something? I'm quite experienced with running monadic code and this seems pretty straight-forward. So i'm not sure where the mistake is. The code, of course, is a simplification of me trying to do ajax and running into race conditions

**Comment by japgolly** [comment]
Hey before you go offline: I'm online now and trying an answer. "Hold the phone"...

**Comment by japgolly** [comment]
The reason it doesn't work as you're expecting as cos of the difference in semantics between `Callback` and `AsyncCallback`. Check out `before` and `after` below. It should clarify things.

```scala
/*
This is equivalent to:

  setTimeout(1000, () => println("starting1"))
  println("stopped1")
  println("starting1")
  println("stopped2")
*/

val before = {
  def cb1 = CallbackTo(println("starting1")).delayMs(1000).toCallback.flatMap(_ => Callback(println("stopped1")))
  def cb2 = CallbackTo(println("starting2")).flatMap(_ => Callback(println("stopped2")))
  val cmp = for {
    _ <- cb1
    _ <- cb2
  } yield ()
}

/*
This is equivalent to:

  setTimeout(1000, () => println("starting1"))
  println("stopped1")
  println("starting1")
  println("stopped2")
*/

val after = {
  def cb1 = // type is AsyncCallback[Unit]
    for {
      _ <- CallbackTo(println("starting1")).delayMs(1000)
      _ <- Callback(println("stopped1")).asAsyncCallback
      _ <- AsyncCallback.delay(println("stopped1")) // alternate version of above
    } yield ()

  def cb2 = CallbackTo(println("starting2")).flatMap(_ => Callback(println("stopped2")))

  val cmp = for {
    _ <- cb1.toCallback
    _ <- cb2
  } yield ()
}
```

**Comment by japgolly** [comment]
Also have a look at https://japgolly.github.io/scalajs-react/#examples/ajax-2

It shows how to use ajax via `AsyncCallback` and even demonstrates async `traverse`

**Comment by tomasherman** [comment]
Awesome! Backported this to my real code and it works as expected. So the long story short, use AsyncCallback as long as you can before converting it to Callback. Thank you!

**Comment by japgolly** [comment]
You're very welcome! Enjoy!

> So the long story short, use AsyncCallback as long as you can before converting it to Callback.

Yeah exactly. That's literally one of my usage mantras too :)
