### ISSUE TITLE
React 0.13

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#95]
http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html

**Comment by ngbinh** [comment]
:+1:

**Comment by ngbinh** [comment]
@japgolly I would love to take a bite on this. Do you have any idea on how to accomplish this?

**Comment by japgolly** [comment]
Hey @ngbinh feel free to mate! PRs are always welcome :)

I haven't thought about what's needed - that's usually the hard part, the implementation isn't very hard when you know what you need.

(To be honest there's a new React out every few months and you keep changing what you changed last time, and most of the time there's not much benefit for us in Scala-land. I was actually thinking of leaving 0.13 for now cos I haven't had enough time, then upgrading straight to 0.14 when it comes out.)

**Comment by ngbinh** [comment]
Ok. I'll see what I can do.  Thanks

**Comment by japgolly** [comment]
As mentioned before, there's not enough benefit in upgrading to React 0.13 to justify the (large) cost of time & effort upgrading, and the disruption to our API (and your code as a user).

I'll upgrade directly to React 0.14 when it comes out. (And I will do this regardless of what's in React 0.14 cos we don't want to diverge for too long.)

**Comment by ngbinh** [comment]
Agreed! At the moment, scala.js react already pulls in react 0.13.2 so there is little incentive to upgrade the scala.js part.

**Comment by bblfish** [comment]
Note: scalajs-react 0.8.4 downgraded back to the 0.12.1 React.

**Comment by japgolly** [comment]
In the README? That was a misleading typo by a bad search/replace in 23a24ecdfeb000657c0636d95995571993b7dca8

React 0.13 isn't supported but you can still use it in that it should work so far as any React 0.12 code would work with 0.13. Just that there's no Scala access to new features in 0.13.
