### ISSUE TITLE
Router should have helpers for breadcrumb or similar widgets

### ISSUE THREAD

**Issue by aparo** [japgolly/scalajs-react#96]
Supporting breadcrumb will be a nice feature.
From @japgolly words:

> It'll be a bit tough because the router doesn't have good support for dynamically identifying which route you're on - it was something I didn't think of when I wrote it - but I think that's the only piece of the puzzle you need to write breadcrumb nicely.

**Comment by japgolly** [comment]
Closed via 93bbc5f1fc1fa3af7b30c7c7ef6689ed992f061b.

There's a [new Router](https://github.com/japgolly/scalajs-react/tree/93bbc5f1fc1fa3af7b30c7c7ef6689ed992f061b/extra/src/main/scala/japgolly/scalajs/react/extra/router2) coming in 0.9 that fixes this.

Unlike the v1 Router which uses `val`s in a `RoutingRules` object, the new one expects that you create a tiny model for your pages (solving this). For example, if there is a page showing a photo, the model can be `case class ViewPhotoPage(photoId: Long)` and when the page is being rendered, you will get a `ViewPhotoPage` instance which will make breadcrumbs very easy - it will just be pattern matching on your pages.

Example of [page ADT](https://github.com/japgolly/scalajs-react/blob/93bbc5f1fc1fa3af7b30c7c7ef6689ed992f061b/test/src/test/scala/japgolly/scalajs/react/extra/router2/RouterTest.scala#L15-L18) and [routing rules](https://github.com/japgolly/scalajs-react/blob/93bbc5f1fc1fa3af7b30c7c7ef6689ed992f061b/test/src/test/scala/japgolly/scalajs/react/extra/router2/RouterTest.scala#L43-L48).
