### ISSUE TITLE
Debounce with javascript component

### ISSUE THREAD

**Issue by tomasherman** [japgolly/scalajs-react#967]
Hello, im trying to use debounce feature with an material-ui autocomplete onInputChange api, which expects a function that returns unit.

I have this code to get the callback into required shape:
```scala
      val onInputChange = (_: Any, input: String) => {
        if(input != null && input != "") {
          StateManagementClient.suggestSecurity(input).debounce(Duration.ofSeconds(5)).flatMap(state.zoomStateL(State.suggestions).setState(_).asAsyncCallback).runNow()
        }
      }
```
But it's not working ... instead of just processing the latest event, all events are processed with the delay provided - this is somewhat obvious as for new change of the input, new code mentioned above is started. But im not sure how to combine these two features together. Any guidance would be very appreciated. Thanks! :)

**Comment by japgolly** [comment]
Hey. Yeah the thing about `.debounce` is that it's by necessity stateful cos it needs to track little windows of time. This means that when you use `.debounce` you've got to save the resulting callback as a `val` somewhere and reuse it, so that it reuses the same underlying state. Atm you're creating a new callback each time, running it, and then it disappears from memory meaning that new debounce state is recreated each time you call it.

My suggestion would be to save the latest `input` value somewhere in your `onInputChange` method, then pull it back out again from a debounced Callback `val`. Does that make sense?

Here's a quick excerpt I've ripped out of the [ShipReq](https://shipreq.com) codebase that demonstrates the concept:

```scala
    private def updateShowResultsNow: Callback = {
      def update(s: State, now: Instant): Option[State] = {
        val showResults =
          s.hasQuery && (s.focus match {
            case None                           => false
            case Some(FocusState.Focused)       => true
            case Some(FocusState.LostFocus(at)) =>
              val sinceMs = now.toEpochMilli - at.toEpochMilli
              sinceMs < BlurToleranceMs
          })
        Option.when(showResults != s.showResults)(s.copy(showResults = showResults))
      }

      lazy val repeatIfNecessary: Callback =
        $.props.flatMap { p =>
          val s = p.state.value
          val needRepeat =
            s.focus match {
              case Some(FocusState.LostFocus(_)) if s.showResults => true
              case _                                              => false
            }
          Callback.when(needRepeat)(updateShowResultsNow.delayMs(10).toCallback)
        }

      for {
        now <- CallbackTo.now
        p   <- $.props
        _   <- p.state.modStateOption(update(_, now), repeatIfNecessary)
      } yield ()
    }

    // Saving as val after the debounce here is key
    private val updateShowResultsOnTextChange: Callback =
      updateShowResultsNow.debounceMs(typingDelayMs)

      // This is the event handler like your onInputChange
      def onTextChange(e: ReactEventFromInput): Callback = {
        val newText = e.target.value
        $.props.flatMap(_.state.modState(_.copy(text = newText), updateShowResultsOnTextChange))
      }
```

Hope that helps!

**Comment by tomasherman** [comment]
Thanks a lot. It does make sense and the example def helps. I will try to implement it this way.

**Comment by tomasherman** [comment]
Thanks. The solution was actually super simple...what i did is i created `val debounceBoundary = AsyncEffect.unit.debounce(...)` in the object that defines the component and then i just did in the `onInputChange` something like `debounceBoundary >> callHttpServer` and it seems to be working well. Thanks a lot again!

**Comment by japgolly** [comment]
No worries! That's a very nice and simple approach! I hadn't thought of that! I'll add the `debounce` methods directly to `object AsyncCallback` to make it even easier. Thanks!

**Comment by tomasherman** [comment]
Perfect
