### ISSUE TITLE
How to create a hook API extension with optional parameters?

### ISSUE THREAD

**Issue by rpiaggio** [japgolly/scalajs-react#983]
I'm following the guidelines for [hook API extensions](https://github.com/japgolly/scalajs-react/blob/master/doc/HOOKS.md#api-extensions).

The extension methods under `Primary` allow defining default values for parameters, but I'm having trouble with `Secondary` since parameters are wrapped in `CtxFn`.

What would be the recommended way to proceed here?

**Comment by japgolly** [comment]
No solid recommendation, just find a way that works and compiles (make sure you double-check that all the overloads work as expected, especially the type inference).

Some ideas:
* Have all the variants you like in `Primary` but in `Secondary` just have one method that accepts all arguments (using `Option` if necessary)
* Name the methods differently depending on the arity
* Make a custom hook with all the nice construction api you need, and then use it via `.customHook{,By}`

**Comment by rpiaggio** [comment]
Thank you, after exploring options a bit we settled for having only one parameter, which is a class containing the actual parameters. We can instantiate this class in varios ways, have `with` methods, etc.
